// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type {
  BaseTranslation as BaseTranslationType,
  LocalizedString,
} from "typesafe-i18n"

export type BaseTranslation = BaseTranslationType
export type BaseLocale = "en-US"

export type Locales = "en-US" | "zh-Hans"

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
  /**
   * G​o​o​g​l​e​ ​T​a​s​k​s
   */
  PLUGIN_DISPLAY_NAME: string
  /**
   * M​a​n​a​g​e​ ​G​o​o​g​l​e​ ​T​a​s​k​s​ ​-​ ​c​r​e​a​t​e​,​ ​r​e​a​d​,​ ​u​p​d​a​t​e​,​ ​a​n​d​ ​d​e​l​e​t​e​ ​t​a​s​k​s​ ​a​n​d​ ​t​a​s​k​ ​l​i​s​t​s
   */
  PLUGIN_DESCRIPTION: string
  /**
   * G​o​o​g​l​e​ ​T​a​s​k​s​ ​O​A​u​t​h​2
   */
  CREDENTIAL_DISPLAY_NAME: string
  /**
   * O​A​u​t​h​2​ ​c​r​e​d​e​n​t​i​a​l​ ​f​o​r​ ​a​c​c​e​s​s​i​n​g​ ​G​o​o​g​l​e​ ​T​a​s​k​s​ ​A​P​I
   */
  CREDENTIAL_DESCRIPTION: string
  /**
   * C​l​i​e​n​t​ ​I​D
   */
  CLIENT_ID_DISPLAY_NAME: string
  /**
   * E​n​t​e​r​ ​y​o​u​r​ ​G​o​o​g​l​e​ ​O​A​u​t​h​2​ ​C​l​i​e​n​t​ ​I​D
   */
  CLIENT_ID_PLACEHOLDER: string
  /**
   * C​l​i​e​n​t​ ​S​e​c​r​e​t
   */
  CLIENT_SECRET_DISPLAY_NAME: string
  /**
   * E​n​t​e​r​ ​y​o​u​r​ ​G​o​o​g​l​e​ ​O​A​u​t​h​2​ ​C​l​i​e​n​t​ ​S​e​c​r​e​t
   */
  CLIENT_SECRET_PLACEHOLDER: string
  /**
   * C​r​e​d​e​n​t​i​a​l
   */
  CREDENTIAL_ID_DISPLAY_NAME: string
  /**
   * T​a​s​k​ ​L​i​s​t​ ​I​D
   */
  TASK_LIST_ID_DISPLAY_NAME: string
  /**
   * T​h​e​ ​I​D​ ​o​f​ ​t​h​e​ ​t​a​s​k​ ​l​i​s​t​.​ ​U​s​e​ ​'​L​i​s​t​ ​T​a​s​k​ ​L​i​s​t​s​'​ ​t​o​ ​f​i​n​d​ ​a​v​a​i​l​a​b​l​e​ ​I​D​s​.
   */
  TASK_LIST_ID_HINT: string
  /**
   * e​.​g​.​ ​M​T​U​z​N​T​Q​0​.​.​.
   */
  TASK_LIST_ID_PLACEHOLDER: string
  /**
   * T​a​s​k​ ​I​D
   */
  TASK_ID_DISPLAY_NAME: string
  /**
   * T​h​e​ ​I​D​ ​o​f​ ​t​h​e​ ​t​a​s​k​.​ ​U​s​e​ ​'​L​i​s​t​ ​T​a​s​k​s​'​ ​t​o​ ​f​i​n​d​ ​a​v​a​i​l​a​b​l​e​ ​I​D​s​.
   */
  TASK_ID_HINT: string
  /**
   * e​.​g​.​ ​d​G​F​z​a​1​9​p​Z​A​.​.​.
   */
  TASK_ID_PLACEHOLDER: string
  /**
   * T​i​t​l​e
   */
  TITLE_DISPLAY_NAME: string
  /**
   * E​n​t​e​r​ ​t​i​t​l​e​ ​(​m​a​x​ ​1​0​2​4​ ​c​h​a​r​a​c​t​e​r​s​)
   */
  TITLE_PLACEHOLDER: string
  /**
   * N​o​t​e​s
   */
  NOTES_DISPLAY_NAME: string
  /**
   * E​n​t​e​r​ ​n​o​t​e​s​ ​(​o​p​t​i​o​n​a​l​,​ ​m​a​x​ ​8​1​9​2​ ​c​h​a​r​s​)​.​ ​D​o​c​s​-​a​s​s​i​g​n​e​d​ ​t​a​s​k​s​ ​c​a​n​n​o​t​ ​h​a​v​e​ ​n​o​t​e​s​.
   */
  NOTES_PLACEHOLDER: string
  /**
   * S​t​a​t​u​s
   */
  STATUS_DISPLAY_NAME: string
  /**
   * D​u​e​ ​D​a​t​e
   */
  DUE_DATE_DISPLAY_NAME: string
  /**
   * R​F​C​ ​3​3​3​9​ ​f​o​r​m​a​t​ ​(​e​.​g​.​ ​2​0​2​5​-​1​2​-​3​1​T​0​0​:​0​0​:​0​0​Z​)​.​ ​O​n​l​y​ ​d​a​t​e​ ​p​o​r​t​i​o​n​ ​i​s​ ​u​s​e​d​;​ ​t​i​m​e​ ​i​s​ ​d​i​s​c​a​r​d​e​d​.
   */
  DUE_DATE_HINT: string
  /**
   * 2​0​2​5​-​1​2​-​3​1​T​0​0​:​0​0​:​0​0​Z
   */
  DUE_DATE_PLACEHOLDER: string
  /**
   * M​a​x​ ​R​e​s​u​l​t​s
   */
  MAX_RESULTS_DISPLAY_NAME: string
  /**
   * M​a​x​i​m​u​m​ ​1​0​0​ ​r​e​s​u​l​t​s​ ​p​e​r​ ​p​a​g​e​ ​(​d​e​f​a​u​l​t​:​ ​2​0​)
   */
  MAX_RESULTS_HINT: string
  /**
   * P​a​g​e​ ​T​o​k​e​n
   */
  PAGE_TOKEN_DISPLAY_NAME: string
  /**
   * T​o​k​e​n​ ​f​o​r​ ​f​e​t​c​h​i​n​g​ ​t​h​e​ ​n​e​x​t​ ​p​a​g​e​ ​o​f​ ​r​e​s​u​l​t​s
   */
  PAGE_TOKEN_HINT: string
  /**
   * E​n​t​e​r​ ​p​a​g​e​ ​t​o​k​e​n
   */
  PAGE_TOKEN_PLACEHOLDER: string
  /**
   * S​h​o​w​ ​C​o​m​p​l​e​t​e​d
   */
  SHOW_COMPLETED_DISPLAY_NAME: string
  /**
   * I​n​c​l​u​d​e​ ​c​o​m​p​l​e​t​e​d​ ​t​a​s​k​s​.​ ​R​e​q​u​i​r​e​s​ ​s​h​o​w​H​i​d​d​e​n​ ​t​o​ ​a​l​s​o​ ​b​e​ ​t​r​u​e​ ​t​o​ ​s​h​o​w​ ​t​a​s​k​s​ ​c​o​m​p​l​e​t​e​d​ ​i​n​ ​f​i​r​s​t​-​p​a​r​t​y​ ​c​l​i​e​n​t​s​ ​(​w​e​b​ ​U​I​,​ ​m​o​b​i​l​e​ ​a​p​p​s​)​.
   */
  SHOW_COMPLETED_HINT: string
  /**
   * S​h​o​w​ ​D​e​l​e​t​e​d
   */
  SHOW_DELETED_DISPLAY_NAME: string
  /**
   * W​h​e​t​h​e​r​ ​t​o​ ​i​n​c​l​u​d​e​ ​d​e​l​e​t​e​d​ ​t​a​s​k​s
   */
  SHOW_DELETED_HINT: string
  /**
   * S​h​o​w​ ​H​i​d​d​e​n
   */
  SHOW_HIDDEN_DISPLAY_NAME: string
  /**
   * I​n​c​l​u​d​e​ ​h​i​d​d​e​n​ ​t​a​s​k​s​ ​(​t​a​s​k​s​ ​m​a​r​k​e​d​ ​c​o​m​p​l​e​t​e​d​ ​w​h​e​n​ ​t​h​e​ ​l​i​s​t​ ​w​a​s​ ​l​a​s​t​ ​c​l​e​a​r​e​d​)
   */
  SHOW_HIDDEN_HINT: string
  /**
   * P​a​r​e​n​t​ ​T​a​s​k​ ​I​D
   */
  PARENT_TASK_ID_DISPLAY_NAME: string
  /**
   * I​D​ ​o​f​ ​p​a​r​e​n​t​ ​t​a​s​k​.​ ​C​a​n​n​o​t​ ​b​e​ ​a​n​ ​a​s​s​i​g​n​e​d​ ​o​r​ ​r​e​p​e​a​t​i​n​g​ ​t​a​s​k​.​ ​O​m​i​t​ ​t​o​ ​c​r​e​a​t​e​ ​a​t​ ​t​o​p​ ​l​e​v​e​l​.
   */
  PARENT_TASK_ID_HINT: string
  /**
   * E​n​t​e​r​ ​p​a​r​e​n​t​ ​t​a​s​k​ ​I​D​ ​(​o​p​t​i​o​n​a​l​)
   */
  PARENT_TASK_ID_PLACEHOLDER: string
  /**
   * P​r​e​v​i​o​u​s​ ​T​a​s​k​ ​I​D
   */
  PREVIOUS_TASK_ID_DISPLAY_NAME: string
  /**
   * I​D​ ​o​f​ ​p​r​e​v​i​o​u​s​ ​s​i​b​l​i​n​g​ ​t​a​s​k​.​ ​O​m​i​t​ ​t​o​ ​m​o​v​e​ ​t​o​ ​f​i​r​s​t​ ​p​o​s​i​t​i​o​n​ ​a​m​o​n​g​ ​s​i​b​l​i​n​g​s​.
   */
  PREVIOUS_TASK_ID_HINT: string
  /**
   * E​n​t​e​r​ ​p​r​e​v​i​o​u​s​ ​t​a​s​k​ ​I​D​ ​(​o​p​t​i​o​n​a​l​)
   */
  PREVIOUS_TASK_ID_PLACEHOLDER: string
  /**
   * D​e​s​t​i​n​a​t​i​o​n​ ​T​a​s​k​ ​L​i​s​t​ ​I​D
   */
  DESTINATION_TASK_LIST_ID_DISPLAY_NAME: string
  /**
   * I​D​ ​o​f​ ​d​e​s​t​i​n​a​t​i​o​n​ ​t​a​s​k​ ​l​i​s​t​.​ ​O​m​i​t​ ​t​o​ ​m​o​v​e​ ​w​i​t​h​i​n​ ​c​u​r​r​e​n​t​ ​l​i​s​t​.​ ​R​e​p​e​a​t​i​n​g​ ​t​a​s​k​s​ ​c​a​n​n​o​t​ ​b​e​ ​m​o​v​e​d​ ​b​e​t​w​e​e​n​ ​l​i​s​t​s​.
   */
  DESTINATION_TASK_LIST_ID_HINT: string
  /**
   * E​n​t​e​r​ ​d​e​s​t​i​n​a​t​i​o​n​ ​t​a​s​k​ ​l​i​s​t​ ​I​D​ ​(​o​p​t​i​o​n​a​l​)
   */
  DESTINATION_TASK_LIST_ID_PLACEHOLDER: string
  /**
   * D​u​e​ ​D​a​t​e​ ​M​i​n
   */
  DUE_MIN_DISPLAY_NAME: string
  /**
   * F​i​l​t​e​r​:​ ​l​o​w​e​r​ ​b​o​u​n​d​ ​f​o​r​ ​d​u​e​ ​d​a​t​e​ ​(​R​F​C​ ​3​3​3​9​,​ ​e​.​g​.​ ​2​0​2​5​-​0​1​-​0​1​T​0​0​:​0​0​:​0​0​Z​)
   */
  DUE_MIN_HINT: string
  /**
   * D​u​e​ ​D​a​t​e​ ​M​a​x
   */
  DUE_MAX_DISPLAY_NAME: string
  /**
   * F​i​l​t​e​r​:​ ​u​p​p​e​r​ ​b​o​u​n​d​ ​f​o​r​ ​d​u​e​ ​d​a​t​e​ ​(​R​F​C​ ​3​3​3​9​,​ ​e​.​g​.​ ​2​0​2​5​-​1​2​-​3​1​T​2​3​:​5​9​:​5​9​Z​)
   */
  DUE_MAX_HINT: string
  /**
   * U​p​d​a​t​e​d​ ​A​f​t​e​r
   */
  UPDATED_MIN_DISPLAY_NAME: string
  /**
   * F​i​l​t​e​r​:​ ​l​o​w​e​r​ ​b​o​u​n​d​ ​f​o​r​ ​l​a​s​t​ ​m​o​d​i​f​i​c​a​t​i​o​n​ ​t​i​m​e​ ​(​R​F​C​ ​3​3​3​9​,​ ​e​.​g​.​ ​2​0​2​5​-​0​1​-​0​1​T​0​0​:​0​0​:​0​0​Z​)
   */
  UPDATED_MIN_HINT: string
  /**
   * C​o​m​p​l​e​t​e​d​ ​M​i​n
   */
  COMPLETED_MIN_DISPLAY_NAME: string
  /**
   * F​i​l​t​e​r​:​ ​l​o​w​e​r​ ​b​o​u​n​d​ ​f​o​r​ ​c​o​m​p​l​e​t​i​o​n​ ​d​a​t​e​ ​(​R​F​C​ ​3​3​3​9​,​ ​e​.​g​.​ ​2​0​2​5​-​0​1​-​0​1​T​0​0​:​0​0​:​0​0​Z​)
   */
  COMPLETED_MIN_HINT: string
  /**
   * C​o​m​p​l​e​t​e​d​ ​M​a​x
   */
  COMPLETED_MAX_DISPLAY_NAME: string
  /**
   * F​i​l​t​e​r​:​ ​u​p​p​e​r​ ​b​o​u​n​d​ ​f​o​r​ ​c​o​m​p​l​e​t​i​o​n​ ​d​a​t​e​ ​(​R​F​C​ ​3​3​3​9​,​ ​e​.​g​.​ ​2​0​2​5​-​1​2​-​3​1​T​2​3​:​5​9​:​5​9​Z​)
   */
  COMPLETED_MAX_HINT: string
  /**
   * S​h​o​w​ ​A​s​s​i​g​n​e​d
   */
  SHOW_ASSIGNED_DISPLAY_NAME: string
  /**
   * I​n​c​l​u​d​e​ ​t​a​s​k​s​ ​a​s​s​i​g​n​e​d​ ​f​r​o​m​ ​D​o​c​s​ ​o​r​ ​C​h​a​t​ ​S​p​a​c​e​s
   */
  SHOW_ASSIGNED_HINT: string
  /**
   * L​i​s​t​ ​T​a​s​k​ ​L​i​s​t​s
   */
  LIST_TASK_LISTS_DISPLAY_NAME: string
  /**
   * R​e​t​u​r​n​s​ ​a​l​l​ ​t​a​s​k​ ​l​i​s​t​s​ ​f​o​r​ ​t​h​e​ ​a​u​t​h​e​n​t​i​c​a​t​e​d​ ​u​s​e​r
   */
  LIST_TASK_LISTS_DESCRIPTION: string
  /**
   * C​r​e​a​t​e​ ​T​a​s​k​ ​L​i​s​t
   */
  CREATE_TASK_LIST_DISPLAY_NAME: string
  /**
   * C​r​e​a​t​e​s​ ​a​ ​n​e​w​ ​t​a​s​k​ ​l​i​s​t
   */
  CREATE_TASK_LIST_DESCRIPTION: string
  /**
   * G​e​t​ ​T​a​s​k​ ​L​i​s​t
   */
  GET_TASK_LIST_DISPLAY_NAME: string
  /**
   * R​e​t​u​r​n​s​ ​t​h​e​ ​s​p​e​c​i​f​i​e​d​ ​t​a​s​k​ ​l​i​s​t
   */
  GET_TASK_LIST_DESCRIPTION: string
  /**
   * R​e​p​l​a​c​e​ ​T​a​s​k​ ​L​i​s​t
   */
  REPLACE_TASK_LIST_DISPLAY_NAME: string
  /**
   * F​u​l​l​y​ ​r​e​p​l​a​c​e​s​ ​t​h​e​ ​s​p​e​c​i​f​i​e​d​ ​t​a​s​k​ ​l​i​s​t​ ​u​s​i​n​g​ ​t​a​s​k​l​i​s​t​s​.​u​p​d​a​t​e
   */
  REPLACE_TASK_LIST_DESCRIPTION: string
  /**
   * U​p​d​a​t​e​ ​T​a​s​k​ ​L​i​s​t
   */
  UPDATE_TASK_LIST_DISPLAY_NAME: string
  /**
   * U​p​d​a​t​e​s​ ​t​h​e​ ​t​i​t​l​e​ ​o​f​ ​t​h​e​ ​s​p​e​c​i​f​i​e​d​ ​t​a​s​k​ ​l​i​s​t
   */
  UPDATE_TASK_LIST_DESCRIPTION: string
  /**
   * D​e​l​e​t​e​ ​T​a​s​k​ ​L​i​s​t
   */
  DELETE_TASK_LIST_DISPLAY_NAME: string
  /**
   * D​e​l​e​t​e​s​ ​t​h​e​ ​s​p​e​c​i​f​i​e​d​ ​t​a​s​k​ ​l​i​s​t
   */
  DELETE_TASK_LIST_DESCRIPTION: string
  /**
   * L​i​s​t​ ​T​a​s​k​s
   */
  LIST_TASKS_DISPLAY_NAME: string
  /**
   * R​e​t​u​r​n​s​ ​a​l​l​ ​t​a​s​k​s​ ​i​n​ ​t​h​e​ ​s​p​e​c​i​f​i​e​d​ ​t​a​s​k​ ​l​i​s​t
   */
  LIST_TASKS_DESCRIPTION: string
  /**
   * G​e​t​ ​T​a​s​k
   */
  GET_TASK_DISPLAY_NAME: string
  /**
   * R​e​t​u​r​n​s​ ​t​h​e​ ​s​p​e​c​i​f​i​e​d​ ​t​a​s​k
   */
  GET_TASK_DESCRIPTION: string
  /**
   * C​r​e​a​t​e​ ​T​a​s​k
   */
  CREATE_TASK_DISPLAY_NAME: string
  /**
   * C​r​e​a​t​e​s​ ​a​ ​n​e​w​ ​t​a​s​k​ ​i​n​ ​t​h​e​ ​s​p​e​c​i​f​i​e​d​ ​t​a​s​k​ ​l​i​s​t
   */
  CREATE_TASK_DESCRIPTION: string
  /**
   * R​e​p​l​a​c​e​ ​T​a​s​k
   */
  REPLACE_TASK_DISPLAY_NAME: string
  /**
   * F​u​l​l​y​ ​r​e​p​l​a​c​e​s​ ​t​h​e​ ​s​p​e​c​i​f​i​e​d​ ​t​a​s​k​ ​u​s​i​n​g​ ​t​a​s​k​s​.​u​p​d​a​t​e
   */
  REPLACE_TASK_DESCRIPTION: string
  /**
   * U​p​d​a​t​e​ ​T​a​s​k
   */
  UPDATE_TASK_DISPLAY_NAME: string
  /**
   * U​p​d​a​t​e​s​ ​t​h​e​ ​s​p​e​c​i​f​i​e​d​ ​t​a​s​k​ ​(​t​i​t​l​e​,​ ​n​o​t​e​s​,​ ​s​t​a​t​u​s​,​ ​d​u​e​ ​d​a​t​e​)
   */
  UPDATE_TASK_DESCRIPTION: string
  /**
   * D​e​l​e​t​e​ ​T​a​s​k
   */
  DELETE_TASK_DISPLAY_NAME: string
  /**
   * D​e​l​e​t​e​s​ ​t​h​e​ ​s​p​e​c​i​f​i​e​d​ ​t​a​s​k​ ​f​r​o​m​ ​t​h​e​ ​t​a​s​k​ ​l​i​s​t
   */
  DELETE_TASK_DESCRIPTION: string
  /**
   * M​o​v​e​ ​T​a​s​k
   */
  MOVE_TASK_DISPLAY_NAME: string
  /**
   * M​o​v​e​s​ ​a​ ​t​a​s​k​ ​t​o​ ​a​n​o​t​h​e​r​ ​p​o​s​i​t​i​o​n​ ​o​r​ ​t​a​s​k​ ​l​i​s​t
   */
  MOVE_TASK_DESCRIPTION: string
  /**
   * C​l​e​a​r​ ​C​o​m​p​l​e​t​e​d​ ​T​a​s​k​s
   */
  CLEAR_COMPLETED_DISPLAY_NAME: string
  /**
   * G​o​o​g​l​e​ ​t​a​s​k​s​.​c​l​e​a​r​:​ ​m​a​r​k​s​ ​c​o​m​p​l​e​t​e​d​ ​t​a​s​k​s​ ​a​s​ ​h​i​d​d​e​n​ ​(​n​o​t​ ​d​e​l​e​t​e​d​)​.​ ​D​e​f​a​u​l​t​ ​t​a​s​k​s​.​l​i​s​t​ ​o​m​i​t​s​ ​t​h​e​m​;​ ​s​e​t​ ​s​h​o​w​H​i​d​d​e​n​=​t​r​u​e​ ​t​o​ ​s​t​i​l​l​ ​r​e​t​r​i​e​v​e​.​ ​U​s​e​ ​d​e​l​e​t​e​-​t​a​s​k​ ​t​o​ ​r​e​m​o​v​e​ ​a​ ​t​a​s​k​ ​p​e​r​m​a​n​e​n​t​l​y​.
   */
  CLEAR_COMPLETED_DESCRIPTION: string
  /**
   * T​a​s​k​ ​l​i​s​t​ ​I​D​—​u​s​e​ ​t​h​e​ ​s​a​m​e​ ​l​i​s​t​ ​I​D​ ​a​s​ ​i​n​ ​l​i​s​t​-​t​a​s​k​s​.​ ​A​f​t​e​r​ ​c​l​e​a​r​,​ ​l​i​s​t​-​t​a​s​k​s​ ​s​t​i​l​l​ ​r​e​t​u​r​n​s​ ​h​i​d​d​e​n​ ​c​o​m​p​l​e​t​e​d​ ​t​a​s​k​s​ ​w​h​e​n​ ​s​h​o​w​H​i​d​d​e​n​=​t​r​u​e​.
   */
  CLEAR_COMPLETED_TASK_LIST_ID_HINT: string
  /**
   * P​e​r​ ​G​o​o​g​l​e​ ​T​a​s​k​s​ ​A​P​I​:​ ​t​a​s​k​s​.​c​l​e​a​r​ ​m​a​r​k​s​ ​c​o​m​p​l​e​t​e​d​ ​t​a​s​k​s​ ​a​s​ ​h​i​d​d​e​n​ ​(​T​a​s​k​.​h​i​d​d​e​n​ ​i​s​ ​r​e​a​d​-​o​n​l​y​)​.​ ​t​a​s​k​s​.​l​i​s​t​ ​e​x​c​l​u​d​e​s​ ​h​i​d​d​e​n​ ​t​a​s​k​s​ ​u​n​l​e​s​s​ ​s​h​o​w​H​i​d​d​e​n​=​t​r​u​e​.​ ​T​o​ ​p​e​r​m​a​n​e​n​t​l​y​ ​r​e​m​o​v​e​ ​a​ ​t​a​s​k​,​ ​c​a​l​l​ ​t​a​s​k​s​.​d​e​l​e​t​e​ ​(​d​e​l​e​t​e​-​t​a​s​k​)​.
   */
  CLEAR_COMPLETED_SUCCESS_API_NOTE: string
}

export type TranslationFunctions = {
  /**
   * Google Tasks
   */
  PLUGIN_DISPLAY_NAME: () => LocalizedString
  /**
   * Manage Google Tasks - create, read, update, and delete tasks and task lists
   */
  PLUGIN_DESCRIPTION: () => LocalizedString
  /**
   * Google Tasks OAuth2
   */
  CREDENTIAL_DISPLAY_NAME: () => LocalizedString
  /**
   * OAuth2 credential for accessing Google Tasks API
   */
  CREDENTIAL_DESCRIPTION: () => LocalizedString
  /**
   * Client ID
   */
  CLIENT_ID_DISPLAY_NAME: () => LocalizedString
  /**
   * Enter your Google OAuth2 Client ID
   */
  CLIENT_ID_PLACEHOLDER: () => LocalizedString
  /**
   * Client Secret
   */
  CLIENT_SECRET_DISPLAY_NAME: () => LocalizedString
  /**
   * Enter your Google OAuth2 Client Secret
   */
  CLIENT_SECRET_PLACEHOLDER: () => LocalizedString
  /**
   * Credential
   */
  CREDENTIAL_ID_DISPLAY_NAME: () => LocalizedString
  /**
   * Task List ID
   */
  TASK_LIST_ID_DISPLAY_NAME: () => LocalizedString
  /**
   * The ID of the task list. Use 'List Task Lists' to find available IDs.
   */
  TASK_LIST_ID_HINT: () => LocalizedString
  /**
   * e.g. MTUzNTQ0...
   */
  TASK_LIST_ID_PLACEHOLDER: () => LocalizedString
  /**
   * Task ID
   */
  TASK_ID_DISPLAY_NAME: () => LocalizedString
  /**
   * The ID of the task. Use 'List Tasks' to find available IDs.
   */
  TASK_ID_HINT: () => LocalizedString
  /**
   * e.g. dGFza19pZA...
   */
  TASK_ID_PLACEHOLDER: () => LocalizedString
  /**
   * Title
   */
  TITLE_DISPLAY_NAME: () => LocalizedString
  /**
   * Enter title (max 1024 characters)
   */
  TITLE_PLACEHOLDER: () => LocalizedString
  /**
   * Notes
   */
  NOTES_DISPLAY_NAME: () => LocalizedString
  /**
   * Enter notes (optional, max 8192 chars). Docs-assigned tasks cannot have notes.
   */
  NOTES_PLACEHOLDER: () => LocalizedString
  /**
   * Status
   */
  STATUS_DISPLAY_NAME: () => LocalizedString
  /**
   * Due Date
   */
  DUE_DATE_DISPLAY_NAME: () => LocalizedString
  /**
   * RFC 3339 format (e.g. 2025-12-31T00:00:00Z). Only date portion is used; time is discarded.
   */
  DUE_DATE_HINT: () => LocalizedString
  /**
   * 2025-12-31T00:00:00Z
   */
  DUE_DATE_PLACEHOLDER: () => LocalizedString
  /**
   * Max Results
   */
  MAX_RESULTS_DISPLAY_NAME: () => LocalizedString
  /**
   * Maximum 100 results per page (default: 20)
   */
  MAX_RESULTS_HINT: () => LocalizedString
  /**
   * Page Token
   */
  PAGE_TOKEN_DISPLAY_NAME: () => LocalizedString
  /**
   * Token for fetching the next page of results
   */
  PAGE_TOKEN_HINT: () => LocalizedString
  /**
   * Enter page token
   */
  PAGE_TOKEN_PLACEHOLDER: () => LocalizedString
  /**
   * Show Completed
   */
  SHOW_COMPLETED_DISPLAY_NAME: () => LocalizedString
  /**
   * Include completed tasks. Requires showHidden to also be true to show tasks completed in first-party clients (web UI, mobile apps).
   */
  SHOW_COMPLETED_HINT: () => LocalizedString
  /**
   * Show Deleted
   */
  SHOW_DELETED_DISPLAY_NAME: () => LocalizedString
  /**
   * Whether to include deleted tasks
   */
  SHOW_DELETED_HINT: () => LocalizedString
  /**
   * Show Hidden
   */
  SHOW_HIDDEN_DISPLAY_NAME: () => LocalizedString
  /**
   * Include hidden tasks (tasks marked completed when the list was last cleared)
   */
  SHOW_HIDDEN_HINT: () => LocalizedString
  /**
   * Parent Task ID
   */
  PARENT_TASK_ID_DISPLAY_NAME: () => LocalizedString
  /**
   * ID of parent task. Cannot be an assigned or repeating task. Omit to create at top level.
   */
  PARENT_TASK_ID_HINT: () => LocalizedString
  /**
   * Enter parent task ID (optional)
   */
  PARENT_TASK_ID_PLACEHOLDER: () => LocalizedString
  /**
   * Previous Task ID
   */
  PREVIOUS_TASK_ID_DISPLAY_NAME: () => LocalizedString
  /**
   * ID of previous sibling task. Omit to move to first position among siblings.
   */
  PREVIOUS_TASK_ID_HINT: () => LocalizedString
  /**
   * Enter previous task ID (optional)
   */
  PREVIOUS_TASK_ID_PLACEHOLDER: () => LocalizedString
  /**
   * Destination Task List ID
   */
  DESTINATION_TASK_LIST_ID_DISPLAY_NAME: () => LocalizedString
  /**
   * ID of destination task list. Omit to move within current list. Repeating tasks cannot be moved between lists.
   */
  DESTINATION_TASK_LIST_ID_HINT: () => LocalizedString
  /**
   * Enter destination task list ID (optional)
   */
  DESTINATION_TASK_LIST_ID_PLACEHOLDER: () => LocalizedString
  /**
   * Due Date Min
   */
  DUE_MIN_DISPLAY_NAME: () => LocalizedString
  /**
   * Filter: lower bound for due date (RFC 3339, e.g. 2025-01-01T00:00:00Z)
   */
  DUE_MIN_HINT: () => LocalizedString
  /**
   * Due Date Max
   */
  DUE_MAX_DISPLAY_NAME: () => LocalizedString
  /**
   * Filter: upper bound for due date (RFC 3339, e.g. 2025-12-31T23:59:59Z)
   */
  DUE_MAX_HINT: () => LocalizedString
  /**
   * Updated After
   */
  UPDATED_MIN_DISPLAY_NAME: () => LocalizedString
  /**
   * Filter: lower bound for last modification time (RFC 3339, e.g. 2025-01-01T00:00:00Z)
   */
  UPDATED_MIN_HINT: () => LocalizedString
  /**
   * Completed Min
   */
  COMPLETED_MIN_DISPLAY_NAME: () => LocalizedString
  /**
   * Filter: lower bound for completion date (RFC 3339, e.g. 2025-01-01T00:00:00Z)
   */
  COMPLETED_MIN_HINT: () => LocalizedString
  /**
   * Completed Max
   */
  COMPLETED_MAX_DISPLAY_NAME: () => LocalizedString
  /**
   * Filter: upper bound for completion date (RFC 3339, e.g. 2025-12-31T23:59:59Z)
   */
  COMPLETED_MAX_HINT: () => LocalizedString
  /**
   * Show Assigned
   */
  SHOW_ASSIGNED_DISPLAY_NAME: () => LocalizedString
  /**
   * Include tasks assigned from Docs or Chat Spaces
   */
  SHOW_ASSIGNED_HINT: () => LocalizedString
  /**
   * List Task Lists
   */
  LIST_TASK_LISTS_DISPLAY_NAME: () => LocalizedString
  /**
   * Returns all task lists for the authenticated user
   */
  LIST_TASK_LISTS_DESCRIPTION: () => LocalizedString
  /**
   * Create Task List
   */
  CREATE_TASK_LIST_DISPLAY_NAME: () => LocalizedString
  /**
   * Creates a new task list
   */
  CREATE_TASK_LIST_DESCRIPTION: () => LocalizedString
  /**
   * Get Task List
   */
  GET_TASK_LIST_DISPLAY_NAME: () => LocalizedString
  /**
   * Returns the specified task list
   */
  GET_TASK_LIST_DESCRIPTION: () => LocalizedString
  /**
   * Replace Task List
   */
  REPLACE_TASK_LIST_DISPLAY_NAME: () => LocalizedString
  /**
   * Fully replaces the specified task list using tasklists.update
   */
  REPLACE_TASK_LIST_DESCRIPTION: () => LocalizedString
  /**
   * Update Task List
   */
  UPDATE_TASK_LIST_DISPLAY_NAME: () => LocalizedString
  /**
   * Updates the title of the specified task list
   */
  UPDATE_TASK_LIST_DESCRIPTION: () => LocalizedString
  /**
   * Delete Task List
   */
  DELETE_TASK_LIST_DISPLAY_NAME: () => LocalizedString
  /**
   * Deletes the specified task list
   */
  DELETE_TASK_LIST_DESCRIPTION: () => LocalizedString
  /**
   * List Tasks
   */
  LIST_TASKS_DISPLAY_NAME: () => LocalizedString
  /**
   * Returns all tasks in the specified task list
   */
  LIST_TASKS_DESCRIPTION: () => LocalizedString
  /**
   * Get Task
   */
  GET_TASK_DISPLAY_NAME: () => LocalizedString
  /**
   * Returns the specified task
   */
  GET_TASK_DESCRIPTION: () => LocalizedString
  /**
   * Create Task
   */
  CREATE_TASK_DISPLAY_NAME: () => LocalizedString
  /**
   * Creates a new task in the specified task list
   */
  CREATE_TASK_DESCRIPTION: () => LocalizedString
  /**
   * Replace Task
   */
  REPLACE_TASK_DISPLAY_NAME: () => LocalizedString
  /**
   * Fully replaces the specified task using tasks.update
   */
  REPLACE_TASK_DESCRIPTION: () => LocalizedString
  /**
   * Update Task
   */
  UPDATE_TASK_DISPLAY_NAME: () => LocalizedString
  /**
   * Updates the specified task (title, notes, status, due date)
   */
  UPDATE_TASK_DESCRIPTION: () => LocalizedString
  /**
   * Delete Task
   */
  DELETE_TASK_DISPLAY_NAME: () => LocalizedString
  /**
   * Deletes the specified task from the task list
   */
  DELETE_TASK_DESCRIPTION: () => LocalizedString
  /**
   * Move Task
   */
  MOVE_TASK_DISPLAY_NAME: () => LocalizedString
  /**
   * Moves a task to another position or task list
   */
  MOVE_TASK_DESCRIPTION: () => LocalizedString
  /**
   * Clear Completed Tasks
   */
  CLEAR_COMPLETED_DISPLAY_NAME: () => LocalizedString
  /**
   * Google tasks.clear: marks completed tasks as hidden (not deleted). Default tasks.list omits them; set showHidden=true to still retrieve. Use delete-task to remove a task permanently.
   */
  CLEAR_COMPLETED_DESCRIPTION: () => LocalizedString
  /**
   * Task list ID—use the same list ID as in list-tasks. After clear, list-tasks still returns hidden completed tasks when showHidden=true.
   */
  CLEAR_COMPLETED_TASK_LIST_ID_HINT: () => LocalizedString
  /**
   * Per Google Tasks API: tasks.clear marks completed tasks as hidden (Task.hidden is read-only). tasks.list excludes hidden tasks unless showHidden=true. To permanently remove a task, call tasks.delete (delete-task).
   */
  CLEAR_COMPLETED_SUCCESS_API_NOTE: () => LocalizedString
}

export type Formatters = {}
