// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type {
  BaseTranslation as BaseTranslationType,
  LocalizedString,
} from "typesafe-i18n"

export type BaseTranslation = BaseTranslationType
export type BaseLocale = "en-US"

export type Locales = "en-US" | "zh-Hans"

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
  /**
   * G​o​o​g​l​e​ ​T​a​s​k​s
   */
  PLUGIN_DISPLAY_NAME: string
  /**
   * M​a​n​a​g​e​ ​G​o​o​g​l​e​ ​T​a​s​k​s​ ​-​ ​c​r​e​a​t​e​,​ ​r​e​a​d​,​ ​u​p​d​a​t​e​,​ ​a​n​d​ ​d​e​l​e​t​e​ ​t​a​s​k​s​ ​a​n​d​ ​t​a​s​k​ ​l​i​s​t​s
   */
  PLUGIN_DESCRIPTION: string
  /**
   * G​o​o​g​l​e​ ​T​a​s​k​s​ ​O​A​u​t​h​2
   */
  CREDENTIAL_DISPLAY_NAME: string
  /**
   * O​A​u​t​h​2​ ​c​r​e​d​e​n​t​i​a​l​ ​f​o​r​ ​a​c​c​e​s​s​i​n​g​ ​G​o​o​g​l​e​ ​T​a​s​k​s​ ​A​P​I
   */
  CREDENTIAL_DESCRIPTION: string
  /**
   * C​l​i​e​n​t​ ​I​D
   */
  CLIENT_ID_DISPLAY_NAME: string
  /**
   * E​n​t​e​r​ ​y​o​u​r​ ​G​o​o​g​l​e​ ​O​A​u​t​h​2​ ​C​l​i​e​n​t​ ​I​D
   */
  CLIENT_ID_PLACEHOLDER: string
  /**
   * C​l​i​e​n​t​ ​S​e​c​r​e​t
   */
  CLIENT_SECRET_DISPLAY_NAME: string
  /**
   * E​n​t​e​r​ ​y​o​u​r​ ​G​o​o​g​l​e​ ​O​A​u​t​h​2​ ​C​l​i​e​n​t​ ​S​e​c​r​e​t
   */
  CLIENT_SECRET_PLACEHOLDER: string
  /**
   * C​r​e​d​e​n​t​i​a​l
   */
  CREDENTIAL_ID_DISPLAY_NAME: string
  /**
   * T​a​s​k​ ​L​i​s​t​ ​I​D
   */
  TASK_LIST_ID_DISPLAY_NAME: string
  /**
   * T​h​e​ ​I​D​ ​o​f​ ​t​h​e​ ​t​a​s​k​ ​l​i​s​t​.​ ​U​s​e​ ​'​L​i​s​t​ ​T​a​s​k​ ​L​i​s​t​s​'​ ​t​o​ ​f​i​n​d​ ​a​v​a​i​l​a​b​l​e​ ​I​D​s​.
   */
  TASK_LIST_ID_HINT: string
  /**
   * e​.​g​.​ ​M​T​U​z​N​T​Q​0​.​.​.
   */
  TASK_LIST_ID_PLACEHOLDER: string
  /**
   * T​a​s​k​ ​I​D
   */
  TASK_ID_DISPLAY_NAME: string
  /**
   * T​h​e​ ​I​D​ ​o​f​ ​t​h​e​ ​t​a​s​k​.​ ​U​s​e​ ​'​L​i​s​t​ ​T​a​s​k​s​'​ ​t​o​ ​f​i​n​d​ ​a​v​a​i​l​a​b​l​e​ ​I​D​s​.
   */
  TASK_ID_HINT: string
  /**
   * e​.​g​.​ ​d​G​F​z​a​1​9​p​Z​A​.​.​.
   */
  TASK_ID_PLACEHOLDER: string
  /**
   * T​i​t​l​e
   */
  TITLE_DISPLAY_NAME: string
  /**
   * E​n​t​e​r​ ​t​i​t​l​e
   */
  TITLE_PLACEHOLDER: string
  /**
   * N​o​t​e​s
   */
  NOTES_DISPLAY_NAME: string
  /**
   * E​n​t​e​r​ ​n​o​t​e​s​ ​(​o​p​t​i​o​n​a​l​)
   */
  NOTES_PLACEHOLDER: string
  /**
   * S​t​a​t​u​s
   */
  STATUS_DISPLAY_NAME: string
  /**
   * D​u​e​ ​D​a​t​e
   */
  DUE_DATE_DISPLAY_NAME: string
  /**
   * R​F​C​ ​3​3​3​9​ ​f​o​r​m​a​t​ ​(​e​.​g​.​ ​2​0​2​5​-​1​2​-​3​1​T​0​0​:​0​0​:​0​0​.​0​0​0​Z​)​.​ ​O​n​l​y​ ​t​h​e​ ​d​a​t​e​ ​p​o​r​t​i​o​n​ ​i​s​ ​u​s​e​d​.
   */
  DUE_DATE_HINT: string
  /**
   * 2​0​2​5​-​1​2​-​3​1​T​0​0​:​0​0​:​0​0​.​0​0​0​Z
   */
  DUE_DATE_PLACEHOLDER: string
  /**
   * M​a​x​ ​R​e​s​u​l​t​s
   */
  MAX_RESULTS_DISPLAY_NAME: string
  /**
   * M​a​x​i​m​u​m​ ​n​u​m​b​e​r​ ​o​f​ ​r​e​s​u​l​t​s​ ​t​o​ ​r​e​t​u​r​n​ ​p​e​r​ ​p​a​g​e
   */
  MAX_RESULTS_HINT: string
  /**
   * P​a​g​e​ ​T​o​k​e​n
   */
  PAGE_TOKEN_DISPLAY_NAME: string
  /**
   * T​o​k​e​n​ ​f​o​r​ ​f​e​t​c​h​i​n​g​ ​t​h​e​ ​n​e​x​t​ ​p​a​g​e​ ​o​f​ ​r​e​s​u​l​t​s
   */
  PAGE_TOKEN_HINT: string
  /**
   * E​n​t​e​r​ ​p​a​g​e​ ​t​o​k​e​n
   */
  PAGE_TOKEN_PLACEHOLDER: string
  /**
   * S​h​o​w​ ​C​o​m​p​l​e​t​e​d
   */
  SHOW_COMPLETED_DISPLAY_NAME: string
  /**
   * W​h​e​t​h​e​r​ ​t​o​ ​i​n​c​l​u​d​e​ ​c​o​m​p​l​e​t​e​d​ ​t​a​s​k​s
   */
  SHOW_COMPLETED_HINT: string
  /**
   * S​h​o​w​ ​D​e​l​e​t​e​d
   */
  SHOW_DELETED_DISPLAY_NAME: string
  /**
   * W​h​e​t​h​e​r​ ​t​o​ ​i​n​c​l​u​d​e​ ​d​e​l​e​t​e​d​ ​t​a​s​k​s
   */
  SHOW_DELETED_HINT: string
  /**
   * S​h​o​w​ ​H​i​d​d​e​n
   */
  SHOW_HIDDEN_DISPLAY_NAME: string
  /**
   * W​h​e​t​h​e​r​ ​t​o​ ​i​n​c​l​u​d​e​ ​h​i​d​d​e​n​ ​t​a​s​k​s
   */
  SHOW_HIDDEN_HINT: string
  /**
   * P​a​r​e​n​t​ ​T​a​s​k​ ​I​D
   */
  PARENT_TASK_ID_DISPLAY_NAME: string
  /**
   * I​D​ ​o​f​ ​t​h​e​ ​p​a​r​e​n​t​ ​t​a​s​k​ ​(​f​o​r​ ​c​r​e​a​t​i​n​g​/​m​o​v​i​n​g​ ​s​u​b​-​t​a​s​k​s​)
   */
  PARENT_TASK_ID_HINT: string
  /**
   * E​n​t​e​r​ ​p​a​r​e​n​t​ ​t​a​s​k​ ​I​D​ ​(​o​p​t​i​o​n​a​l​)
   */
  PARENT_TASK_ID_PLACEHOLDER: string
  /**
   * P​r​e​v​i​o​u​s​ ​T​a​s​k​ ​I​D
   */
  PREVIOUS_TASK_ID_DISPLAY_NAME: string
  /**
   * I​D​ ​o​f​ ​t​h​e​ ​p​r​e​v​i​o​u​s​ ​s​i​b​l​i​n​g​ ​t​a​s​k​ ​(​f​o​r​ ​o​r​d​e​r​i​n​g​)
   */
  PREVIOUS_TASK_ID_HINT: string
  /**
   * E​n​t​e​r​ ​p​r​e​v​i​o​u​s​ ​t​a​s​k​ ​I​D​ ​(​o​p​t​i​o​n​a​l​)
   */
  PREVIOUS_TASK_ID_PLACEHOLDER: string
  /**
   * D​e​s​t​i​n​a​t​i​o​n​ ​T​a​s​k​ ​L​i​s​t​ ​I​D
   */
  DESTINATION_TASK_LIST_ID_DISPLAY_NAME: string
  /**
   * I​D​ ​o​f​ ​t​h​e​ ​d​e​s​t​i​n​a​t​i​o​n​ ​t​a​s​k​ ​l​i​s​t​ ​(​f​o​r​ ​c​r​o​s​s​-​l​i​s​t​ ​m​o​v​e​s​)
   */
  DESTINATION_TASK_LIST_ID_HINT: string
  /**
   * E​n​t​e​r​ ​d​e​s​t​i​n​a​t​i​o​n​ ​t​a​s​k​ ​l​i​s​t​ ​I​D​ ​(​o​p​t​i​o​n​a​l​)
   */
  DESTINATION_TASK_LIST_ID_PLACEHOLDER: string
  /**
   * D​u​e​ ​D​a​t​e​ ​M​i​n
   */
  DUE_MIN_DISPLAY_NAME: string
  /**
   * F​i​l​t​e​r​:​ ​m​i​n​i​m​u​m​ ​d​u​e​ ​d​a​t​e​ ​(​R​F​C​ ​3​3​3​9​)
   */
  DUE_MIN_HINT: string
  /**
   * D​u​e​ ​D​a​t​e​ ​M​a​x
   */
  DUE_MAX_DISPLAY_NAME: string
  /**
   * F​i​l​t​e​r​:​ ​m​a​x​i​m​u​m​ ​d​u​e​ ​d​a​t​e​ ​(​R​F​C​ ​3​3​3​9​)
   */
  DUE_MAX_HINT: string
  /**
   * U​p​d​a​t​e​d​ ​A​f​t​e​r
   */
  UPDATED_MIN_DISPLAY_NAME: string
  /**
   * F​i​l​t​e​r​:​ ​m​i​n​i​m​u​m​ ​l​a​s​t​ ​m​o​d​i​f​i​c​a​t​i​o​n​ ​t​i​m​e​ ​(​R​F​C​ ​3​3​3​9​)
   */
  UPDATED_MIN_HINT: string
  /**
   * L​i​s​t​ ​T​a​s​k​ ​L​i​s​t​s
   */
  LIST_TASK_LISTS_DISPLAY_NAME: string
  /**
   * R​e​t​u​r​n​s​ ​a​l​l​ ​t​a​s​k​ ​l​i​s​t​s​ ​f​o​r​ ​t​h​e​ ​a​u​t​h​e​n​t​i​c​a​t​e​d​ ​u​s​e​r
   */
  LIST_TASK_LISTS_DESCRIPTION: string
  /**
   * C​r​e​a​t​e​ ​T​a​s​k​ ​L​i​s​t
   */
  CREATE_TASK_LIST_DISPLAY_NAME: string
  /**
   * C​r​e​a​t​e​s​ ​a​ ​n​e​w​ ​t​a​s​k​ ​l​i​s​t
   */
  CREATE_TASK_LIST_DESCRIPTION: string
  /**
   * G​e​t​ ​T​a​s​k​ ​L​i​s​t
   */
  GET_TASK_LIST_DISPLAY_NAME: string
  /**
   * R​e​t​u​r​n​s​ ​t​h​e​ ​s​p​e​c​i​f​i​e​d​ ​t​a​s​k​ ​l​i​s​t
   */
  GET_TASK_LIST_DESCRIPTION: string
  /**
   * R​e​p​l​a​c​e​ ​T​a​s​k​ ​L​i​s​t
   */
  REPLACE_TASK_LIST_DISPLAY_NAME: string
  /**
   * F​u​l​l​y​ ​r​e​p​l​a​c​e​s​ ​t​h​e​ ​s​p​e​c​i​f​i​e​d​ ​t​a​s​k​ ​l​i​s​t​ ​u​s​i​n​g​ ​t​a​s​k​l​i​s​t​s​.​u​p​d​a​t​e
   */
  REPLACE_TASK_LIST_DESCRIPTION: string
  /**
   * U​p​d​a​t​e​ ​T​a​s​k​ ​L​i​s​t
   */
  UPDATE_TASK_LIST_DISPLAY_NAME: string
  /**
   * U​p​d​a​t​e​s​ ​t​h​e​ ​t​i​t​l​e​ ​o​f​ ​t​h​e​ ​s​p​e​c​i​f​i​e​d​ ​t​a​s​k​ ​l​i​s​t
   */
  UPDATE_TASK_LIST_DESCRIPTION: string
  /**
   * D​e​l​e​t​e​ ​T​a​s​k​ ​L​i​s​t
   */
  DELETE_TASK_LIST_DISPLAY_NAME: string
  /**
   * D​e​l​e​t​e​s​ ​t​h​e​ ​s​p​e​c​i​f​i​e​d​ ​t​a​s​k​ ​l​i​s​t
   */
  DELETE_TASK_LIST_DESCRIPTION: string
  /**
   * L​i​s​t​ ​T​a​s​k​s
   */
  LIST_TASKS_DISPLAY_NAME: string
  /**
   * R​e​t​u​r​n​s​ ​a​l​l​ ​t​a​s​k​s​ ​i​n​ ​t​h​e​ ​s​p​e​c​i​f​i​e​d​ ​t​a​s​k​ ​l​i​s​t
   */
  LIST_TASKS_DESCRIPTION: string
  /**
   * G​e​t​ ​T​a​s​k
   */
  GET_TASK_DISPLAY_NAME: string
  /**
   * R​e​t​u​r​n​s​ ​t​h​e​ ​s​p​e​c​i​f​i​e​d​ ​t​a​s​k
   */
  GET_TASK_DESCRIPTION: string
  /**
   * C​r​e​a​t​e​ ​T​a​s​k
   */
  CREATE_TASK_DISPLAY_NAME: string
  /**
   * C​r​e​a​t​e​s​ ​a​ ​n​e​w​ ​t​a​s​k​ ​i​n​ ​t​h​e​ ​s​p​e​c​i​f​i​e​d​ ​t​a​s​k​ ​l​i​s​t
   */
  CREATE_TASK_DESCRIPTION: string
  /**
   * R​e​p​l​a​c​e​ ​T​a​s​k
   */
  REPLACE_TASK_DISPLAY_NAME: string
  /**
   * F​u​l​l​y​ ​r​e​p​l​a​c​e​s​ ​t​h​e​ ​s​p​e​c​i​f​i​e​d​ ​t​a​s​k​ ​u​s​i​n​g​ ​t​a​s​k​s​.​u​p​d​a​t​e
   */
  REPLACE_TASK_DESCRIPTION: string
  /**
   * U​p​d​a​t​e​ ​T​a​s​k
   */
  UPDATE_TASK_DISPLAY_NAME: string
  /**
   * U​p​d​a​t​e​s​ ​t​h​e​ ​s​p​e​c​i​f​i​e​d​ ​t​a​s​k​ ​(​t​i​t​l​e​,​ ​n​o​t​e​s​,​ ​s​t​a​t​u​s​,​ ​d​u​e​ ​d​a​t​e​)
   */
  UPDATE_TASK_DESCRIPTION: string
  /**
   * D​e​l​e​t​e​ ​T​a​s​k
   */
  DELETE_TASK_DISPLAY_NAME: string
  /**
   * D​e​l​e​t​e​s​ ​t​h​e​ ​s​p​e​c​i​f​i​e​d​ ​t​a​s​k​ ​f​r​o​m​ ​t​h​e​ ​t​a​s​k​ ​l​i​s​t
   */
  DELETE_TASK_DESCRIPTION: string
  /**
   * M​o​v​e​ ​T​a​s​k
   */
  MOVE_TASK_DISPLAY_NAME: string
  /**
   * M​o​v​e​s​ ​a​ ​t​a​s​k​ ​t​o​ ​a​n​o​t​h​e​r​ ​p​o​s​i​t​i​o​n​ ​o​r​ ​t​a​s​k​ ​l​i​s​t
   */
  MOVE_TASK_DESCRIPTION: string
  /**
   * C​l​e​a​r​ ​C​o​m​p​l​e​t​e​d​ ​T​a​s​k​s
   */
  CLEAR_COMPLETED_DISPLAY_NAME: string
  /**
   * C​l​e​a​r​s​ ​a​l​l​ ​c​o​m​p​l​e​t​e​d​ ​t​a​s​k​s​ ​f​r​o​m​ ​t​h​e​ ​s​p​e​c​i​f​i​e​d​ ​t​a​s​k​ ​l​i​s​t
   */
  CLEAR_COMPLETED_DESCRIPTION: string
}

export type TranslationFunctions = {
  /**
   * Google Tasks
   */
  PLUGIN_DISPLAY_NAME: () => LocalizedString
  /**
   * Manage Google Tasks - create, read, update, and delete tasks and task lists
   */
  PLUGIN_DESCRIPTION: () => LocalizedString
  /**
   * Google Tasks OAuth2
   */
  CREDENTIAL_DISPLAY_NAME: () => LocalizedString
  /**
   * OAuth2 credential for accessing Google Tasks API
   */
  CREDENTIAL_DESCRIPTION: () => LocalizedString
  /**
   * Client ID
   */
  CLIENT_ID_DISPLAY_NAME: () => LocalizedString
  /**
   * Enter your Google OAuth2 Client ID
   */
  CLIENT_ID_PLACEHOLDER: () => LocalizedString
  /**
   * Client Secret
   */
  CLIENT_SECRET_DISPLAY_NAME: () => LocalizedString
  /**
   * Enter your Google OAuth2 Client Secret
   */
  CLIENT_SECRET_PLACEHOLDER: () => LocalizedString
  /**
   * Credential
   */
  CREDENTIAL_ID_DISPLAY_NAME: () => LocalizedString
  /**
   * Task List ID
   */
  TASK_LIST_ID_DISPLAY_NAME: () => LocalizedString
  /**
   * The ID of the task list. Use 'List Task Lists' to find available IDs.
   */
  TASK_LIST_ID_HINT: () => LocalizedString
  /**
   * e.g. MTUzNTQ0...
   */
  TASK_LIST_ID_PLACEHOLDER: () => LocalizedString
  /**
   * Task ID
   */
  TASK_ID_DISPLAY_NAME: () => LocalizedString
  /**
   * The ID of the task. Use 'List Tasks' to find available IDs.
   */
  TASK_ID_HINT: () => LocalizedString
  /**
   * e.g. dGFza19pZA...
   */
  TASK_ID_PLACEHOLDER: () => LocalizedString
  /**
   * Title
   */
  TITLE_DISPLAY_NAME: () => LocalizedString
  /**
   * Enter title
   */
  TITLE_PLACEHOLDER: () => LocalizedString
  /**
   * Notes
   */
  NOTES_DISPLAY_NAME: () => LocalizedString
  /**
   * Enter notes (optional)
   */
  NOTES_PLACEHOLDER: () => LocalizedString
  /**
   * Status
   */
  STATUS_DISPLAY_NAME: () => LocalizedString
  /**
   * Due Date
   */
  DUE_DATE_DISPLAY_NAME: () => LocalizedString
  /**
   * RFC 3339 format (e.g. 2025-12-31T00:00:00.000Z). Only the date portion is used.
   */
  DUE_DATE_HINT: () => LocalizedString
  /**
   * 2025-12-31T00:00:00.000Z
   */
  DUE_DATE_PLACEHOLDER: () => LocalizedString
  /**
   * Max Results
   */
  MAX_RESULTS_DISPLAY_NAME: () => LocalizedString
  /**
   * Maximum number of results to return per page
   */
  MAX_RESULTS_HINT: () => LocalizedString
  /**
   * Page Token
   */
  PAGE_TOKEN_DISPLAY_NAME: () => LocalizedString
  /**
   * Token for fetching the next page of results
   */
  PAGE_TOKEN_HINT: () => LocalizedString
  /**
   * Enter page token
   */
  PAGE_TOKEN_PLACEHOLDER: () => LocalizedString
  /**
   * Show Completed
   */
  SHOW_COMPLETED_DISPLAY_NAME: () => LocalizedString
  /**
   * Whether to include completed tasks
   */
  SHOW_COMPLETED_HINT: () => LocalizedString
  /**
   * Show Deleted
   */
  SHOW_DELETED_DISPLAY_NAME: () => LocalizedString
  /**
   * Whether to include deleted tasks
   */
  SHOW_DELETED_HINT: () => LocalizedString
  /**
   * Show Hidden
   */
  SHOW_HIDDEN_DISPLAY_NAME: () => LocalizedString
  /**
   * Whether to include hidden tasks
   */
  SHOW_HIDDEN_HINT: () => LocalizedString
  /**
   * Parent Task ID
   */
  PARENT_TASK_ID_DISPLAY_NAME: () => LocalizedString
  /**
   * ID of the parent task (for creating/moving sub-tasks)
   */
  PARENT_TASK_ID_HINT: () => LocalizedString
  /**
   * Enter parent task ID (optional)
   */
  PARENT_TASK_ID_PLACEHOLDER: () => LocalizedString
  /**
   * Previous Task ID
   */
  PREVIOUS_TASK_ID_DISPLAY_NAME: () => LocalizedString
  /**
   * ID of the previous sibling task (for ordering)
   */
  PREVIOUS_TASK_ID_HINT: () => LocalizedString
  /**
   * Enter previous task ID (optional)
   */
  PREVIOUS_TASK_ID_PLACEHOLDER: () => LocalizedString
  /**
   * Destination Task List ID
   */
  DESTINATION_TASK_LIST_ID_DISPLAY_NAME: () => LocalizedString
  /**
   * ID of the destination task list (for cross-list moves)
   */
  DESTINATION_TASK_LIST_ID_HINT: () => LocalizedString
  /**
   * Enter destination task list ID (optional)
   */
  DESTINATION_TASK_LIST_ID_PLACEHOLDER: () => LocalizedString
  /**
   * Due Date Min
   */
  DUE_MIN_DISPLAY_NAME: () => LocalizedString
  /**
   * Filter: minimum due date (RFC 3339)
   */
  DUE_MIN_HINT: () => LocalizedString
  /**
   * Due Date Max
   */
  DUE_MAX_DISPLAY_NAME: () => LocalizedString
  /**
   * Filter: maximum due date (RFC 3339)
   */
  DUE_MAX_HINT: () => LocalizedString
  /**
   * Updated After
   */
  UPDATED_MIN_DISPLAY_NAME: () => LocalizedString
  /**
   * Filter: minimum last modification time (RFC 3339)
   */
  UPDATED_MIN_HINT: () => LocalizedString
  /**
   * List Task Lists
   */
  LIST_TASK_LISTS_DISPLAY_NAME: () => LocalizedString
  /**
   * Returns all task lists for the authenticated user
   */
  LIST_TASK_LISTS_DESCRIPTION: () => LocalizedString
  /**
   * Create Task List
   */
  CREATE_TASK_LIST_DISPLAY_NAME: () => LocalizedString
  /**
   * Creates a new task list
   */
  CREATE_TASK_LIST_DESCRIPTION: () => LocalizedString
  /**
   * Get Task List
   */
  GET_TASK_LIST_DISPLAY_NAME: () => LocalizedString
  /**
   * Returns the specified task list
   */
  GET_TASK_LIST_DESCRIPTION: () => LocalizedString
  /**
   * Replace Task List
   */
  REPLACE_TASK_LIST_DISPLAY_NAME: () => LocalizedString
  /**
   * Fully replaces the specified task list using tasklists.update
   */
  REPLACE_TASK_LIST_DESCRIPTION: () => LocalizedString
  /**
   * Update Task List
   */
  UPDATE_TASK_LIST_DISPLAY_NAME: () => LocalizedString
  /**
   * Updates the title of the specified task list
   */
  UPDATE_TASK_LIST_DESCRIPTION: () => LocalizedString
  /**
   * Delete Task List
   */
  DELETE_TASK_LIST_DISPLAY_NAME: () => LocalizedString
  /**
   * Deletes the specified task list
   */
  DELETE_TASK_LIST_DESCRIPTION: () => LocalizedString
  /**
   * List Tasks
   */
  LIST_TASKS_DISPLAY_NAME: () => LocalizedString
  /**
   * Returns all tasks in the specified task list
   */
  LIST_TASKS_DESCRIPTION: () => LocalizedString
  /**
   * Get Task
   */
  GET_TASK_DISPLAY_NAME: () => LocalizedString
  /**
   * Returns the specified task
   */
  GET_TASK_DESCRIPTION: () => LocalizedString
  /**
   * Create Task
   */
  CREATE_TASK_DISPLAY_NAME: () => LocalizedString
  /**
   * Creates a new task in the specified task list
   */
  CREATE_TASK_DESCRIPTION: () => LocalizedString
  /**
   * Replace Task
   */
  REPLACE_TASK_DISPLAY_NAME: () => LocalizedString
  /**
   * Fully replaces the specified task using tasks.update
   */
  REPLACE_TASK_DESCRIPTION: () => LocalizedString
  /**
   * Update Task
   */
  UPDATE_TASK_DISPLAY_NAME: () => LocalizedString
  /**
   * Updates the specified task (title, notes, status, due date)
   */
  UPDATE_TASK_DESCRIPTION: () => LocalizedString
  /**
   * Delete Task
   */
  DELETE_TASK_DISPLAY_NAME: () => LocalizedString
  /**
   * Deletes the specified task from the task list
   */
  DELETE_TASK_DESCRIPTION: () => LocalizedString
  /**
   * Move Task
   */
  MOVE_TASK_DISPLAY_NAME: () => LocalizedString
  /**
   * Moves a task to another position or task list
   */
  MOVE_TASK_DESCRIPTION: () => LocalizedString
  /**
   * Clear Completed Tasks
   */
  CLEAR_COMPLETED_DISPLAY_NAME: () => LocalizedString
  /**
   * Clears all completed tasks from the specified task list
   */
  CLEAR_COMPLETED_DESCRIPTION: () => LocalizedString
}

export type Formatters = {}
