// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type {
  BaseTranslation as BaseTranslationType,
  LocalizedString,
} from "typesafe-i18n"

export type BaseTranslation = BaseTranslationType
export type BaseLocale = "en-US"

export type Locales = "en-US" | "zh-Hans"

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
  /**
   * T​e​s​t​i​n​g​ ​P​l​u​g​i​n
   */
  PLUGIN_DISPLAY_NAME: string
  /**
   * A​ ​p​l​u​g​i​n​ ​f​o​r​ ​t​e​s​t​i​n​g​ ​t​h​e​ ​p​l​u​g​i​n
   */
  PLUGIN_DESCRIPTION: string
  /**
   * D​e​m​o​ ​T​o​o​l
   */
  DEMO_TOOL_DISPLAY_NAME: string
  /**
   * A​ ​t​o​o​l​ ​f​o​r​ ​t​e​s​t​i​n​g​ ​t​h​e​ ​p​l​u​g​i​n
   */
  DEMO_TOOL_DESCRIPTION: string
  /**
   * L​o​c​a​t​i​o​n
   */
  LOCATION_DISPLAY_NAME: string
  /**
   * T​h​e​ ​l​o​c​a​t​i​o​n​ ​t​o​ ​t​e​s​t
   */
  LOCATION_HINT: string
  /**
   * E​n​t​e​r​ ​t​h​e​ ​l​o​c​a​t​i​o​n​ ​t​o​ ​t​e​s​t
   */
  LOCATION_PLACEHOLDER: string
  /**
   * G​o​o​g​l​e​ ​D​o​c​s​ ​O​A​u​t​h​2
   */
  GOOGLE_DOCS_CREDENTIAL_DISPLAY_NAME: string
  /**
   * O​A​u​t​h​2​ ​c​r​e​d​e​n​t​i​a​l​s​ ​f​o​r​ ​a​c​c​e​s​s​i​n​g​ ​G​o​o​g​l​e​ ​D​o​c​s​ ​A​P​I
   */
  GOOGLE_DOCS_CREDENTIAL_DESCRIPTION: string
  /**
   * C​l​i​e​n​t​ ​I​D
   */
  CLIENT_ID_DISPLAY_NAME: string
  /**
   * G​o​o​g​l​e​ ​O​A​u​t​h​2​ ​C​l​i​e​n​t​ ​I​D
   */
  CLIENT_ID_PLACEHOLDER: string
  /**
   * C​r​e​a​t​e​ ​O​A​u​t​h​2​ ​c​r​e​d​e​n​t​i​a​l​s​ ​i​n​ ​G​o​o​g​l​e​ ​C​l​o​u​d​ ​C​o​n​s​o​l​e
   */
  CLIENT_ID_HINT: string
  /**
   * C​l​i​e​n​t​ ​S​e​c​r​e​t
   */
  CLIENT_SECRET_DISPLAY_NAME: string
  /**
   * G​o​o​g​l​e​ ​O​A​u​t​h​2​ ​C​l​i​e​n​t​ ​S​e​c​r​e​t
   */
  CLIENT_SECRET_HINT: string
  /**
   * G​o​o​g​l​e​ ​C​r​e​d​e​n​t​i​a​l
   */
  GOOGLE_DOCS_CREDENTIAL_PARAM_DISPLAY_NAME: string
  /**
   * C​r​e​a​t​e​ ​D​o​c​u​m​e​n​t
   */
  CREATE_DOCUMENT_TOOL_DISPLAY_NAME: string
  /**
   * C​r​e​a​t​e​ ​a​ ​n​e​w​ ​G​o​o​g​l​e​ ​D​o​c​s​ ​d​o​c​u​m​e​n​t
   */
  CREATE_DOCUMENT_TOOL_DESCRIPTION: string
  /**
   * G​e​t​ ​D​o​c​u​m​e​n​t
   */
  GET_DOCUMENT_TOOL_DISPLAY_NAME: string
  /**
   * G​e​t​ ​G​o​o​g​l​e​ ​D​o​c​s​ ​d​o​c​u​m​e​n​t​ ​c​o​n​t​e​n​t​ ​b​y​ ​I​D
   */
  GET_DOCUMENT_TOOL_DESCRIPTION: string
  /**
   * B​a​t​c​h​ ​U​p​d​a​t​e​ ​D​o​c​u​m​e​n​t
   */
  BATCH_UPDATE_DOCUMENT_TOOL_DISPLAY_NAME: string
  /**
   * A​p​p​l​y​ ​b​a​t​c​h​U​p​d​a​t​e​ ​r​e​q​u​e​s​t​s​ ​t​o​ ​a​ ​G​o​o​g​l​e​ ​D​o​c​s​ ​d​o​c​u​m​e​n​t
   */
  BATCH_UPDATE_DOCUMENT_TOOL_DESCRIPTION: string
  /**
   * D​o​c​u​m​e​n​t​ ​T​i​t​l​e
   */
  DOCUMENT_TITLE_DISPLAY_NAME: string
  /**
   * E​n​t​e​r​ ​d​o​c​u​m​e​n​t​ ​t​i​t​l​e
   */
  DOCUMENT_TITLE_PLACEHOLDER: string
  /**
   * T​i​t​l​e​ ​f​o​r​ ​t​h​e​ ​n​e​w​ ​G​o​o​g​l​e​ ​D​o​c​s​ ​d​o​c​u​m​e​n​t
   */
  DOCUMENT_TITLE_HINT: string
  /**
   * D​o​c​u​m​e​n​t​ ​I​D
   */
  DOCUMENT_ID_DISPLAY_NAME: string
  /**
   * E​n​t​e​r​ ​G​o​o​g​l​e​ ​D​o​c​s​ ​d​o​c​u​m​e​n​t​ ​I​D
   */
  DOCUMENT_ID_PLACEHOLDER: string
  /**
   * D​o​c​u​m​e​n​t​ ​I​D​ ​f​r​o​m​ ​d​o​c​s​.​g​o​o​g​l​e​.​c​o​m​ ​U​R​L
   */
  DOCUMENT_ID_HINT: string
  /**
   * I​n​c​l​u​d​e​ ​T​a​b​s​ ​C​o​n​t​e​n​t
   */
  INCLUDE_TABS_CONTENT_DISPLAY_NAME: string
  /**
   * W​h​e​n​ ​e​n​a​b​l​e​d​,​ ​r​e​t​u​r​n​ ​c​o​n​t​e​n​t​ ​i​n​ ​t​a​b​s​ ​f​i​e​l​d​ ​f​o​r​ ​m​u​l​t​i​-​t​a​b​ ​d​o​c​s
   */
  INCLUDE_TABS_CONTENT_HINT: string
  /**
   * S​u​g​g​e​s​t​i​o​n​s​ ​V​i​e​w​ ​M​o​d​e
   */
  SUGGESTIONS_VIEW_MODE_DISPLAY_NAME: string
  /**
   * O​p​t​i​o​n​a​l​;​ ​m​a​p​s​ ​t​o​ ​d​o​c​u​m​e​n​t​s​.​g​e​t​ ​s​u​g​g​e​s​t​i​o​n​s​V​i​e​w​M​o​d​e​ ​q​u​e​r​y​ ​p​a​r​a​m​e​t​e​r
   */
  SUGGESTIONS_VIEW_MODE_HINT: string
  /**
   * R​e​q​u​e​s​t​s​ ​J​S​O​N
   */
  REQUESTS_JSON_DISPLAY_NAME: string
  /**
   * J​S​O​N​ ​a​r​r​a​y​ ​o​f​ ​G​o​o​g​l​e​ ​D​o​c​s​ ​R​e​q​u​e​s​t​ ​o​b​j​e​c​t​s​ ​u​s​e​d​ ​i​n​ ​b​a​t​c​h​U​p​d​a​t​e
   */
  REQUESTS_JSON_HINT: string
  /**
   * J​S​O​N​ ​a​r​r​a​y​ ​f​o​r​ ​b​a​t​c​h​U​p​d​a​t​e​ ​r​e​q​u​e​s​t​s
   */
  REQUESTS_JSON_PLACEHOLDER: string
  /**
   * O​p​e​r​a​t​i​o​n
   */
  BATCH_OPERATION_DISPLAY_NAME: string
  /**
   * C​h​o​o​s​e​ ​s​t​r​u​c​t​u​r​e​d​ ​m​o​d​e​ ​o​r​ ​r​a​w​ ​J​S​O​N​ ​m​o​d​e
   */
  BATCH_OPERATION_HINT: string
  /**
   * I​n​s​e​r​t​ ​T​e​x​t
   */
  INSERT_TEXT_DISPLAY_NAME: string
  /**
   * T​e​x​t​ ​t​o​ ​i​n​s​e​r​t​ ​w​h​e​n​ ​o​p​e​r​a​t​i​o​n​ ​i​s​ ​i​n​s​e​r​t​_​t​e​x​t
   */
  INSERT_TEXT_HINT: string
  /**
   * I​n​s​e​r​t​ ​I​n​d​e​x
   */
  INSERT_INDEX_DISPLAY_NAME: string
  /**
   * C​h​a​r​a​c​t​e​r​ ​i​n​d​e​x​ ​w​h​e​r​e​ ​t​e​x​t​ ​i​n​s​e​r​t​i​o​n​ ​s​t​a​r​t​s
   */
  INSERT_INDEX_HINT: string
  /**
   * M​a​t​c​h​ ​T​e​x​t
   */
  REPLACE_CONTAINS_TEXT_DISPLAY_NAME: string
  /**
   * T​e​x​t​ ​t​o​ ​s​e​a​r​c​h​ ​w​h​e​n​ ​o​p​e​r​a​t​i​o​n​ ​i​s​ ​r​e​p​l​a​c​e​_​a​l​l​_​t​e​x​t
   */
  REPLACE_CONTAINS_TEXT_HINT: string
  /**
   * R​e​p​l​a​c​e​ ​T​e​x​t
   */
  REPLACE_TEXT_DISPLAY_NAME: string
  /**
   * R​e​p​l​a​c​e​m​e​n​t​ ​t​e​x​t​ ​f​o​r​ ​r​e​p​l​a​c​e​_​a​l​l​_​t​e​x​t
   */
  REPLACE_TEXT_HINT: string
  /**
   * S​t​y​l​e​ ​S​t​a​r​t​ ​I​n​d​e​x
   */
  STYLE_START_INDEX_DISPLAY_NAME: string
  /**
   * S​t​a​r​t​ ​i​n​d​e​x​ ​f​o​r​ ​s​t​y​l​e​ ​u​p​d​a​t​e​ ​r​a​n​g​e
   */
  STYLE_START_INDEX_HINT: string
  /**
   * S​t​y​l​e​ ​E​n​d​ ​I​n​d​e​x
   */
  STYLE_END_INDEX_DISPLAY_NAME: string
  /**
   * E​n​d​ ​i​n​d​e​x​ ​f​o​r​ ​s​t​y​l​e​ ​u​p​d​a​t​e​ ​r​a​n​g​e
   */
  STYLE_END_INDEX_HINT: string
  /**
   * S​e​t​ ​B​o​l​d
   */
  STYLE_BOLD_DISPLAY_NAME: string
  /**
   * W​h​e​t​h​e​r​ ​t​o​ ​a​p​p​l​y​ ​b​o​l​d​ ​s​t​y​l​e​ ​i​n​ ​u​p​d​a​t​e​_​t​e​x​t​_​s​t​y​l​e
   */
  STYLE_BOLD_HINT: string
  /**
   * W​r​i​t​e​ ​C​o​n​t​r​o​l​ ​J​S​O​N
   */
  WRITE_CONTROL_JSON_DISPLAY_NAME: string
  /**
   * O​p​t​i​o​n​a​l​ ​J​S​O​N​ ​o​b​j​e​c​t​ ​w​i​t​h​ ​r​e​v​i​s​i​o​n​ ​c​o​n​t​r​o​l​ ​s​e​t​t​i​n​g​s
   */
  WRITE_CONTROL_JSON_HINT: string
  /**
   * J​S​O​N​ ​o​b​j​e​c​t​ ​f​o​r​ ​w​r​i​t​e​ ​c​o​n​t​r​o​l
   */
  WRITE_CONTROL_JSON_PLACEHOLDER: string
}

export type TranslationFunctions = {
  /**
   * Testing Plugin
   */
  PLUGIN_DISPLAY_NAME: () => LocalizedString
  /**
   * A plugin for testing the plugin
   */
  PLUGIN_DESCRIPTION: () => LocalizedString
  /**
   * Demo Tool
   */
  DEMO_TOOL_DISPLAY_NAME: () => LocalizedString
  /**
   * A tool for testing the plugin
   */
  DEMO_TOOL_DESCRIPTION: () => LocalizedString
  /**
   * Location
   */
  LOCATION_DISPLAY_NAME: () => LocalizedString
  /**
   * The location to test
   */
  LOCATION_HINT: () => LocalizedString
  /**
   * Enter the location to test
   */
  LOCATION_PLACEHOLDER: () => LocalizedString
  /**
   * Google Docs OAuth2
   */
  GOOGLE_DOCS_CREDENTIAL_DISPLAY_NAME: () => LocalizedString
  /**
   * OAuth2 credentials for accessing Google Docs API
   */
  GOOGLE_DOCS_CREDENTIAL_DESCRIPTION: () => LocalizedString
  /**
   * Client ID
   */
  CLIENT_ID_DISPLAY_NAME: () => LocalizedString
  /**
   * Google OAuth2 Client ID
   */
  CLIENT_ID_PLACEHOLDER: () => LocalizedString
  /**
   * Create OAuth2 credentials in Google Cloud Console
   */
  CLIENT_ID_HINT: () => LocalizedString
  /**
   * Client Secret
   */
  CLIENT_SECRET_DISPLAY_NAME: () => LocalizedString
  /**
   * Google OAuth2 Client Secret
   */
  CLIENT_SECRET_HINT: () => LocalizedString
  /**
   * Google Credential
   */
  GOOGLE_DOCS_CREDENTIAL_PARAM_DISPLAY_NAME: () => LocalizedString
  /**
   * Create Document
   */
  CREATE_DOCUMENT_TOOL_DISPLAY_NAME: () => LocalizedString
  /**
   * Create a new Google Docs document
   */
  CREATE_DOCUMENT_TOOL_DESCRIPTION: () => LocalizedString
  /**
   * Get Document
   */
  GET_DOCUMENT_TOOL_DISPLAY_NAME: () => LocalizedString
  /**
   * Get Google Docs document content by ID
   */
  GET_DOCUMENT_TOOL_DESCRIPTION: () => LocalizedString
  /**
   * Batch Update Document
   */
  BATCH_UPDATE_DOCUMENT_TOOL_DISPLAY_NAME: () => LocalizedString
  /**
   * Apply batchUpdate requests to a Google Docs document
   */
  BATCH_UPDATE_DOCUMENT_TOOL_DESCRIPTION: () => LocalizedString
  /**
   * Document Title
   */
  DOCUMENT_TITLE_DISPLAY_NAME: () => LocalizedString
  /**
   * Enter document title
   */
  DOCUMENT_TITLE_PLACEHOLDER: () => LocalizedString
  /**
   * Title for the new Google Docs document
   */
  DOCUMENT_TITLE_HINT: () => LocalizedString
  /**
   * Document ID
   */
  DOCUMENT_ID_DISPLAY_NAME: () => LocalizedString
  /**
   * Enter Google Docs document ID
   */
  DOCUMENT_ID_PLACEHOLDER: () => LocalizedString
  /**
   * Document ID from docs.google.com URL
   */
  DOCUMENT_ID_HINT: () => LocalizedString
  /**
   * Include Tabs Content
   */
  INCLUDE_TABS_CONTENT_DISPLAY_NAME: () => LocalizedString
  /**
   * When enabled, return content in tabs field for multi-tab docs
   */
  INCLUDE_TABS_CONTENT_HINT: () => LocalizedString
  /**
   * Suggestions View Mode
   */
  SUGGESTIONS_VIEW_MODE_DISPLAY_NAME: () => LocalizedString
  /**
   * Optional; maps to documents.get suggestionsViewMode query parameter
   */
  SUGGESTIONS_VIEW_MODE_HINT: () => LocalizedString
  /**
   * Requests JSON
   */
  REQUESTS_JSON_DISPLAY_NAME: () => LocalizedString
  /**
   * JSON array of Google Docs Request objects used in batchUpdate
   */
  REQUESTS_JSON_HINT: () => LocalizedString
  /**
   * JSON array for batchUpdate requests
   */
  REQUESTS_JSON_PLACEHOLDER: () => LocalizedString
  /**
   * Operation
   */
  BATCH_OPERATION_DISPLAY_NAME: () => LocalizedString
  /**
   * Choose structured mode or raw JSON mode
   */
  BATCH_OPERATION_HINT: () => LocalizedString
  /**
   * Insert Text
   */
  INSERT_TEXT_DISPLAY_NAME: () => LocalizedString
  /**
   * Text to insert when operation is insert_text
   */
  INSERT_TEXT_HINT: () => LocalizedString
  /**
   * Insert Index
   */
  INSERT_INDEX_DISPLAY_NAME: () => LocalizedString
  /**
   * Character index where text insertion starts
   */
  INSERT_INDEX_HINT: () => LocalizedString
  /**
   * Match Text
   */
  REPLACE_CONTAINS_TEXT_DISPLAY_NAME: () => LocalizedString
  /**
   * Text to search when operation is replace_all_text
   */
  REPLACE_CONTAINS_TEXT_HINT: () => LocalizedString
  /**
   * Replace Text
   */
  REPLACE_TEXT_DISPLAY_NAME: () => LocalizedString
  /**
   * Replacement text for replace_all_text
   */
  REPLACE_TEXT_HINT: () => LocalizedString
  /**
   * Style Start Index
   */
  STYLE_START_INDEX_DISPLAY_NAME: () => LocalizedString
  /**
   * Start index for style update range
   */
  STYLE_START_INDEX_HINT: () => LocalizedString
  /**
   * Style End Index
   */
  STYLE_END_INDEX_DISPLAY_NAME: () => LocalizedString
  /**
   * End index for style update range
   */
  STYLE_END_INDEX_HINT: () => LocalizedString
  /**
   * Set Bold
   */
  STYLE_BOLD_DISPLAY_NAME: () => LocalizedString
  /**
   * Whether to apply bold style in update_text_style
   */
  STYLE_BOLD_HINT: () => LocalizedString
  /**
   * Write Control JSON
   */
  WRITE_CONTROL_JSON_DISPLAY_NAME: () => LocalizedString
  /**
   * Optional JSON object with revision control settings
   */
  WRITE_CONTROL_JSON_HINT: () => LocalizedString
  /**
   * JSON object for write control
   */
  WRITE_CONTROL_JSON_PLACEHOLDER: () => LocalizedString
}

export type Formatters = {}
