// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type {
  BaseTranslation as BaseTranslationType,
  LocalizedString,
} from "typesafe-i18n"

export type BaseTranslation = BaseTranslationType
export type BaseLocale = "en-US"

export type Locales = "en-US" | "zh-Hans"

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
  /**
   * H​u​b​S​p​o​t
   */
  PLUGIN_DISPLAY_NAME: string
  /**
   * H​u​b​S​p​o​t​ ​s​t​a​r​t​e​r​ ​s​c​a​f​f​o​l​d​ ​p​l​u​g​i​n​ ​f​o​r​ ​f​u​t​u​r​e​ ​C​R​M​ ​t​o​o​l​s​ ​a​n​d​ ​c​r​e​d​e​n​t​i​a​l​s​.
   */
  PLUGIN_DESCRIPTION: string
  /**
   * H​u​b​S​p​o​t​ ​P​l​u​g​i​n​ ​S​t​a​t​u​s
   */
  HUBSPOT_PLUGIN_STATUS_DISPLAY_NAME: string
  /**
   * R​e​t​u​r​n​ ​s​c​a​f​f​o​l​d​ ​m​e​t​a​d​a​t​a​ ​f​o​r​ ​t​h​e​ ​H​u​b​S​p​o​t​ ​s​t​a​r​t​e​r​ ​p​l​u​g​i​n​.​ ​T​h​i​s​ ​d​o​e​s​ ​n​o​t​ ​c​a​l​l​ ​t​h​e​ ​H​u​b​S​p​o​t​ ​A​P​I​.
   */
  HUBSPOT_PLUGIN_STATUS_DESCRIPTION: string
}

export type TranslationFunctions = {
  /**
   * HubSpot
   */
  PLUGIN_DISPLAY_NAME: () => LocalizedString
  /**
   * HubSpot starter scaffold plugin for future CRM tools and credentials.
   */
  PLUGIN_DESCRIPTION: () => LocalizedString
  /**
   * HubSpot Plugin Status
   */
  HUBSPOT_PLUGIN_STATUS_DISPLAY_NAME: () => LocalizedString
  /**
   * Return scaffold metadata for the HubSpot starter plugin. This does not call the HubSpot API.
   */
  HUBSPOT_PLUGIN_STATUS_DESCRIPTION: () => LocalizedString
}

export type Formatters = {}
