// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type {
  BaseTranslation as BaseTranslationType,
  LocalizedString,
} from "typesafe-i18n"

export type BaseTranslation = BaseTranslationType
export type BaseLocale = "en-US"

export type Locales = "en-US" | "zh-Hans"

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
  /**
   * F​e​i​s​h​u​ ​P​l​u​g​i​n
   */
  PLUGIN_DISPLAY_NAME: string
  /**
   * C​o​n​n​e​c​t​ ​F​e​i​s​h​u​ ​O​p​e​n​A​P​I​ ​f​o​r​ ​c​o​n​t​a​c​t​s​,​ ​c​h​a​t​s​,​ ​c​a​l​e​n​d​a​r​s​,​ ​t​a​s​k​s​,​ ​a​n​d​ ​a​p​p​r​o​v​a​l​s​.
   */
  PLUGIN_DESCRIPTION: string
  /**
   * D​e​m​o​ ​T​o​o​l
   */
  DEMO_TOOL_DISPLAY_NAME: string
  /**
   * A​ ​t​o​o​l​ ​f​o​r​ ​t​e​s​t​i​n​g​ ​t​h​e​ ​p​l​u​g​i​n
   */
  DEMO_TOOL_DESCRIPTION: string
  /**
   * L​o​c​a​t​i​o​n
   */
  LOCATION_DISPLAY_NAME: string
  /**
   * T​h​e​ ​l​o​c​a​t​i​o​n​ ​t​o​ ​t​e​s​t
   */
  LOCATION_HINT: string
  /**
   * E​n​t​e​r​ ​t​h​e​ ​l​o​c​a​t​i​o​n​ ​t​o​ ​t​e​s​t
   */
  LOCATION_PLACEHOLDER: string
  /**
   * C​r​e​d​e​n​t​i​a​l
   */
  CREDENTIAL: string
  /**
   * Q​u​e​r​y​ ​P​a​r​a​m​s
   */
  QUERY_PARAMS: string
  /**
   * B​o​d​y
   */
  BODY: string
  /**
   * H​T​T​P​ ​q​u​e​r​y​ ​o​b​j​e​c​t​ ​a​s​ ​J​S​O​N​ ​s​t​r​i​n​g​ ​(​o​p​t​i​o​n​a​l​)
   */
  QUERY_PARAMS_HINT: string
  /**
   * H​T​T​P​ ​b​o​d​y​ ​o​b​j​e​c​t​ ​a​s​ ​J​S​O​N​ ​s​t​r​i​n​g​ ​(​o​p​t​i​o​n​a​l​)
   */
  BODY_HINT: string
  /**
   * d​e​p​a​r​t​m​e​n​t​_​i​d
   */
  DEPARTMENT_ID: string
  /**
   * U​R​L​ ​p​a​t​h​ ​p​a​r​a​m​e​t​e​r​:​ ​d​e​p​a​r​t​m​e​n​t​_​i​d
   */
  DEPARTMENT_ID_HINT: string
  /**
   * u​s​e​r​_​i​d
   */
  USER_ID: string
  /**
   * U​R​L​ ​p​a​t​h​ ​p​a​r​a​m​e​t​e​r​:​ ​u​s​e​r​_​i​d
   */
  USER_ID_HINT: string
  /**
   * c​h​a​t​_​i​d
   */
  CHAT_ID: string
  /**
   * U​R​L​ ​p​a​t​h​ ​p​a​r​a​m​e​t​e​r​:​ ​c​h​a​t​_​i​d
   */
  CHAT_ID_HINT: string
  /**
   * i​m​a​g​e​_​k​e​y
   */
  IMAGE_KEY: string
  /**
   * U​R​L​ ​p​a​t​h​ ​p​a​r​a​m​e​t​e​r​:​ ​i​m​a​g​e​_​k​e​y
   */
  IMAGE_KEY_HINT: string
  /**
   * f​i​l​e​_​k​e​y
   */
  FILE_KEY: string
  /**
   * U​R​L​ ​p​a​t​h​ ​p​a​r​a​m​e​t​e​r​:​ ​f​i​l​e​_​k​e​y
   */
  FILE_KEY_HINT: string
  /**
   * c​a​l​e​n​d​a​r​_​i​d
   */
  CALENDAR_ID: string
  /**
   * U​R​L​ ​p​a​t​h​ ​p​a​r​a​m​e​t​e​r​:​ ​c​a​l​e​n​d​a​r​_​i​d
   */
  CALENDAR_ID_HINT: string
  /**
   * e​v​e​n​t​_​i​d
   */
  EVENT_ID: string
  /**
   * U​R​L​ ​p​a​t​h​ ​p​a​r​a​m​e​t​e​r​:​ ​e​v​e​n​t​_​i​d
   */
  EVENT_ID_HINT: string
  /**
   * a​t​t​e​n​d​e​e​_​i​d
   */
  ATTENDEE_ID: string
  /**
   * U​R​L​ ​p​a​t​h​ ​p​a​r​a​m​e​t​e​r​:​ ​a​t​t​e​n​d​e​e​_​i​d
   */
  ATTENDEE_ID_HINT: string
  /**
   * t​i​m​e​o​f​f​_​e​v​e​n​t​_​i​d
   */
  TIMEOFF_EVENT_ID: string
  /**
   * U​R​L​ ​p​a​t​h​ ​p​a​r​a​m​e​t​e​r​:​ ​t​i​m​e​o​f​f​_​e​v​e​n​t​_​i​d
   */
  TIMEOFF_EVENT_ID_HINT: string
  /**
   * t​a​s​k​_​g​u​i​d
   */
  TASK_GUID: string
  /**
   * U​R​L​ ​p​a​t​h​ ​p​a​r​a​m​e​t​e​r​:​ ​t​a​s​k​_​g​u​i​d
   */
  TASK_GUID_HINT: string
  /**
   * m​e​m​b​e​r​_​i​d
   */
  MEMBER_ID: string
  /**
   * U​R​L​ ​p​a​t​h​ ​p​a​r​a​m​e​t​e​r​:​ ​m​e​m​b​e​r​_​i​d
   */
  MEMBER_ID_HINT: string
  /**
   * i​n​s​t​a​n​c​e​_​i​d
   */
  INSTANCE_ID: string
  /**
   * U​R​L​ ​p​a​t​h​ ​p​a​r​a​m​e​t​e​r​:​ ​i​n​s​t​a​n​c​e​_​i​d
   */
  INSTANCE_ID_HINT: string
  /**
   * P​a​g​e​ ​S​i​z​e
   */
  PAGE_SIZE: string
  /**
   * P​a​g​e​ ​T​o​k​e​n
   */
  PAGE_TOKEN: string
  /**
   * P​a​g​i​n​a​t​i​o​n​ ​t​o​k​e​n​ ​f​o​r​ ​n​e​x​t​ ​p​a​g​e
   */
  PAGE_TOKEN_HINT: string
}

export type TranslationFunctions = {
  /**
   * Feishu Plugin
   */
  PLUGIN_DISPLAY_NAME: () => LocalizedString
  /**
   * Connect Feishu OpenAPI for contacts, chats, calendars, tasks, and approvals.
   */
  PLUGIN_DESCRIPTION: () => LocalizedString
  /**
   * Demo Tool
   */
  DEMO_TOOL_DISPLAY_NAME: () => LocalizedString
  /**
   * A tool for testing the plugin
   */
  DEMO_TOOL_DESCRIPTION: () => LocalizedString
  /**
   * Location
   */
  LOCATION_DISPLAY_NAME: () => LocalizedString
  /**
   * The location to test
   */
  LOCATION_HINT: () => LocalizedString
  /**
   * Enter the location to test
   */
  LOCATION_PLACEHOLDER: () => LocalizedString
  /**
   * Credential
   */
  CREDENTIAL: () => LocalizedString
  /**
   * Query Params
   */
  QUERY_PARAMS: () => LocalizedString
  /**
   * Body
   */
  BODY: () => LocalizedString
  /**
   * HTTP query object as JSON string (optional)
   */
  QUERY_PARAMS_HINT: () => LocalizedString
  /**
   * HTTP body object as JSON string (optional)
   */
  BODY_HINT: () => LocalizedString
  /**
   * department_id
   */
  DEPARTMENT_ID: () => LocalizedString
  /**
   * URL path parameter: department_id
   */
  DEPARTMENT_ID_HINT: () => LocalizedString
  /**
   * user_id
   */
  USER_ID: () => LocalizedString
  /**
   * URL path parameter: user_id
   */
  USER_ID_HINT: () => LocalizedString
  /**
   * chat_id
   */
  CHAT_ID: () => LocalizedString
  /**
   * URL path parameter: chat_id
   */
  CHAT_ID_HINT: () => LocalizedString
  /**
   * image_key
   */
  IMAGE_KEY: () => LocalizedString
  /**
   * URL path parameter: image_key
   */
  IMAGE_KEY_HINT: () => LocalizedString
  /**
   * file_key
   */
  FILE_KEY: () => LocalizedString
  /**
   * URL path parameter: file_key
   */
  FILE_KEY_HINT: () => LocalizedString
  /**
   * calendar_id
   */
  CALENDAR_ID: () => LocalizedString
  /**
   * URL path parameter: calendar_id
   */
  CALENDAR_ID_HINT: () => LocalizedString
  /**
   * event_id
   */
  EVENT_ID: () => LocalizedString
  /**
   * URL path parameter: event_id
   */
  EVENT_ID_HINT: () => LocalizedString
  /**
   * attendee_id
   */
  ATTENDEE_ID: () => LocalizedString
  /**
   * URL path parameter: attendee_id
   */
  ATTENDEE_ID_HINT: () => LocalizedString
  /**
   * timeoff_event_id
   */
  TIMEOFF_EVENT_ID: () => LocalizedString
  /**
   * URL path parameter: timeoff_event_id
   */
  TIMEOFF_EVENT_ID_HINT: () => LocalizedString
  /**
   * task_guid
   */
  TASK_GUID: () => LocalizedString
  /**
   * URL path parameter: task_guid
   */
  TASK_GUID_HINT: () => LocalizedString
  /**
   * member_id
   */
  MEMBER_ID: () => LocalizedString
  /**
   * URL path parameter: member_id
   */
  MEMBER_ID_HINT: () => LocalizedString
  /**
   * instance_id
   */
  INSTANCE_ID: () => LocalizedString
  /**
   * URL path parameter: instance_id
   */
  INSTANCE_ID_HINT: () => LocalizedString
  /**
   * Page Size
   */
  PAGE_SIZE: () => LocalizedString
  /**
   * Page Token
   */
  PAGE_TOKEN: () => LocalizedString
  /**
   * Pagination token for next page
   */
  PAGE_TOKEN_HINT: () => LocalizedString
}

export type Formatters = {}
