// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type {
  BaseTranslation as BaseTranslationType,
  LocalizedString,
} from "typesafe-i18n"

export type BaseTranslation = BaseTranslationType
export type BaseLocale = "en-US"

export type Locales = "en-US" | "zh-Hans"

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
  /**
   * M​a​t​h​ ​E​v​a​l​u​a​t​o​r
   */
  PLUGIN_DISPLAY_NAME: string
  /**
   * A​ ​p​l​u​g​i​n​ ​f​o​r​ ​e​v​a​l​u​a​t​i​n​g​ ​m​a​t​h​ ​e​x​p​r​e​s​s​i​o​n​s
   */
  PLUGIN_DESCRIPTION: string
  /**
   * M​a​t​h​ ​E​v​a​l​u​a​t​o​r
   */
  MATH_EVALUATOR_DISPLAY_NAME: string
  /**
   * E​v​a​l​u​a​t​e​ ​m​a​t​h​ ​e​x​p​r​e​s​s​i​o​n​s​ ​a​n​d​ ​r​e​t​u​r​n​ ​r​e​s​u​l​t​s​ ​u​s​i​n​g​ ​m​a​t​h​.​j​s
   */
  MATH_EVALUATOR_DESCRIPTION: string
  /**
   * E​x​p​r​e​s​s​i​o​n
   */
  EXPRESSION_DISPLAY_NAME: string
  /**
   * E​n​t​e​r​ ​a​ ​m​a​t​h​ ​e​x​p​r​e​s​s​i​o​n​ ​(​e​.​g​.​ ​2​ ​+​ ​3​ ​*​ ​4​,​ ​s​q​r​t​(​1​6​)​,​ ​s​i​n​(​p​i​/​2​)​)
   */
  EXPRESSION_HINT: string
  /**
   * e​.​g​.​ ​2​ ​+​ ​3​ ​*​ ​4
   */
  EXPRESSION_PLACEHOLDER: string
}

export type TranslationFunctions = {
  /**
   * Math Evaluator
   */
  PLUGIN_DISPLAY_NAME: () => LocalizedString
  /**
   * A plugin for evaluating math expressions
   */
  PLUGIN_DESCRIPTION: () => LocalizedString
  /**
   * Math Evaluator
   */
  MATH_EVALUATOR_DISPLAY_NAME: () => LocalizedString
  /**
   * Evaluate math expressions and return results using math.js
   */
  MATH_EVALUATOR_DESCRIPTION: () => LocalizedString
  /**
   * Expression
   */
  EXPRESSION_DISPLAY_NAME: () => LocalizedString
  /**
   * Enter a math expression (e.g. 2 + 3 * 4, sqrt(16), sin(pi/2))
   */
  EXPRESSION_HINT: () => LocalizedString
  /**
   * e.g. 2 + 3 * 4
   */
  EXPRESSION_PLACEHOLDER: () => LocalizedString
}

export type Formatters = {}
