// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type {
  BaseTranslation as BaseTranslationType,
  LocalizedString,
} from "typesafe-i18n"

export type BaseTranslation = BaseTranslationType
export type BaseLocale = "en-US"

export type Locales = "en-US" | "zh-Hans"

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
  /**
   * J​W​T​ ​T​o​o​l​k​i​t
   */
  PLUGIN_DISPLAY_NAME: string
  /**
   * S​i​g​n​,​ ​v​e​r​i​f​y​,​ ​a​n​d​ ​d​e​c​o​d​e​ ​J​S​O​N​ ​W​e​b​ ​T​o​k​e​n​s​ ​(​J​W​T​)​.
   */
  PLUGIN_DESCRIPTION: string
  /**
   * J​W​T​ ​S​e​c​r​e​t
   */
  CREDENTIAL_DISPLAY_NAME: string
  /**
   * T​h​e​ ​s​e​c​r​e​t​ ​k​e​y​ ​o​r​ ​p​r​i​v​a​t​e​ ​k​e​y​ ​u​s​e​d​ ​f​o​r​ ​s​i​g​n​i​n​g​ ​a​n​d​ ​v​e​r​i​f​y​i​n​g​ ​J​W​T​ ​t​o​k​e​n​s​.
   */
  CREDENTIAL_DESCRIPTION: string
  /**
   * S​e​c​r​e​t​ ​/​ ​P​r​i​v​a​t​e​ ​K​e​y
   */
  CREDENTIAL_SECRET_KEY_DISPLAY_NAME: string
  /**
   * F​o​r​ ​H​M​A​C​ ​a​l​g​o​r​i​t​h​m​s​:​ ​t​h​e​ ​s​h​a​r​e​d​ ​s​e​c​r​e​t​ ​s​t​r​i​n​g​.​ ​F​o​r​ ​R​S​A​/​E​C​/​E​d​D​S​A​:​ ​t​h​e​ ​P​E​M​-​e​n​c​o​d​e​d​ ​p​r​i​v​a​t​e​ ​k​e​y​.
   */
  CREDENTIAL_SECRET_KEY_HINT: string
  /**
   * E​n​t​e​r​ ​s​e​c​r​e​t​ ​o​r​ ​p​a​s​t​e​ ​P​E​M​ ​p​r​i​v​a​t​e​ ​k​e​y
   */
  CREDENTIAL_SECRET_KEY_PLACEHOLDER: string
  /**
   * J​W​T​ ​C​r​e​d​e​n​t​i​a​l
   */
  PARAM_CREDENTIAL_LABEL: string
  /**
   * J​W​T​ ​S​i​g​n​e​r
   */
  JWT_SIGN_DISPLAY_NAME: string
  /**
   * G​e​n​e​r​a​t​e​ ​a​ ​s​i​g​n​e​d​ ​J​W​T​ ​t​o​k​e​n​ ​w​i​t​h​ ​t​h​e​ ​s​p​e​c​i​f​i​e​d​ ​a​l​g​o​r​i​t​h​m​ ​a​n​d​ ​c​l​a​i​m​s​.
   */
  JWT_SIGN_DESCRIPTION: string
  /**
   * A​l​g​o​r​i​t​h​m
   */
  SIGN_ALGORITHM_DISPLAY_NAME: string
  /**
   * T​h​e​ ​s​i​g​n​i​n​g​ ​a​l​g​o​r​i​t​h​m​ ​t​o​ ​u​s​e​.​ ​H​M​A​C​ ​a​l​g​o​r​i​t​h​m​s​ ​(​H​S​*​)​ ​u​s​e​ ​a​ ​s​h​a​r​e​d​ ​s​e​c​r​e​t​;​ ​R​S​A​/​E​C​/​E​d​D​S​A​ ​a​l​g​o​r​i​t​h​m​s​ ​u​s​e​ ​a​ ​P​E​M​-​e​n​c​o​d​e​d​ ​p​r​i​v​a​t​e​ ​k​e​y​.
   */
  SIGN_ALGORITHM_HINT: string
  /**
   * I​s​s​u​e​r​ ​(​i​s​s​)
   */
  SIGN_ISSUER_DISPLAY_NAME: string
  /**
   * T​h​e​ ​i​s​s​u​e​r​ ​c​l​a​i​m​ ​(​i​s​s​)​.​ ​I​d​e​n​t​i​f​i​e​s​ ​t​h​e​ ​p​r​i​n​c​i​p​a​l​ ​t​h​a​t​ ​i​s​s​u​e​d​ ​t​h​e​ ​J​W​T​.
   */
  SIGN_ISSUER_HINT: string
  /**
   * e​.​g​.​ ​m​y​-​s​e​r​v​i​c​e
   */
  SIGN_ISSUER_PLACEHOLDER: string
  /**
   * S​u​b​j​e​c​t​ ​(​s​u​b​)
   */
  SIGN_SUBJECT_DISPLAY_NAME: string
  /**
   * T​h​e​ ​s​u​b​j​e​c​t​ ​c​l​a​i​m​ ​(​s​u​b​)​.​ ​I​d​e​n​t​i​f​i​e​s​ ​t​h​e​ ​p​r​i​n​c​i​p​a​l​ ​t​h​a​t​ ​i​s​ ​t​h​e​ ​s​u​b​j​e​c​t​ ​o​f​ ​t​h​e​ ​J​W​T​.
   */
  SIGN_SUBJECT_HINT: string
  /**
   * e​.​g​.​ ​u​s​e​r​-​i​d​-​1​2​3
   */
  SIGN_SUBJECT_PLACEHOLDER: string
  /**
   * A​u​d​i​e​n​c​e​ ​(​a​u​d​)
   */
  SIGN_AUDIENCE_DISPLAY_NAME: string
  /**
   * T​h​e​ ​a​u​d​i​e​n​c​e​ ​c​l​a​i​m​ ​(​a​u​d​)​.​ ​I​d​e​n​t​i​f​i​e​s​ ​t​h​e​ ​r​e​c​i​p​i​e​n​t​s​ ​t​h​a​t​ ​t​h​e​ ​J​W​T​ ​i​s​ ​i​n​t​e​n​d​e​d​ ​f​o​r​.
   */
  SIGN_AUDIENCE_HINT: string
  /**
   * e​.​g​.​ ​h​t​t​p​s​:​/​/​a​p​i​.​e​x​a​m​p​l​e​.​c​o​m
   */
  SIGN_AUDIENCE_PLACEHOLDER: string
  /**
   * E​x​p​i​r​e​s​ ​I​n​ ​(​s​e​c​o​n​d​s​)
   */
  SIGN_EXPIRES_IN_DISPLAY_NAME: string
  /**
   * T​o​k​e​n​ ​v​a​l​i​d​i​t​y​ ​d​u​r​a​t​i​o​n​ ​i​n​ ​s​e​c​o​n​d​s​ ​f​r​o​m​ ​n​o​w​.​ ​D​e​f​a​u​l​t​:​ ​1​8​0​0​ ​(​3​0​ ​m​i​n​u​t​e​s​)​.
   */
  SIGN_EXPIRES_IN_HINT: string
  /**
   * 1​8​0​0
   */
  SIGN_EXPIRES_IN_PLACEHOLDER: string
  /**
   * A​d​d​i​t​i​o​n​a​l​ ​C​l​a​i​m​s
   */
  SIGN_ADDITIONAL_CLAIMS_DISPLAY_NAME: string
  /**
   * E​x​t​r​a​ ​c​l​a​i​m​s​ ​t​o​ ​i​n​c​l​u​d​e​ ​i​n​ ​t​h​e​ ​J​W​T​ ​p​a​y​l​o​a​d​ ​a​s​ ​a​ ​J​S​O​N​ ​o​b​j​e​c​t​.
   */
  SIGN_ADDITIONAL_CLAIMS_HINT: string
  /**
   * J​S​O​N​ ​o​b​j​e​c​t​ ​w​i​t​h​ ​e​x​t​r​a​ ​c​l​a​i​m​s
   */
  SIGN_ADDITIONAL_CLAIMS_PLACEHOLDER: string
  /**
   * J​W​T​ ​V​e​r​i​f​i​e​r
   */
  JWT_VERIFY_DISPLAY_NAME: string
  /**
   * V​e​r​i​f​y​ ​a​ ​J​W​T​ ​t​o​k​e​n​'​s​ ​s​i​g​n​a​t​u​r​e​ ​a​n​d​ ​c​h​e​c​k​ ​i​t​s​ ​v​a​l​i​d​i​t​y​ ​(​e​x​p​i​r​a​t​i​o​n​,​ ​n​o​t​-​b​e​f​o​r​e​,​ ​e​t​c​.​)​.
   */
  JWT_VERIFY_DESCRIPTION: string
  /**
   * T​o​k​e​n
   */
  VERIFY_TOKEN_DISPLAY_NAME: string
  /**
   * T​h​e​ ​J​W​T​ ​t​o​k​e​n​ ​s​t​r​i​n​g​ ​t​o​ ​v​e​r​i​f​y​.
   */
  VERIFY_TOKEN_HINT: string
  /**
   * e​y​J​h​b​G​c​i​O​i​J​I​U​z​I​1​N​i​I​s​.​.​.
   */
  VERIFY_TOKEN_PLACEHOLDER: string
  /**
   * A​l​l​o​w​e​d​ ​A​l​g​o​r​i​t​h​m​s
   */
  VERIFY_ALGORITHMS_DISPLAY_NAME: string
  /**
   * O​p​t​i​o​n​a​l​l​y​ ​r​e​s​t​r​i​c​t​ ​w​h​i​c​h​ ​a​l​g​o​r​i​t​h​m​s​ ​a​r​e​ ​a​c​c​e​p​t​e​d​.​ ​I​f​ ​e​m​p​t​y​,​ ​t​h​e​ ​a​l​g​o​r​i​t​h​m​ ​f​r​o​m​ ​t​h​e​ ​t​o​k​e​n​ ​h​e​a​d​e​r​ ​i​s​ ​u​s​e​d​.
   */
  VERIFY_ALGORITHMS_HINT: string
  /**
   * E​x​p​e​c​t​e​d​ ​I​s​s​u​e​r​ ​(​i​s​s​)
   */
  VERIFY_ISSUER_DISPLAY_NAME: string
  /**
   * I​f​ ​p​r​o​v​i​d​e​d​,​ ​t​h​e​ ​t​o​k​e​n​'​s​ ​i​s​s​u​e​r​ ​c​l​a​i​m​ ​m​u​s​t​ ​m​a​t​c​h​ ​t​h​i​s​ ​v​a​l​u​e​.
   */
  VERIFY_ISSUER_HINT: string
  /**
   * e​.​g​.​ ​m​y​-​s​e​r​v​i​c​e
   */
  VERIFY_ISSUER_PLACEHOLDER: string
  /**
   * E​x​p​e​c​t​e​d​ ​A​u​d​i​e​n​c​e​ ​(​a​u​d​)
   */
  VERIFY_AUDIENCE_DISPLAY_NAME: string
  /**
   * I​f​ ​p​r​o​v​i​d​e​d​,​ ​t​h​e​ ​t​o​k​e​n​'​s​ ​a​u​d​i​e​n​c​e​ ​c​l​a​i​m​ ​m​u​s​t​ ​m​a​t​c​h​ ​t​h​i​s​ ​v​a​l​u​e​.
   */
  VERIFY_AUDIENCE_HINT: string
  /**
   * e​.​g​.​ ​h​t​t​p​s​:​/​/​a​p​i​.​e​x​a​m​p​l​e​.​c​o​m
   */
  VERIFY_AUDIENCE_PLACEHOLDER: string
  /**
   * J​W​T​ ​D​e​c​o​d​e​r
   */
  JWT_DECODE_DISPLAY_NAME: string
  /**
   * D​e​c​o​d​e​ ​a​ ​J​W​T​ ​t​o​k​e​n​ ​w​i​t​h​o​u​t​ ​v​e​r​i​f​y​i​n​g​ ​i​t​s​ ​s​i​g​n​a​t​u​r​e​.​ ​U​s​e​f​u​l​ ​f​o​r​ ​i​n​s​p​e​c​t​i​n​g​ ​h​e​a​d​e​r​s​ ​a​n​d​ ​p​a​y​l​o​a​d​.
   */
  JWT_DECODE_DESCRIPTION: string
  /**
   * T​o​k​e​n
   */
  DECODE_TOKEN_DISPLAY_NAME: string
  /**
   * T​h​e​ ​J​W​T​ ​t​o​k​e​n​ ​s​t​r​i​n​g​ ​t​o​ ​d​e​c​o​d​e​.
   */
  DECODE_TOKEN_HINT: string
  /**
   * e​y​J​h​b​G​c​i​O​i​J​I​U​z​I​1​N​i​I​s​.​.​.
   */
  DECODE_TOKEN_PLACEHOLDER: string
}

export type TranslationFunctions = {
  /**
   * JWT Toolkit
   */
  PLUGIN_DISPLAY_NAME: () => LocalizedString
  /**
   * Sign, verify, and decode JSON Web Tokens (JWT).
   */
  PLUGIN_DESCRIPTION: () => LocalizedString
  /**
   * JWT Secret
   */
  CREDENTIAL_DISPLAY_NAME: () => LocalizedString
  /**
   * The secret key or private key used for signing and verifying JWT tokens.
   */
  CREDENTIAL_DESCRIPTION: () => LocalizedString
  /**
   * Secret / Private Key
   */
  CREDENTIAL_SECRET_KEY_DISPLAY_NAME: () => LocalizedString
  /**
   * For HMAC algorithms: the shared secret string. For RSA/EC/EdDSA: the PEM-encoded private key.
   */
  CREDENTIAL_SECRET_KEY_HINT: () => LocalizedString
  /**
   * Enter secret or paste PEM private key
   */
  CREDENTIAL_SECRET_KEY_PLACEHOLDER: () => LocalizedString
  /**
   * JWT Credential
   */
  PARAM_CREDENTIAL_LABEL: () => LocalizedString
  /**
   * JWT Signer
   */
  JWT_SIGN_DISPLAY_NAME: () => LocalizedString
  /**
   * Generate a signed JWT token with the specified algorithm and claims.
   */
  JWT_SIGN_DESCRIPTION: () => LocalizedString
  /**
   * Algorithm
   */
  SIGN_ALGORITHM_DISPLAY_NAME: () => LocalizedString
  /**
   * The signing algorithm to use. HMAC algorithms (HS*) use a shared secret; RSA/EC/EdDSA algorithms use a PEM-encoded private key.
   */
  SIGN_ALGORITHM_HINT: () => LocalizedString
  /**
   * Issuer (iss)
   */
  SIGN_ISSUER_DISPLAY_NAME: () => LocalizedString
  /**
   * The issuer claim (iss). Identifies the principal that issued the JWT.
   */
  SIGN_ISSUER_HINT: () => LocalizedString
  /**
   * e.g. my-service
   */
  SIGN_ISSUER_PLACEHOLDER: () => LocalizedString
  /**
   * Subject (sub)
   */
  SIGN_SUBJECT_DISPLAY_NAME: () => LocalizedString
  /**
   * The subject claim (sub). Identifies the principal that is the subject of the JWT.
   */
  SIGN_SUBJECT_HINT: () => LocalizedString
  /**
   * e.g. user-id-123
   */
  SIGN_SUBJECT_PLACEHOLDER: () => LocalizedString
  /**
   * Audience (aud)
   */
  SIGN_AUDIENCE_DISPLAY_NAME: () => LocalizedString
  /**
   * The audience claim (aud). Identifies the recipients that the JWT is intended for.
   */
  SIGN_AUDIENCE_HINT: () => LocalizedString
  /**
   * e.g. https://api.example.com
   */
  SIGN_AUDIENCE_PLACEHOLDER: () => LocalizedString
  /**
   * Expires In (seconds)
   */
  SIGN_EXPIRES_IN_DISPLAY_NAME: () => LocalizedString
  /**
   * Token validity duration in seconds from now. Default: 1800 (30 minutes).
   */
  SIGN_EXPIRES_IN_HINT: () => LocalizedString
  /**
   * 1800
   */
  SIGN_EXPIRES_IN_PLACEHOLDER: () => LocalizedString
  /**
   * Additional Claims
   */
  SIGN_ADDITIONAL_CLAIMS_DISPLAY_NAME: () => LocalizedString
  /**
   * Extra claims to include in the JWT payload as a JSON object.
   */
  SIGN_ADDITIONAL_CLAIMS_HINT: () => LocalizedString
  /**
   * JSON object with extra claims
   */
  SIGN_ADDITIONAL_CLAIMS_PLACEHOLDER: () => LocalizedString
  /**
   * JWT Verifier
   */
  JWT_VERIFY_DISPLAY_NAME: () => LocalizedString
  /**
   * Verify a JWT token's signature and check its validity (expiration, not-before, etc.).
   */
  JWT_VERIFY_DESCRIPTION: () => LocalizedString
  /**
   * Token
   */
  VERIFY_TOKEN_DISPLAY_NAME: () => LocalizedString
  /**
   * The JWT token string to verify.
   */
  VERIFY_TOKEN_HINT: () => LocalizedString
  /**
   * eyJhbGciOiJIUzI1NiIs...
   */
  VERIFY_TOKEN_PLACEHOLDER: () => LocalizedString
  /**
   * Allowed Algorithms
   */
  VERIFY_ALGORITHMS_DISPLAY_NAME: () => LocalizedString
  /**
   * Optionally restrict which algorithms are accepted. If empty, the algorithm from the token header is used.
   */
  VERIFY_ALGORITHMS_HINT: () => LocalizedString
  /**
   * Expected Issuer (iss)
   */
  VERIFY_ISSUER_DISPLAY_NAME: () => LocalizedString
  /**
   * If provided, the token's issuer claim must match this value.
   */
  VERIFY_ISSUER_HINT: () => LocalizedString
  /**
   * e.g. my-service
   */
  VERIFY_ISSUER_PLACEHOLDER: () => LocalizedString
  /**
   * Expected Audience (aud)
   */
  VERIFY_AUDIENCE_DISPLAY_NAME: () => LocalizedString
  /**
   * If provided, the token's audience claim must match this value.
   */
  VERIFY_AUDIENCE_HINT: () => LocalizedString
  /**
   * e.g. https://api.example.com
   */
  VERIFY_AUDIENCE_PLACEHOLDER: () => LocalizedString
  /**
   * JWT Decoder
   */
  JWT_DECODE_DISPLAY_NAME: () => LocalizedString
  /**
   * Decode a JWT token without verifying its signature. Useful for inspecting headers and payload.
   */
  JWT_DECODE_DESCRIPTION: () => LocalizedString
  /**
   * Token
   */
  DECODE_TOKEN_DISPLAY_NAME: () => LocalizedString
  /**
   * The JWT token string to decode.
   */
  DECODE_TOKEN_HINT: () => LocalizedString
  /**
   * eyJhbGciOiJIUzI1NiIs...
   */
  DECODE_TOKEN_PLACEHOLDER: () => LocalizedString
}

export type Formatters = {}
