// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type {
  BaseTranslation as BaseTranslationType,
  LocalizedString,
} from "typesafe-i18n"

export type BaseTranslation = BaseTranslationType
export type BaseLocale = "en-US"

export type Locales = "en-US" | "zh-Hans"

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
  /**
   * J​S​O​N​ ​R​e​a​d​e​r
   */
  PLUGIN_DISPLAY_NAME: string
  /**
   * R​e​a​d​ ​a​ ​f​i​l​e​ ​a​n​d​ ​p​a​r​s​e​ ​i​t​ ​a​s​ ​a​ ​J​S​O​N​ ​o​b​j​e​c​t​,​ ​w​i​t​h​ ​B​O​M​ ​h​e​a​d​e​r​ ​s​u​p​p​o​r​t
   */
  PLUGIN_DESCRIPTION: string
  /**
   * R​e​a​d​ ​J​S​O​N
   */
  READ_JSON_TOOL_DISPLAY_NAME: string
  /**
   * P​a​r​s​e​ ​a​ ​f​i​l​e​_​r​e​f​ ​a​s​ ​J​S​O​N​ ​o​b​j​e​c​t​.​ ​A​u​t​o​m​a​t​i​c​a​l​l​y​ ​h​a​n​d​l​e​s​ ​B​O​M​ ​h​e​a​d​e​r​s​ ​a​n​d​ ​e​n​c​o​d​i​n​g​ ​d​e​t​e​c​t​i​o​n​.
   */
  READ_JSON_TOOL_DESCRIPTION: string
  /**
   * F​i​l​e
   */
  FILE_DISPLAY_NAME: string
  /**
   * T​h​e​ ​f​i​l​e​ ​t​o​ ​p​a​r​s​e​ ​a​s​ ​J​S​O​N
   */
  FILE_HINT: string
}

export type TranslationFunctions = {
  /**
   * JSON Reader
   */
  PLUGIN_DISPLAY_NAME: () => LocalizedString
  /**
   * Read a file and parse it as a JSON object, with BOM header support
   */
  PLUGIN_DESCRIPTION: () => LocalizedString
  /**
   * Read JSON
   */
  READ_JSON_TOOL_DISPLAY_NAME: () => LocalizedString
  /**
   * Parse a file_ref as JSON object. Automatically handles BOM headers and encoding detection.
   */
  READ_JSON_TOOL_DESCRIPTION: () => LocalizedString
  /**
   * File
   */
  FILE_DISPLAY_NAME: () => LocalizedString
  /**
   * The file to parse as JSON
   */
  FILE_HINT: () => LocalizedString
}

export type Formatters = {}
