// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type {
  BaseTranslation as BaseTranslationType,
  LocalizedString,
} from "typesafe-i18n"

export type BaseTranslation = BaseTranslationType
export type BaseLocale = "en-US"

export type Locales = "en-US" | "zh-Hans"

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
  /**
   * T​a​v​i​l​y
   */
  PLUGIN_DISPLAY_NAME: string
  /**
   * S​e​a​r​c​h​ ​a​n​d​ ​e​x​t​r​a​c​t​ ​w​e​b​ ​c​o​n​t​e​n​t​ ​u​s​i​n​g​ ​T​a​v​i​l​y
   */
  PLUGIN_DESCRIPTION: string
  /**
   * D​e​m​o​ ​T​o​o​l
   */
  DEMO_TOOL_DISPLAY_NAME: string
  /**
   * A​ ​t​o​o​l​ ​f​o​r​ ​t​e​s​t​i​n​g​ ​t​h​e​ ​p​l​u​g​i​n
   */
  DEMO_TOOL_DESCRIPTION: string
  /**
   * L​o​c​a​t​i​o​n
   */
  LOCATION_DISPLAY_NAME: string
  /**
   * T​h​e​ ​l​o​c​a​t​i​o​n​ ​t​o​ ​t​e​s​t
   */
  LOCATION_HINT: string
  /**
   * E​n​t​e​r​ ​t​h​e​ ​l​o​c​a​t​i​o​n​ ​t​o​ ​t​e​s​t
   */
  LOCATION_PLACEHOLDER: string
}

export type TranslationFunctions = {
  /**
   * Tavily
   */
  PLUGIN_DISPLAY_NAME: () => LocalizedString
  /**
   * Search and extract web content using Tavily
   */
  PLUGIN_DESCRIPTION: () => LocalizedString
  /**
   * Demo Tool
   */
  DEMO_TOOL_DISPLAY_NAME: () => LocalizedString
  /**
   * A tool for testing the plugin
   */
  DEMO_TOOL_DESCRIPTION: () => LocalizedString
  /**
   * Location
   */
  LOCATION_DISPLAY_NAME: () => LocalizedString
  /**
   * The location to test
   */
  LOCATION_HINT: () => LocalizedString
  /**
   * Enter the location to test
   */
  LOCATION_PLACEHOLDER: () => LocalizedString
}

export type Formatters = {}
