// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type {
  BaseTranslation as BaseTranslationType,
  LocalizedString,
} from "typesafe-i18n"

export type BaseTranslation = BaseTranslationType
export type BaseLocale = "en-US"

export type Locales = "en-US" | "zh-Hans"

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
  /**
   * M​e​t​e​o​ ​W​e​a​t​h​e​r
   */
  PLUGIN_DISPLAY_NAME: string
  /**
   * G​e​t​ ​c​u​r​r​e​n​t​ ​w​e​a​t​h​e​r​ ​b​y​ ​c​i​t​y​ ​o​r​ ​l​o​c​a​t​i​o​n​ ​n​a​m​e​ ​(​O​p​e​n​-​M​e​t​e​o​)
   */
  PLUGIN_DESCRIPTION: string
  /**
   * G​e​t​ ​C​u​r​r​e​n​t​ ​W​e​a​t​h​e​r
   */
  GET_CURRENT_WEATHER_TOOL_DISPLAY_NAME: string
  /**
   * G​e​t​ ​c​u​r​r​e​n​t​ ​w​e​a​t​h​e​r​ ​f​o​r​ ​a​ ​g​i​v​e​n​ ​c​i​t​y​ ​o​r​ ​l​o​c​a​t​i​o​n
   */
  GET_CURRENT_WEATHER_TOOL_DESCRIPTION: string
  /**
   * L​o​c​a​t​i​o​n
   */
  LOCATION_DISPLAY_NAME: string
  /**
   * C​i​t​y​ ​n​a​m​e​ ​o​r​ ​l​o​c​a​t​i​o​n​,​ ​e​.​g​.​ ​B​e​i​j​i​n​g​,​ ​T​o​k​y​o
   */
  LOCATION_HINT: string
  /**
   * e​.​g​.​ ​B​e​i​j​i​n​g
   */
  LOCATION_PLACEHOLDER: string
  /**
   * T​e​m​p​e​r​a​t​u​r​e​ ​u​n​i​t
   */
  TEMPERATURE_UNIT_DISPLAY_NAME: string
  /**
   * c​e​l​s​i​u​s​ ​o​r​ ​f​a​h​r​e​n​h​e​i​t
   */
  TEMPERATURE_UNIT_HINT: string
  /**
   * C​e​l​s​i​u​s​ ​(​°​C​)
   */
  TEMPERATURE_UNIT_OPTION_CELSIUS: string
  /**
   * F​a​h​r​e​n​h​e​i​t​ ​(​°​F​)
   */
  TEMPERATURE_UNIT_OPTION_FAHRENHEIT: string
  /**
   * W​i​n​d​ ​s​p​e​e​d​ ​u​n​i​t
   */
  WIND_SPEED_UNIT_DISPLAY_NAME: string
  /**
   * k​m​h​,​ ​m​s​,​ ​m​p​h​,​ ​o​r​ ​k​n
   */
  WIND_SPEED_UNIT_HINT: string
  /**
   * k​m​/​h
   */
  WIND_SPEED_OPTION_KMH: string
  /**
   * m​/​s
   */
  WIND_SPEED_OPTION_MS: string
  /**
   * m​p​h
   */
  WIND_SPEED_OPTION_MPH: string
  /**
   * k​n
   */
  WIND_SPEED_OPTION_KN: string
  /**
   * P​r​e​c​i​p​i​t​a​t​i​o​n​ ​u​n​i​t
   */
  PRECIPITATION_UNIT_DISPLAY_NAME: string
  /**
   * m​m​ ​o​r​ ​i​n​c​h
   */
  PRECIPITATION_UNIT_HINT: string
  /**
   * m​m
   */
  PRECIPITATION_OPTION_MM: string
  /**
   * i​n​c​h
   */
  PRECIPITATION_OPTION_INCH: string
  /**
   * T​i​m​e​z​o​n​e
   */
  TIMEZONE_DISPLAY_NAME: string
  /**
   * e​.​g​.​ ​A​s​i​a​/​S​h​a​n​g​h​a​i​,​ ​o​r​ ​l​e​a​v​e​ ​e​m​p​t​y​ ​f​o​r​ ​a​u​t​o​ ​f​r​o​m​ ​l​o​c​a​t​i​o​n
   */
  TIMEZONE_HINT: string
  /**
   * e​.​g​.​ ​A​s​i​a​/​S​h​a​n​g​h​a​i​ ​o​r​ ​a​u​t​o
   */
  TIMEZONE_PLACEHOLDER: string
}

export type TranslationFunctions = {
  /**
   * Meteo Weather
   */
  PLUGIN_DISPLAY_NAME: () => LocalizedString
  /**
   * Get current weather by city or location name (Open-Meteo)
   */
  PLUGIN_DESCRIPTION: () => LocalizedString
  /**
   * Get Current Weather
   */
  GET_CURRENT_WEATHER_TOOL_DISPLAY_NAME: () => LocalizedString
  /**
   * Get current weather for a given city or location
   */
  GET_CURRENT_WEATHER_TOOL_DESCRIPTION: () => LocalizedString
  /**
   * Location
   */
  LOCATION_DISPLAY_NAME: () => LocalizedString
  /**
   * City name or location, e.g. Beijing, Tokyo
   */
  LOCATION_HINT: () => LocalizedString
  /**
   * e.g. Beijing
   */
  LOCATION_PLACEHOLDER: () => LocalizedString
  /**
   * Temperature unit
   */
  TEMPERATURE_UNIT_DISPLAY_NAME: () => LocalizedString
  /**
   * celsius or fahrenheit
   */
  TEMPERATURE_UNIT_HINT: () => LocalizedString
  /**
   * Celsius (°C)
   */
  TEMPERATURE_UNIT_OPTION_CELSIUS: () => LocalizedString
  /**
   * Fahrenheit (°F)
   */
  TEMPERATURE_UNIT_OPTION_FAHRENHEIT: () => LocalizedString
  /**
   * Wind speed unit
   */
  WIND_SPEED_UNIT_DISPLAY_NAME: () => LocalizedString
  /**
   * kmh, ms, mph, or kn
   */
  WIND_SPEED_UNIT_HINT: () => LocalizedString
  /**
   * km/h
   */
  WIND_SPEED_OPTION_KMH: () => LocalizedString
  /**
   * m/s
   */
  WIND_SPEED_OPTION_MS: () => LocalizedString
  /**
   * mph
   */
  WIND_SPEED_OPTION_MPH: () => LocalizedString
  /**
   * kn
   */
  WIND_SPEED_OPTION_KN: () => LocalizedString
  /**
   * Precipitation unit
   */
  PRECIPITATION_UNIT_DISPLAY_NAME: () => LocalizedString
  /**
   * mm or inch
   */
  PRECIPITATION_UNIT_HINT: () => LocalizedString
  /**
   * mm
   */
  PRECIPITATION_OPTION_MM: () => LocalizedString
  /**
   * inch
   */
  PRECIPITATION_OPTION_INCH: () => LocalizedString
  /**
   * Timezone
   */
  TIMEZONE_DISPLAY_NAME: () => LocalizedString
  /**
   * e.g. Asia/Shanghai, or leave empty for auto from location
   */
  TIMEZONE_HINT: () => LocalizedString
  /**
   * e.g. Asia/Shanghai or auto
   */
  TIMEZONE_PLACEHOLDER: () => LocalizedString
}

export type Formatters = {}
