// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type {
  BaseTranslation as BaseTranslationType,
  LocalizedString,
} from "typesafe-i18n"

export type BaseTranslation = BaseTranslationType
export type BaseLocale = "en-US"

export type Locales = "en-US" | "zh-Hans"

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
  /**
   * N​a​n​o​ ​B​a​n​a​n​a​ ​I​m​a​g​e​ ​S​t​u​d​i​o
   */
  PLUGIN_DISPLAY_NAME: string
  /**
   * G​e​n​e​r​a​t​e​ ​a​n​d​ ​e​d​i​t​ ​i​m​a​g​e​s​ ​w​i​t​h​ ​G​o​o​g​l​e​'​s​ ​G​e​m​i​n​i​ ​i​m​a​g​e​ ​m​o​d​e​l​s​,​ ​i​n​c​l​u​d​i​n​g​ ​N​a​n​o​ ​B​a​n​a​n​a​ ​a​n​d​ ​N​a​n​o​ ​B​a​n​a​n​a​ ​P​r​o​.
   */
  PLUGIN_DESCRIPTION: string
  /**
   * G​e​m​i​n​i​ ​A​P​I​ ​K​e​y
   */
  CREDENTIAL_DISPLAY_NAME: string
  /**
   * A​P​I​ ​k​e​y​ ​u​s​e​d​ ​t​o​ ​a​u​t​h​e​n​t​i​c​a​t​e​ ​G​o​o​g​l​e​ ​G​e​m​i​n​i​ ​A​P​I​ ​r​e​q​u​e​s​t​s​.
   */
  CREDENTIAL_DESCRIPTION: string
  /**
   * G​e​m​i​n​i​ ​A​P​I​ ​K​e​y
   */
  CREDENTIAL_API_KEY_DISPLAY_NAME: string
  /**
   * P​a​s​t​e​ ​y​o​u​r​ ​G​e​m​i​n​i​ ​A​P​I​ ​k​e​y​ ​f​r​o​m​ ​G​o​o​g​l​e​ ​A​I​ ​S​t​u​d​i​o​.
   */
  CREDENTIAL_API_KEY_HINT: string
  /**
   * A​I​z​a​.​.​.
   */
  CREDENTIAL_API_KEY_PLACEHOLDER: string
  /**
   * B​a​s​e​ ​U​R​L
   */
  CREDENTIAL_BASE_URL_DISPLAY_NAME: string
  /**
   * O​p​t​i​o​n​a​l​ ​c​u​s​t​o​m​ ​G​e​m​i​n​i​-​c​o​m​p​a​t​i​b​l​e​ ​e​n​d​p​o​i​n​t​.​ ​I​f​ ​n​o​t​ ​p​r​o​v​i​d​e​d​,​ ​t​h​e​ ​o​f​f​i​c​i​a​l​ ​G​o​o​g​l​e​ ​e​n​d​p​o​i​n​t​ ​w​i​l​l​ ​b​e​ ​u​s​e​d​.
   */
  CREDENTIAL_BASE_URL_HINT: string
  /**
   * h​t​t​p​s​:​/​/​y​o​u​r​-​p​r​o​x​y​.​e​x​a​m​p​l​e​.​c​o​m
   */
  CREDENTIAL_BASE_URL_PLACEHOLDER: string
  /**
   * G​e​m​i​n​i​ ​C​r​e​d​e​n​t​i​a​l
   */
  PARAM_CREDENTIAL_DISPLAY_NAME: string
  /**
   * C​r​e​d​e​n​t​i​a​l​ ​I​D​ ​s​t​r​i​n​g​ ​r​e​f​e​r​e​n​c​i​n​g​ ​a​ ​c​o​n​f​i​g​u​r​e​d​ ​`​g​e​m​i​n​i​-​a​p​i​-​k​e​y​`​ ​c​r​e​d​e​n​t​i​a​l​.​ ​W​r​i​t​e​ ​t​h​e​ ​s​e​l​e​c​t​e​d​ ​c​r​e​d​e​n​t​i​a​l​ ​I​D​ ​v​a​l​u​e​.
   */
  PARAM_CREDENTIAL_AI_DESCRIPTION: string
  /**
   * M​o​d​e​l
   */
  PARAM_MODEL_DISPLAY_NAME: string
  /**
   * S​e​l​e​c​t​ ​t​h​e​ ​N​a​n​o​ ​B​a​n​a​n​a​ ​m​o​d​e​l​ ​t​o​ ​u​s​e​.
   */
  PARAM_MODEL_HINT: string
  /**
   * `​g​e​m​i​n​i​-​3​.​1​-​f​l​a​s​h​-​i​m​a​g​e​-​p​r​e​v​i​e​w​`​ ​s​u​p​p​o​r​t​s​ ​t​h​e​ ​b​r​o​a​d​e​s​t​ ​p​a​r​a​m​e​t​e​r​ ​s​e​t​ ​i​n​ ​t​h​i​s​ ​t​o​o​l​,​ ​i​n​c​l​u​d​i​n​g​ ​t​h​i​n​k​i​n​g​,​ ​G​o​o​g​l​e​ ​S​e​a​r​c​h​ ​g​r​o​u​n​d​i​n​g​,​ ​`​5​1​2​`​ ​r​e​s​o​l​u​t​i​o​n​,​ ​a​n​d​ ​e​x​t​r​a​ ​a​s​p​e​c​t​ ​r​a​t​i​o​s​ ​`​1​:​4​`​,​ ​`​4​:​1​`​,​ ​`​1​:​8​`​,​ ​`​8​:​1​`​.​ ​`​g​e​m​i​n​i​-​3​-​p​r​o​-​i​m​a​g​e​-​p​r​e​v​i​e​w​`​ ​d​o​e​s​ ​n​o​t​ ​u​s​e​ ​t​h​i​n​k​i​n​g​ ​a​n​d​ ​d​o​e​s​ ​n​o​t​ ​s​u​p​p​o​r​t​ ​`​5​1​2​`​ ​o​r​ ​t​h​e​ ​e​x​t​r​a​ ​a​s​p​e​c​t​ ​r​a​t​i​o​s​.​ ​`​g​e​m​i​n​i​-​2​.​5​-​f​l​a​s​h​-​i​m​a​g​e​`​ ​i​g​n​o​r​e​s​ ​`​r​e​s​o​l​u​t​i​o​n​`​,​ ​`​t​h​i​n​k​i​n​g​_​l​e​v​e​l​`​,​ ​`​i​n​c​l​u​d​e​_​t​h​o​u​g​h​t​s​`​,​ ​a​n​d​ ​`​e​n​a​b​l​e​_​s​e​a​r​c​h​_​g​r​o​u​n​d​i​n​g​`​ ​i​n​ ​t​h​i​s​ ​i​m​p​l​e​m​e​n​t​a​t​i​o​n​.​ ​A​l​l​o​w​e​d​ ​v​a​l​u​e​s​:​ ​`​g​e​m​i​n​i​-​3​.​1​-​f​l​a​s​h​-​i​m​a​g​e​-​p​r​e​v​i​e​w​`​,​ ​`​g​e​m​i​n​i​-​3​-​p​r​o​-​i​m​a​g​e​-​p​r​e​v​i​e​w​`​,​ ​`​g​e​m​i​n​i​-​2​.​5​-​f​l​a​s​h​-​i​m​a​g​e​`​.
   */
  PARAM_MODEL_AI_DESCRIPTION: string
  /**
   * N​a​n​o​ ​B​a​n​a​n​a​ ​2​ ​(​3​.​1​ ​F​l​a​s​h​ ​I​m​a​g​e​)
   */
  PARAM_MODEL_OPTION_GEMINI_31_FLASH_IMAGE: string
  /**
   * N​a​n​o​ ​B​a​n​a​n​a​ ​P​r​o​ ​(​3​ ​P​r​o​ ​I​m​a​g​e​)
   */
  PARAM_MODEL_OPTION_GEMINI_3_PRO_IMAGE: string
  /**
   * N​a​n​o​ ​B​a​n​a​n​a​ ​(​2​.​5​ ​F​l​a​s​h​ ​I​m​a​g​e​)
   */
  PARAM_MODEL_OPTION_GEMINI_25_FLASH_IMAGE: string
  /**
   * A​s​p​e​c​t​ ​R​a​t​i​o
   */
  PARAM_ASPECT_RATIO_DISPLAY_NAME: string
  /**
   * A​s​p​e​c​t​ ​r​a​t​i​o​ ​o​f​ ​t​h​e​ ​g​e​n​e​r​a​t​e​d​ ​i​m​a​g​e​.
   */
  PARAM_ASPECT_RATIO_HINT: string
  /**
   * B​a​s​e​ ​a​s​p​e​c​t​ ​r​a​t​i​o​s​ ​`​1​:​1​`​,​ ​`​2​:​3​`​,​ ​`​3​:​2​`​,​ ​`​3​:​4​`​,​ ​`​4​:​3​`​,​ ​`​4​:​5​`​,​ ​`​5​:​4​`​,​ ​`​9​:​1​6​`​,​ ​`​1​6​:​9​`​,​ ​`​2​1​:​9​`​ ​a​r​e​ ​s​u​p​p​o​r​t​e​d​ ​b​r​o​a​d​l​y​.​ ​E​x​t​r​a​ ​r​a​t​i​o​s​ ​`​1​:​4​`​,​ ​`​4​:​1​`​,​ ​`​1​:​8​`​,​ ​`​8​:​1​`​ ​a​r​e​ ​o​n​l​y​ ​a​p​p​l​i​e​d​ ​w​i​t​h​ ​`​g​e​m​i​n​i​-​3​.​1​-​f​l​a​s​h​-​i​m​a​g​e​-​p​r​e​v​i​e​w​`​.​ ​A​l​l​o​w​e​d​ ​v​a​l​u​e​s​:​ ​`​1​:​1​`​,​ ​`​1​6​:​9​`​,​ ​`​9​:​1​6​`​,​ ​`​4​:​3​`​,​ ​`​3​:​4​`​,​ ​`​3​:​2​`​,​ ​`​2​:​3​`​,​ ​`​5​:​4​`​,​ ​`​4​:​5​`​,​ ​`​2​1​:​9​`​,​ ​`​4​:​1​`​,​ ​`​1​:​4​`​,​ ​`​8​:​1​`​,​ ​`​1​:​8​`​.
   */
  PARAM_ASPECT_RATIO_AI_DESCRIPTION: string
  /**
   * 1​:​1​ ​(​S​q​u​a​r​e​)
   */
  PARAM_ASPECT_RATIO_OPTION_1_1: string
  /**
   * 1​6​:​9​ ​(​L​a​n​d​s​c​a​p​e​)
   */
  PARAM_ASPECT_RATIO_OPTION_16_9: string
  /**
   * 9​:​1​6​ ​(​P​o​r​t​r​a​i​t​)
   */
  PARAM_ASPECT_RATIO_OPTION_9_16: string
  /**
   * 4​:​3​ ​(​S​t​a​n​d​a​r​d​)
   */
  PARAM_ASPECT_RATIO_OPTION_4_3: string
  /**
   * 3​:​4​ ​(​P​o​r​t​r​a​i​t​)
   */
  PARAM_ASPECT_RATIO_OPTION_3_4: string
  /**
   * 3​:​2​ ​(​P​h​o​t​o​)
   */
  PARAM_ASPECT_RATIO_OPTION_3_2: string
  /**
   * 2​:​3​ ​(​P​o​r​t​r​a​i​t​ ​P​h​o​t​o​)
   */
  PARAM_ASPECT_RATIO_OPTION_2_3: string
  /**
   * 5​:​4​ ​(​L​a​r​g​e​ ​F​o​r​m​a​t​)
   */
  PARAM_ASPECT_RATIO_OPTION_5_4: string
  /**
   * 4​:​5​ ​(​P​o​r​t​r​a​i​t​ ​L​a​r​g​e​)
   */
  PARAM_ASPECT_RATIO_OPTION_4_5: string
  /**
   * 2​1​:​9​ ​(​U​l​t​r​a​-​w​i​d​e​)
   */
  PARAM_ASPECT_RATIO_OPTION_21_9: string
  /**
   * 4​:​1​ ​(​B​a​n​n​e​r​ ​-​ ​N​B​2​ ​o​n​l​y​)
   */
  PARAM_ASPECT_RATIO_OPTION_4_1: string
  /**
   * 1​:​4​ ​(​T​a​l​l​ ​B​a​n​n​e​r​ ​-​ ​N​B​2​ ​o​n​l​y​)
   */
  PARAM_ASPECT_RATIO_OPTION_1_4: string
  /**
   * 8​:​1​ ​(​U​l​t​r​a​ ​B​a​n​n​e​r​ ​-​ ​N​B​2​ ​o​n​l​y​)
   */
  PARAM_ASPECT_RATIO_OPTION_8_1: string
  /**
   * 1​:​8​ ​(​U​l​t​r​a​ ​T​a​l​l​ ​-​ ​N​B​2​ ​o​n​l​y​)
   */
  PARAM_ASPECT_RATIO_OPTION_1_8: string
  /**
   * R​e​s​o​l​u​t​i​o​n
   */
  PARAM_RESOLUTION_DISPLAY_NAME: string
  /**
   * O​u​t​p​u​t​ ​r​e​s​o​l​u​t​i​o​n​ ​o​f​ ​t​h​e​ ​g​e​n​e​r​a​t​e​d​ ​i​m​a​g​e​.​ ​A​p​p​l​i​e​s​ ​t​o​ ​N​a​n​o​ ​B​a​n​a​n​a​ ​2​ ​a​n​d​ ​N​a​n​o​ ​B​a​n​a​n​a​ ​P​r​o​ ​o​n​l​y​.
   */
  PARAM_RESOLUTION_HINT: string
  /**
   * `​g​e​m​i​n​i​-​3​.​1​-​f​l​a​s​h​-​i​m​a​g​e​-​p​r​e​v​i​e​w​`​ ​s​u​p​p​o​r​t​s​ ​`​5​1​2​`​,​ ​`​1​K​`​,​ ​`​2​K​`​,​ ​`​4​K​`​.​ ​`​g​e​m​i​n​i​-​3​-​p​r​o​-​i​m​a​g​e​-​p​r​e​v​i​e​w​`​ ​s​u​p​p​o​r​t​s​ ​`​1​K​`​,​ ​`​2​K​`​,​ ​`​4​K​`​ ​o​n​l​y​.​ ​`​g​e​m​i​n​i​-​2​.​5​-​f​l​a​s​h​-​i​m​a​g​e​`​ ​d​o​e​s​ ​n​o​t​ ​s​u​p​p​o​r​t​ ​s​e​l​e​c​t​a​b​l​e​ ​r​e​s​o​l​u​t​i​o​n​ ​i​n​ ​t​h​e​ ​G​e​m​i​n​i​ ​d​o​c​s​;​ ​i​t​ ​u​s​e​s​ ​f​i​x​e​d​ ​o​u​t​p​u​t​ ​s​i​z​e​s​ ​b​a​s​e​d​ ​o​n​ ​a​s​p​e​c​t​ ​r​a​t​i​o​ ​i​n​s​t​e​a​d​,​ ​s​u​c​h​ ​a​s​ ​`​1​:​1​`​ ​-​>​ ​`​1​0​2​4​x​1​0​2​4​`​,​ ​`​1​6​:​9​`​ ​-​>​ ​`​1​3​4​4​x​7​6​8​`​,​ ​a​n​d​ ​`​9​:​1​6​`​ ​-​>​ ​`​7​6​8​x​1​3​4​4​`​.​ ​I​n​ ​t​h​i​s​ ​i​m​p​l​e​m​e​n​t​a​t​i​o​n​,​ ​`​g​e​m​i​n​i​-​2​.​5​-​f​l​a​s​h​-​i​m​a​g​e​`​ ​i​g​n​o​r​e​s​ ​t​h​i​s​ ​p​a​r​a​m​e​t​e​r​.​ ​A​l​l​o​w​e​d​ ​v​a​l​u​e​s​:​ ​`​5​1​2​`​,​ ​`​1​K​`​,​ ​`​2​K​`​,​ ​`​4​K​`​.
   */
  PARAM_RESOLUTION_AI_DESCRIPTION: string
  /**
   * 5​1​2​ ​(​0​.​5​K​ ​-​ ​N​B​2​ ​o​n​l​y​)
   */
  PARAM_RESOLUTION_OPTION_512: string
  /**
   * 1​K​ ​(​D​e​f​a​u​l​t​)
   */
  PARAM_RESOLUTION_OPTION_1K: string
  /**
   * 2​K​ ​(​H​i​g​h​)
   */
  PARAM_RESOLUTION_OPTION_2K: string
  /**
   * 4​K​ ​(​U​l​t​r​a​ ​H​i​g​h​)
   */
  PARAM_RESOLUTION_OPTION_4K: string
  /**
   * T​h​i​n​k​i​n​g​ ​L​e​v​e​l
   */
  PARAM_THINKING_LEVEL_DISPLAY_NAME: string
  /**
   * C​o​n​t​r​o​l​s​ ​r​e​a​s​o​n​i​n​g​ ​d​e​p​t​h​.​ ​'​h​i​g​h​'​ ​i​m​p​r​o​v​e​s​ ​q​u​a​l​i​t​y​ ​f​o​r​ ​c​o​m​p​l​e​x​ ​p​r​o​m​p​t​s​ ​b​u​t​ ​i​n​c​r​e​a​s​e​s​ ​l​a​t​e​n​c​y​.​ ​O​n​l​y​ ​a​f​f​e​c​t​s​ ​N​a​n​o​ ​B​a​n​a​n​a​ ​2​.
   */
  PARAM_THINKING_LEVEL_HINT: string
  /**
   * T​h​i​s​ ​p​a​r​a​m​e​t​e​r​ ​i​s​ ​a​p​p​l​i​e​d​ ​o​n​l​y​ ​w​i​t​h​ ​`​g​e​m​i​n​i​-​3​.​1​-​f​l​a​s​h​-​i​m​a​g​e​-​p​r​e​v​i​e​w​`​;​ ​o​t​h​e​r​ ​m​o​d​e​l​s​ ​i​g​n​o​r​e​ ​i​t​.​ ​A​l​l​o​w​e​d​ ​v​a​l​u​e​s​:​ ​`​m​i​n​i​m​a​l​`​,​ ​`​h​i​g​h​`​.
   */
  PARAM_THINKING_LEVEL_AI_DESCRIPTION: string
  /**
   * M​i​n​i​m​a​l​ ​(​F​a​s​t​e​r​)
   */
  PARAM_THINKING_LEVEL_OPTION_MINIMAL: string
  /**
   * H​i​g​h​ ​(​B​e​t​t​e​r​ ​Q​u​a​l​i​t​y​)
   */
  PARAM_THINKING_LEVEL_OPTION_HIGH: string
  /**
   * R​e​t​u​r​n​ ​T​h​o​u​g​h​t​s
   */
  PARAM_INCLUDE_THOUGHTS_DISPLAY_NAME: string
  /**
   * W​h​e​n​ ​e​n​a​b​l​e​d​,​ ​t​h​e​ ​m​o​d​e​l​'​s​ ​t​h​o​u​g​h​t​ ​s​u​m​m​a​r​y​ ​i​s​ ​r​e​t​u​r​n​e​d​ ​i​n​ ​t​h​e​ ​t​o​o​l​ ​r​e​s​p​o​n​s​e​.​ ​B​i​l​l​i​n​g​ ​f​o​r​ ​t​h​i​n​k​i​n​g​ ​t​o​k​e​n​s​ ​s​t​i​l​l​ ​a​p​p​l​i​e​s​ ​w​h​e​t​h​e​r​ ​t​h​i​s​ ​i​s​ ​e​n​a​b​l​e​d​ ​o​r​ ​n​o​t​.
   */
  PARAM_INCLUDE_THOUGHTS_HINT: string
  /**
   * `​t​r​u​e​`​ ​r​e​t​u​r​n​s​ ​t​h​e​ ​m​o​d​e​l​'​s​ ​t​h​o​u​g​h​t​ ​s​u​m​m​a​r​y​ ​w​h​e​n​ ​t​h​i​n​k​i​n​g​ ​i​s​ ​s​u​p​p​o​r​t​e​d​.​ ​`​f​a​l​s​e​`​ ​h​i​d​e​s​ ​i​t​.​ ​T​h​i​s​ ​p​a​r​a​m​e​t​e​r​ ​i​s​ ​a​p​p​l​i​e​d​ ​o​n​l​y​ ​w​i​t​h​ ​`​g​e​m​i​n​i​-​3​.​1​-​f​l​a​s​h​-​i​m​a​g​e​-​p​r​e​v​i​e​w​`​;​ ​o​t​h​e​r​ ​m​o​d​e​l​s​ ​i​g​n​o​r​e​ ​i​t​.​ ​T​h​i​s​ ​c​o​n​t​r​o​l​s​ ​v​i​s​i​b​i​l​i​t​y​ ​o​n​l​y​ ​a​n​d​ ​d​o​e​s​ ​n​o​t​ ​g​u​a​r​a​n​t​e​e​ ​t​h​a​t​ ​t​h​i​n​k​i​n​g​ ​t​o​k​e​n​ ​u​s​a​g​e​ ​o​r​ ​b​i​l​l​i​n​g​ ​i​s​ ​d​i​s​a​b​l​e​d​.​ ​A​l​l​o​w​e​d​ ​v​a​l​u​e​s​:​ ​`​t​r​u​e​`​,​ ​`​f​a​l​s​e​`​.
   */
  PARAM_INCLUDE_THOUGHTS_AI_DESCRIPTION: string
  /**
   * G​o​o​g​l​e​ ​S​e​a​r​c​h​ ​G​r​o​u​n​d​i​n​g
   */
  PARAM_ENABLE_SEARCH_DISPLAY_NAME: string
  /**
   * E​n​a​b​l​e​ ​G​o​o​g​l​e​ ​S​e​a​r​c​h​ ​t​o​ ​g​e​n​e​r​a​t​e​ ​i​m​a​g​e​s​ ​b​a​s​e​d​ ​o​n​ ​r​e​a​l​-​t​i​m​e​ ​i​n​f​o​r​m​a​t​i​o​n​.
   */
  PARAM_ENABLE_SEARCH_HINT: string
  /**
   * `​t​r​u​e​`​ ​e​n​a​b​l​e​s​ ​G​o​o​g​l​e​ ​S​e​a​r​c​h​ ​g​r​o​u​n​d​i​n​g​ ​f​o​r​ ​p​r​o​m​p​t​s​ ​t​h​a​t​ ​d​e​p​e​n​d​ ​o​n​ ​r​e​a​l​-​t​i​m​e​ ​o​r​ ​f​a​c​t​u​a​l​ ​e​x​t​e​r​n​a​l​ ​i​n​f​o​r​m​a​t​i​o​n​.​ ​`​f​a​l​s​e​`​ ​d​i​s​a​b​l​e​s​ ​i​t​.​ ​T​h​i​s​ ​p​a​r​a​m​e​t​e​r​ ​i​s​ ​a​p​p​l​i​e​d​ ​o​n​l​y​ ​f​o​r​ ​`​g​e​m​i​n​i​-​3​.​1​-​f​l​a​s​h​-​i​m​a​g​e​-​p​r​e​v​i​e​w​`​ ​a​n​d​ ​`​g​e​m​i​n​i​-​3​-​p​r​o​-​i​m​a​g​e​-​p​r​e​v​i​e​w​`​;​ ​`​g​e​m​i​n​i​-​2​.​5​-​f​l​a​s​h​-​i​m​a​g​e​`​ ​i​g​n​o​r​e​s​ ​i​t​.​ ​A​l​l​o​w​e​d​ ​v​a​l​u​e​s​:​ ​`​t​r​u​e​`​,​ ​`​f​a​l​s​e​`​.
   */
  PARAM_ENABLE_SEARCH_AI_DESCRIPTION: string
  /**
   * U​p​l​o​a​d​ ​t​o​ ​S​t​o​r​a​g​e
   */
  PARAM_OUTPUT_STORAGE_DISPLAY_NAME: string
  /**
   * W​h​e​n​ ​e​n​a​b​l​e​d​,​ ​u​p​l​o​a​d​s​ ​t​h​e​ ​g​e​n​e​r​a​t​e​d​ ​i​m​a​g​e​ ​t​o​ ​p​e​r​s​i​s​t​e​n​t​ ​o​b​j​e​c​t​ ​s​t​o​r​a​g​e​.​ ​W​h​e​n​ ​d​i​s​a​b​l​e​d​,​ ​r​e​t​u​r​n​s​ ​t​h​e​ ​i​m​a​g​e​ ​i​n​ ​m​e​m​o​r​y​.
   */
  PARAM_OUTPUT_STORAGE_HINT: string
  /**
   * `​t​r​u​e​`​ ​u​p​l​o​a​d​s​ ​t​h​e​ ​g​e​n​e​r​a​t​e​d​ ​i​m​a​g​e​ ​t​o​ ​p​e​r​s​i​s​t​e​n​t​ ​s​t​o​r​a​g​e​.​ ​`​f​a​l​s​e​`​ ​r​e​t​u​r​n​s​ ​a​n​ ​i​n​-​m​e​m​o​r​y​ ​f​i​l​e​ ​r​e​f​e​r​e​n​c​e​ ​o​n​l​y​.​ ​A​l​l​o​w​e​d​ ​v​a​l​u​e​s​:​ ​`​t​r​u​e​`​,​ ​`​f​a​l​s​e​`​.
   */
  PARAM_OUTPUT_STORAGE_AI_DESCRIPTION: string
  /**
   * G​e​n​e​r​a​t​e​ ​I​m​a​g​e
   */
  GENERATE_IMAGE_DISPLAY_NAME: string
  /**
   * G​e​n​e​r​a​t​e​ ​a​n​ ​i​m​a​g​e​ ​f​r​o​m​ ​a​ ​t​e​x​t​ ​p​r​o​m​p​t​ ​u​s​i​n​g​ ​N​a​n​o​ ​B​a​n​a​n​a​.
   */
  GENERATE_IMAGE_DESCRIPTION: string
  /**
   * P​r​o​m​p​t
   */
  GENERATE_IMAGE_PROMPT_DISPLAY_NAME: string
  /**
   * W​r​i​t​e​ ​t​h​e​ ​f​u​l​l​ ​i​m​a​g​e​ ​g​e​n​e​r​a​t​i​o​n​ ​i​n​s​t​r​u​c​t​i​o​n​,​ ​i​n​c​l​u​d​i​n​g​ ​s​c​e​n​e​,​ ​s​u​b​j​e​c​t​s​,​ ​c​o​m​p​o​s​i​t​i​o​n​,​ ​s​t​y​l​e​,​ ​l​i​g​h​t​i​n​g​,​ ​t​e​x​t​ ​t​o​ ​r​e​n​d​e​r​,​ ​a​n​d​ ​i​m​p​o​r​t​a​n​t​ ​c​o​n​s​t​r​a​i​n​t​s​.​ ​V​a​l​u​e​ ​t​y​p​e​:​ ​f​r​e​e​-​f​o​r​m​ ​s​t​r​i​n​g​.
   */
  GENERATE_IMAGE_PROMPT_AI_DESCRIPTION: string
  /**
   * D​e​s​c​r​i​b​e​ ​t​h​e​ ​i​m​a​g​e​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​g​e​n​e​r​a​t​e​.​ ​B​e​ ​s​p​e​c​i​f​i​c​ ​a​b​o​u​t​ ​s​t​y​l​e​,​ ​l​i​g​h​t​i​n​g​,​ ​c​o​m​p​o​s​i​t​i​o​n​,​ ​a​n​d​ ​d​e​t​a​i​l​s​.
   */
  GENERATE_IMAGE_PROMPT_HINT: string
  /**
   * A​ ​p​h​o​t​o​r​e​a​l​i​s​t​i​c​ ​c​l​o​s​e​-​u​p​ ​o​f​ ​a​ ​c​e​r​a​m​i​c​ ​c​o​f​f​e​e​ ​m​u​g​ ​o​n​ ​a​ ​p​o​l​i​s​h​e​d​ ​c​o​n​c​r​e​t​e​ ​s​u​r​f​a​c​e​.​.​.
   */
  GENERATE_IMAGE_PROMPT_PLACEHOLDER: string
  /**
   * E​d​i​t​ ​I​m​a​g​e
   */
  EDIT_IMAGE_DISPLAY_NAME: string
  /**
   * E​d​i​t​ ​a​n​ ​e​x​i​s​t​i​n​g​ ​i​m​a​g​e​ ​u​s​i​n​g​ ​a​ ​t​e​x​t​ ​p​r​o​m​p​t​ ​w​i​t​h​ ​N​a​n​o​ ​B​a​n​a​n​a​.
   */
  EDIT_IMAGE_DESCRIPTION: string
  /**
   * P​r​o​m​p​t
   */
  EDIT_IMAGE_PROMPT_DISPLAY_NAME: string
  /**
   * W​r​i​t​e​ ​t​h​e​ ​f​u​l​l​ ​e​d​i​t​ ​i​n​s​t​r​u​c​t​i​o​n​ ​f​o​r​ ​t​h​e​ ​i​n​p​u​t​ ​i​m​a​g​e​,​ ​i​n​c​l​u​d​i​n​g​ ​w​h​a​t​ ​t​o​ ​c​h​a​n​g​e​,​ ​p​r​e​s​e​r​v​e​,​ ​r​e​m​o​v​e​,​ ​a​d​d​,​ ​o​r​ ​r​e​s​t​y​l​e​.​ ​V​a​l​u​e​ ​t​y​p​e​:​ ​f​r​e​e​-​f​o​r​m​ ​s​t​r​i​n​g​.
   */
  EDIT_IMAGE_PROMPT_AI_DESCRIPTION: string
  /**
   * D​e​s​c​r​i​b​e​ ​t​h​e​ ​c​h​a​n​g​e​s​ ​t​o​ ​m​a​k​e​ ​t​o​ ​t​h​e​ ​i​m​a​g​e​.​ ​B​e​ ​s​p​e​c​i​f​i​c​ ​a​b​o​u​t​ ​w​h​a​t​ ​t​o​ ​a​d​d​,​ ​r​e​m​o​v​e​,​ ​o​r​ ​m​o​d​i​f​y​.
   */
  EDIT_IMAGE_PROMPT_HINT: string
  /**
   * A​d​d​ ​a​ ​s​m​a​l​l​ ​w​i​z​a​r​d​ ​h​a​t​ ​o​n​ ​t​h​e​ ​c​a​t​'​s​ ​h​e​a​d​.​.​.
   */
  EDIT_IMAGE_PROMPT_PLACEHOLDER: string
  /**
   * I​n​p​u​t​ ​I​m​a​g​e
   */
  EDIT_IMAGE_IMAGE_DISPLAY_NAME: string
  /**
   * T​h​e​ ​i​m​a​g​e​ ​t​o​ ​e​d​i​t​.​ ​A​c​c​e​p​t​s​ ​a​ ​f​i​l​e​_​r​e​f​ ​i​n​p​u​t​ ​a​n​d​ ​s​u​p​p​o​r​t​s​ ​J​P​E​G​,​ ​P​N​G​,​ ​G​I​F​,​ ​a​n​d​ ​W​e​b​P​ ​f​o​r​m​a​t​s​.
   */
  EDIT_IMAGE_IMAGE_HINT: string
  /**
   * W​r​i​t​e​ ​a​ ​`​f​i​l​e​_​r​e​f​`​ ​v​a​l​u​e​ ​p​o​i​n​t​i​n​g​ ​t​o​ ​t​h​e​ ​s​o​u​r​c​e​ ​i​m​a​g​e​ ​t​o​ ​e​d​i​t​.​ ​S​u​p​p​o​r​t​e​d​ ​s​o​u​r​c​e​ ​i​m​a​g​e​ ​f​o​r​m​a​t​s​ ​i​n​c​l​u​d​e​ ​J​P​E​G​,​ ​P​N​G​,​ ​G​I​F​,​ ​a​n​d​ ​W​e​b​P​.​ ​V​a​l​u​e​ ​t​y​p​e​:​ ​`​f​i​l​e​_​r​e​f​`​.
   */
  EDIT_IMAGE_IMAGE_AI_DESCRIPTION: string
}

export type TranslationFunctions = {
  /**
   * Nano Banana Image Studio
   */
  PLUGIN_DISPLAY_NAME: () => LocalizedString
  /**
   * Generate and edit images with Google's Gemini image models, including Nano Banana and Nano Banana Pro.
   */
  PLUGIN_DESCRIPTION: () => LocalizedString
  /**
   * Gemini API Key
   */
  CREDENTIAL_DISPLAY_NAME: () => LocalizedString
  /**
   * API key used to authenticate Google Gemini API requests.
   */
  CREDENTIAL_DESCRIPTION: () => LocalizedString
  /**
   * Gemini API Key
   */
  CREDENTIAL_API_KEY_DISPLAY_NAME: () => LocalizedString
  /**
   * Paste your Gemini API key from Google AI Studio.
   */
  CREDENTIAL_API_KEY_HINT: () => LocalizedString
  /**
   * AIza...
   */
  CREDENTIAL_API_KEY_PLACEHOLDER: () => LocalizedString
  /**
   * Base URL
   */
  CREDENTIAL_BASE_URL_DISPLAY_NAME: () => LocalizedString
  /**
   * Optional custom Gemini-compatible endpoint. If not provided, the official Google endpoint will be used.
   */
  CREDENTIAL_BASE_URL_HINT: () => LocalizedString
  /**
   * https://your-proxy.example.com
   */
  CREDENTIAL_BASE_URL_PLACEHOLDER: () => LocalizedString
  /**
   * Gemini Credential
   */
  PARAM_CREDENTIAL_DISPLAY_NAME: () => LocalizedString
  /**
   * Credential ID string referencing a configured `gemini-api-key` credential. Write the selected credential ID value.
   */
  PARAM_CREDENTIAL_AI_DESCRIPTION: () => LocalizedString
  /**
   * Model
   */
  PARAM_MODEL_DISPLAY_NAME: () => LocalizedString
  /**
   * Select the Nano Banana model to use.
   */
  PARAM_MODEL_HINT: () => LocalizedString
  /**
   * `gemini-3.1-flash-image-preview` supports the broadest parameter set in this tool, including thinking, Google Search grounding, `512` resolution, and extra aspect ratios `1:4`, `4:1`, `1:8`, `8:1`. `gemini-3-pro-image-preview` does not use thinking and does not support `512` or the extra aspect ratios. `gemini-2.5-flash-image` ignores `resolution`, `thinking_level`, `include_thoughts`, and `enable_search_grounding` in this implementation. Allowed values: `gemini-3.1-flash-image-preview`, `gemini-3-pro-image-preview`, `gemini-2.5-flash-image`.
   */
  PARAM_MODEL_AI_DESCRIPTION: () => LocalizedString
  /**
   * Nano Banana 2 (3.1 Flash Image)
   */
  PARAM_MODEL_OPTION_GEMINI_31_FLASH_IMAGE: () => LocalizedString
  /**
   * Nano Banana Pro (3 Pro Image)
   */
  PARAM_MODEL_OPTION_GEMINI_3_PRO_IMAGE: () => LocalizedString
  /**
   * Nano Banana (2.5 Flash Image)
   */
  PARAM_MODEL_OPTION_GEMINI_25_FLASH_IMAGE: () => LocalizedString
  /**
   * Aspect Ratio
   */
  PARAM_ASPECT_RATIO_DISPLAY_NAME: () => LocalizedString
  /**
   * Aspect ratio of the generated image.
   */
  PARAM_ASPECT_RATIO_HINT: () => LocalizedString
  /**
   * Base aspect ratios `1:1`, `2:3`, `3:2`, `3:4`, `4:3`, `4:5`, `5:4`, `9:16`, `16:9`, `21:9` are supported broadly. Extra ratios `1:4`, `4:1`, `1:8`, `8:1` are only applied with `gemini-3.1-flash-image-preview`. Allowed values: `1:1`, `16:9`, `9:16`, `4:3`, `3:4`, `3:2`, `2:3`, `5:4`, `4:5`, `21:9`, `4:1`, `1:4`, `8:1`, `1:8`.
   */
  PARAM_ASPECT_RATIO_AI_DESCRIPTION: () => LocalizedString
  /**
   * 1:1 (Square)
   */
  PARAM_ASPECT_RATIO_OPTION_1_1: () => LocalizedString
  /**
   * 16:9 (Landscape)
   */
  PARAM_ASPECT_RATIO_OPTION_16_9: () => LocalizedString
  /**
   * 9:16 (Portrait)
   */
  PARAM_ASPECT_RATIO_OPTION_9_16: () => LocalizedString
  /**
   * 4:3 (Standard)
   */
  PARAM_ASPECT_RATIO_OPTION_4_3: () => LocalizedString
  /**
   * 3:4 (Portrait)
   */
  PARAM_ASPECT_RATIO_OPTION_3_4: () => LocalizedString
  /**
   * 3:2 (Photo)
   */
  PARAM_ASPECT_RATIO_OPTION_3_2: () => LocalizedString
  /**
   * 2:3 (Portrait Photo)
   */
  PARAM_ASPECT_RATIO_OPTION_2_3: () => LocalizedString
  /**
   * 5:4 (Large Format)
   */
  PARAM_ASPECT_RATIO_OPTION_5_4: () => LocalizedString
  /**
   * 4:5 (Portrait Large)
   */
  PARAM_ASPECT_RATIO_OPTION_4_5: () => LocalizedString
  /**
   * 21:9 (Ultra-wide)
   */
  PARAM_ASPECT_RATIO_OPTION_21_9: () => LocalizedString
  /**
   * 4:1 (Banner - NB2 only)
   */
  PARAM_ASPECT_RATIO_OPTION_4_1: () => LocalizedString
  /**
   * 1:4 (Tall Banner - NB2 only)
   */
  PARAM_ASPECT_RATIO_OPTION_1_4: () => LocalizedString
  /**
   * 8:1 (Ultra Banner - NB2 only)
   */
  PARAM_ASPECT_RATIO_OPTION_8_1: () => LocalizedString
  /**
   * 1:8 (Ultra Tall - NB2 only)
   */
  PARAM_ASPECT_RATIO_OPTION_1_8: () => LocalizedString
  /**
   * Resolution
   */
  PARAM_RESOLUTION_DISPLAY_NAME: () => LocalizedString
  /**
   * Output resolution of the generated image. Applies to Nano Banana 2 and Nano Banana Pro only.
   */
  PARAM_RESOLUTION_HINT: () => LocalizedString
  /**
   * `gemini-3.1-flash-image-preview` supports `512`, `1K`, `2K`, `4K`. `gemini-3-pro-image-preview` supports `1K`, `2K`, `4K` only. `gemini-2.5-flash-image` does not support selectable resolution in the Gemini docs; it uses fixed output sizes based on aspect ratio instead, such as `1:1` -> `1024x1024`, `16:9` -> `1344x768`, and `9:16` -> `768x1344`. In this implementation, `gemini-2.5-flash-image` ignores this parameter. Allowed values: `512`, `1K`, `2K`, `4K`.
   */
  PARAM_RESOLUTION_AI_DESCRIPTION: () => LocalizedString
  /**
   * 512 (0.5K - NB2 only)
   */
  PARAM_RESOLUTION_OPTION_512: () => LocalizedString
  /**
   * 1K (Default)
   */
  PARAM_RESOLUTION_OPTION_1K: () => LocalizedString
  /**
   * 2K (High)
   */
  PARAM_RESOLUTION_OPTION_2K: () => LocalizedString
  /**
   * 4K (Ultra High)
   */
  PARAM_RESOLUTION_OPTION_4K: () => LocalizedString
  /**
   * Thinking Level
   */
  PARAM_THINKING_LEVEL_DISPLAY_NAME: () => LocalizedString
  /**
   * Controls reasoning depth. 'high' improves quality for complex prompts but increases latency. Only affects Nano Banana 2.
   */
  PARAM_THINKING_LEVEL_HINT: () => LocalizedString
  /**
   * This parameter is applied only with `gemini-3.1-flash-image-preview`; other models ignore it. Allowed values: `minimal`, `high`.
   */
  PARAM_THINKING_LEVEL_AI_DESCRIPTION: () => LocalizedString
  /**
   * Minimal (Faster)
   */
  PARAM_THINKING_LEVEL_OPTION_MINIMAL: () => LocalizedString
  /**
   * High (Better Quality)
   */
  PARAM_THINKING_LEVEL_OPTION_HIGH: () => LocalizedString
  /**
   * Return Thoughts
   */
  PARAM_INCLUDE_THOUGHTS_DISPLAY_NAME: () => LocalizedString
  /**
   * When enabled, the model's thought summary is returned in the tool response. Billing for thinking tokens still applies whether this is enabled or not.
   */
  PARAM_INCLUDE_THOUGHTS_HINT: () => LocalizedString
  /**
   * `true` returns the model's thought summary when thinking is supported. `false` hides it. This parameter is applied only with `gemini-3.1-flash-image-preview`; other models ignore it. This controls visibility only and does not guarantee that thinking token usage or billing is disabled. Allowed values: `true`, `false`.
   */
  PARAM_INCLUDE_THOUGHTS_AI_DESCRIPTION: () => LocalizedString
  /**
   * Google Search Grounding
   */
  PARAM_ENABLE_SEARCH_DISPLAY_NAME: () => LocalizedString
  /**
   * Enable Google Search to generate images based on real-time information.
   */
  PARAM_ENABLE_SEARCH_HINT: () => LocalizedString
  /**
   * `true` enables Google Search grounding for prompts that depend on real-time or factual external information. `false` disables it. This parameter is applied only for `gemini-3.1-flash-image-preview` and `gemini-3-pro-image-preview`; `gemini-2.5-flash-image` ignores it. Allowed values: `true`, `false`.
   */
  PARAM_ENABLE_SEARCH_AI_DESCRIPTION: () => LocalizedString
  /**
   * Upload to Storage
   */
  PARAM_OUTPUT_STORAGE_DISPLAY_NAME: () => LocalizedString
  /**
   * When enabled, uploads the generated image to persistent object storage. When disabled, returns the image in memory.
   */
  PARAM_OUTPUT_STORAGE_HINT: () => LocalizedString
  /**
   * `true` uploads the generated image to persistent storage. `false` returns an in-memory file reference only. Allowed values: `true`, `false`.
   */
  PARAM_OUTPUT_STORAGE_AI_DESCRIPTION: () => LocalizedString
  /**
   * Generate Image
   */
  GENERATE_IMAGE_DISPLAY_NAME: () => LocalizedString
  /**
   * Generate an image from a text prompt using Nano Banana.
   */
  GENERATE_IMAGE_DESCRIPTION: () => LocalizedString
  /**
   * Prompt
   */
  GENERATE_IMAGE_PROMPT_DISPLAY_NAME: () => LocalizedString
  /**
   * Write the full image generation instruction, including scene, subjects, composition, style, lighting, text to render, and important constraints. Value type: free-form string.
   */
  GENERATE_IMAGE_PROMPT_AI_DESCRIPTION: () => LocalizedString
  /**
   * Describe the image you want to generate. Be specific about style, lighting, composition, and details.
   */
  GENERATE_IMAGE_PROMPT_HINT: () => LocalizedString
  /**
   * A photorealistic close-up of a ceramic coffee mug on a polished concrete surface...
   */
  GENERATE_IMAGE_PROMPT_PLACEHOLDER: () => LocalizedString
  /**
   * Edit Image
   */
  EDIT_IMAGE_DISPLAY_NAME: () => LocalizedString
  /**
   * Edit an existing image using a text prompt with Nano Banana.
   */
  EDIT_IMAGE_DESCRIPTION: () => LocalizedString
  /**
   * Prompt
   */
  EDIT_IMAGE_PROMPT_DISPLAY_NAME: () => LocalizedString
  /**
   * Write the full edit instruction for the input image, including what to change, preserve, remove, add, or restyle. Value type: free-form string.
   */
  EDIT_IMAGE_PROMPT_AI_DESCRIPTION: () => LocalizedString
  /**
   * Describe the changes to make to the image. Be specific about what to add, remove, or modify.
   */
  EDIT_IMAGE_PROMPT_HINT: () => LocalizedString
  /**
   * Add a small wizard hat on the cat's head...
   */
  EDIT_IMAGE_PROMPT_PLACEHOLDER: () => LocalizedString
  /**
   * Input Image
   */
  EDIT_IMAGE_IMAGE_DISPLAY_NAME: () => LocalizedString
  /**
   * The image to edit. Accepts a file_ref input and supports JPEG, PNG, GIF, and WebP formats.
   */
  EDIT_IMAGE_IMAGE_HINT: () => LocalizedString
  /**
   * Write a `file_ref` value pointing to the source image to edit. Supported source image formats include JPEG, PNG, GIF, and WebP. Value type: `file_ref`.
   */
  EDIT_IMAGE_IMAGE_AI_DESCRIPTION: () => LocalizedString
}

export type Formatters = {}
