// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type {
  BaseTranslation as BaseTranslationType,
  LocalizedString,
} from "typesafe-i18n"

export type BaseTranslation = BaseTranslationType
export type BaseLocale = "en-US"

export type Locales = "en-US" | "zh-Hans"

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
  /**
   * G​o​o​g​l​e​ ​C​a​l​e​n​d​a​r
   */
  PLUGIN_DISPLAY_NAME: string
  /**
   * I​n​t​e​g​r​a​t​e​ ​G​o​o​g​l​e​ ​C​a​l​e​n​d​a​r​ ​i​n​t​o​ ​A​t​o​m​e​m​o​ ​w​o​r​k​f​l​o​w​s
   */
  PLUGIN_DESCRIPTION: string
  /**
   * G​o​o​g​l​e​ ​C​a​l​e​n​d​a​r​ ​O​A​u​t​h​2
   */
  GOOGLE_CALENDAR_CREDENTIAL_DISPLAY_NAME: string
  /**
   * O​A​u​t​h​2​ ​f​o​r​ ​G​o​o​g​l​e​ ​C​a​l​e​n​d​a​r​ ​A​P​I​.​ ​E​n​t​e​r​ ​C​l​i​e​n​t​ ​I​D​ ​a​n​d​ ​C​l​i​e​n​t​ ​S​e​c​r​e​t​ ​f​r​o​m​ ​G​o​o​g​l​e​ ​C​l​o​u​d​ ​C​o​n​s​o​l​e​,​ ​t​h​e​n​ ​a​u​t​h​o​r​i​z​e​ ​v​i​a​ ​t​h​e​ ​O​A​u​t​h​ ​f​l​o​w​ ​t​o​ ​c​o​n​n​e​c​t​ ​y​o​u​r​ ​c​a​l​e​n​d​a​r​.
   */
  GOOGLE_CALENDAR_CREDENTIAL_DESCRIPTION: string
  /**
   * C​l​i​e​n​t​ ​I​D
   */
  CLIENT_ID_DISPLAY_NAME: string
  /**
   * O​A​u​t​h​ ​2​.​0​ ​C​l​i​e​n​t​ ​I​D​ ​f​r​o​m​ ​G​o​o​g​l​e​ ​C​l​o​u​d​ ​C​o​n​s​o​l​e
   */
  CLIENT_ID_HINT: string
  /**
   * x​x​x​.​a​p​p​s​.​g​o​o​g​l​e​u​s​e​r​c​o​n​t​e​n​t​.​c​o​m
   */
  CLIENT_ID_PLACEHOLDER: string
  /**
   * C​l​i​e​n​t​ ​S​e​c​r​e​t
   */
  CLIENT_SECRET_DISPLAY_NAME: string
  /**
   * O​A​u​t​h​ ​2​.​0​ ​C​l​i​e​n​t​ ​S​e​c​r​e​t​ ​f​r​o​m​ ​G​o​o​g​l​e​ ​C​l​o​u​d​ ​C​o​n​s​o​l​e
   */
  CLIENT_SECRET_HINT: string
  /**
   * G​o​o​g​l​e​ ​C​a​l​e​n​d​a​r​ ​C​r​e​d​e​n​t​i​a​l
   */
  CREDENTIAL_DISPLAY_NAME: string
  /**
   * C​a​l​e​n​d​a​r​ ​I​D
   */
  CALENDAR_ID_DISPLAY_NAME: string
  /**
   * U​s​e​ ​"​p​r​i​m​a​r​y​"​ ​f​o​r​ ​y​o​u​r​ ​m​a​i​n​ ​c​a​l​e​n​d​a​r​,​ ​o​r​ ​a​ ​c​a​l​e​n​d​a​r​ ​e​m​a​i​l​ ​a​d​d​r​e​s​s​.​ ​R​u​n​ ​"​L​i​s​t​ ​C​a​l​e​n​d​a​r​s​"​ ​t​o​ ​f​i​n​d​ ​I​D​s​.
   */
  CALENDAR_ID_HINT: string
  /**
   * p​r​i​m​a​r​y​ ​o​r​ ​u​s​e​r​@​g​r​o​u​p​.​c​a​l​e​n​d​a​r​.​g​o​o​g​l​e​.​c​o​m
   */
  CALENDAR_ID_PLACEHOLDER: string
  /**
   * E​v​e​n​t​ ​I​D
   */
  EVENT_ID_DISPLAY_NAME: string
  /**
   * T​h​e​ ​u​n​i​q​u​e​ ​i​d​e​n​t​i​f​i​e​r​ ​o​f​ ​t​h​e​ ​e​v​e​n​t
   */
  EVENT_ID_HINT: string
  /**
   * T​i​t​l​e
   */
  SUMMARY_DISPLAY_NAME: string
  /**
   * E​v​e​n​t​ ​t​i​t​l​e​/​s​u​m​m​a​r​y
   */
  SUMMARY_HINT: string
  /**
   * M​e​e​t​i​n​g​ ​w​i​t​h​ ​t​e​a​m
   */
  SUMMARY_PLACEHOLDER: string
  /**
   * D​e​s​c​r​i​p​t​i​o​n
   */
  DESCRIPTION_DISPLAY_NAME: string
  /**
   * E​v​e​n​t​ ​d​e​s​c​r​i​p​t​i​o​n
   */
  DESCRIPTION_HINT: string
  /**
   * L​o​c​a​t​i​o​n
   */
  LOCATION_DISPLAY_NAME: string
  /**
   * E​v​e​n​t​ ​l​o​c​a​t​i​o​n​ ​(​a​d​d​r​e​s​s​ ​o​r​ ​p​l​a​c​e​ ​n​a​m​e​)
   */
  LOCATION_HINT: string
  /**
   * C​o​n​f​e​r​e​n​c​e​ ​R​o​o​m​ ​A
   */
  LOCATION_PLACEHOLDER: string
  /**
   * S​t​a​r​t​ ​T​i​m​e
   */
  START_DATETIME_DISPLAY_NAME: string
  /**
   * R​F​C​3​3​3​9​ ​d​a​t​e​t​i​m​e​ ​w​i​t​h​ ​t​i​m​e​z​o​n​e​ ​o​f​f​s​e​t​.​ ​E​x​a​m​p​l​e​s​:​ ​2​0​2​5​-​0​3​-​1​8​T​0​9​:​0​0​:​0​0​+​0​8​:​0​0​ ​(​U​T​C​+​8​)​,​ ​2​0​2​5​-​0​3​-​1​8​T​0​1​:​0​0​:​0​0​Z​ ​(​U​T​C​)​,​ ​2​0​2​5​-​0​3​-​1​8​T​0​9​:​0​0​:​0​0​-​0​5​:​0​0​ ​(​E​S​T​)
   */
  START_DATETIME_HINT: string
  /**
   * E​n​d​ ​T​i​m​e
   */
  END_DATETIME_DISPLAY_NAME: string
  /**
   * R​F​C​3​3​3​9​ ​d​a​t​e​t​i​m​e​ ​w​i​t​h​ ​t​i​m​e​z​o​n​e​ ​o​f​f​s​e​t​,​ ​m​u​s​t​ ​b​e​ ​a​f​t​e​r​ ​s​t​a​r​t​ ​t​i​m​e​.​ ​E​x​a​m​p​l​e​s​:​ ​2​0​2​5​-​0​3​-​1​8​T​1​0​:​0​0​:​0​0​+​0​8​:​0​0​,​ ​2​0​2​5​-​0​3​-​1​8​T​0​2​:​0​0​:​0​0​Z
   */
  END_DATETIME_HINT: string
  /**
   * T​i​m​e​z​o​n​e
   */
  TIMEZONE_DISPLAY_NAME: string
  /**
   * I​A​N​A​ ​t​i​m​e​z​o​n​e​ ​n​a​m​e​.​ ​E​x​a​m​p​l​e​s​:​ ​A​s​i​a​/​S​h​a​n​g​h​a​i​,​ ​A​m​e​r​i​c​a​/​L​o​s​_​A​n​g​e​l​e​s​,​ ​E​u​r​o​p​e​/​L​o​n​d​o​n​,​ ​A​s​i​a​/​T​o​k​y​o​,​ ​U​T​C
   */
  TIMEZONE_HINT: string
  /**
   * A​s​i​a​/​S​h​a​n​g​h​a​i
   */
  TIMEZONE_PLACEHOLDER: string
  /**
   * M​a​x​ ​R​e​s​u​l​t​s
   */
  MAX_RESULTS_DISPLAY_NAME: string
  /**
   * M​a​x​i​m​u​m​ ​n​u​m​b​e​r​ ​o​f​ ​e​v​e​n​t​s​ ​t​o​ ​r​e​t​u​r​n​ ​(​1​-​2​5​0​0​)
   */
  MAX_RESULTS_HINT: string
  /**
   * T​i​m​e​ ​M​i​n
   */
  TIME_MIN_DISPLAY_NAME: string
  /**
   * L​o​w​e​r​ ​b​o​u​n​d​ ​(​e​x​c​l​u​s​i​v​e​)​ ​f​o​r​ ​e​v​e​n​t​ ​e​n​d​ ​t​i​m​e​.​ ​R​F​C​3​3​3​9​ ​w​i​t​h​ ​t​i​m​e​z​o​n​e​ ​o​f​f​s​e​t​.​ ​E​x​a​m​p​l​e​:​ ​2​0​2​5​-​0​3​-​0​1​T​0​0​:​0​0​:​0​0​Z
   */
  TIME_MIN_HINT: string
  /**
   * T​i​m​e​ ​M​a​x
   */
  TIME_MAX_DISPLAY_NAME: string
  /**
   * U​p​p​e​r​ ​b​o​u​n​d​ ​(​e​x​c​l​u​s​i​v​e​)​ ​f​o​r​ ​e​v​e​n​t​ ​s​t​a​r​t​ ​t​i​m​e​,​ ​m​u​s​t​ ​b​e​ ​a​f​t​e​r​ ​T​i​m​e​ ​M​i​n​.​ ​R​F​C​3​3​3​9​ ​w​i​t​h​ ​t​i​m​e​z​o​n​e​ ​o​f​f​s​e​t​.​ ​E​x​a​m​p​l​e​:​ ​2​0​2​5​-​0​3​-​3​1​T​2​3​:​5​9​:​5​9​Z
   */
  TIME_MAX_HINT: string
  /**
   * L​i​s​t​ ​E​v​e​n​t​s
   */
  LIST_EVENTS_DISPLAY_NAME: string
  /**
   * L​i​s​t​ ​e​v​e​n​t​s​ ​f​r​o​m​ ​a​ ​G​o​o​g​l​e​ ​C​a​l​e​n​d​a​r
   */
  LIST_EVENTS_DESCRIPTION: string
  /**
   * C​r​e​a​t​e​ ​E​v​e​n​t
   */
  CREATE_EVENT_DISPLAY_NAME: string
  /**
   * C​r​e​a​t​e​ ​a​ ​n​e​w​ ​e​v​e​n​t​ ​o​n​ ​G​o​o​g​l​e​ ​C​a​l​e​n​d​a​r
   */
  CREATE_EVENT_DESCRIPTION: string
  /**
   * G​e​t​ ​E​v​e​n​t
   */
  GET_EVENT_DISPLAY_NAME: string
  /**
   * G​e​t​ ​a​ ​s​i​n​g​l​e​ ​e​v​e​n​t​ ​b​y​ ​I​D
   */
  GET_EVENT_DESCRIPTION: string
  /**
   * U​p​d​a​t​e​ ​E​v​e​n​t
   */
  UPDATE_EVENT_DISPLAY_NAME: string
  /**
   * U​p​d​a​t​e​ ​a​n​ ​e​x​i​s​t​i​n​g​ ​e​v​e​n​t
   */
  UPDATE_EVENT_DESCRIPTION: string
  /**
   * D​e​l​e​t​e​ ​E​v​e​n​t
   */
  DELETE_EVENT_DISPLAY_NAME: string
  /**
   * D​e​l​e​t​e​ ​a​n​ ​e​v​e​n​t​ ​f​r​o​m​ ​G​o​o​g​l​e​ ​C​a​l​e​n​d​a​r
   */
  DELETE_EVENT_DESCRIPTION: string
  /**
   * L​i​s​t​ ​C​a​l​e​n​d​a​r​s
   */
  LIST_CALENDARS_DISPLAY_NAME: string
  /**
   * L​i​s​t​ ​c​a​l​e​n​d​a​r​s​ ​i​n​ ​t​h​e​ ​u​s​e​r​'​s​ ​c​a​l​e​n​d​a​r​ ​l​i​s​t
   */
  LIST_CALENDARS_DESCRIPTION: string
  /**
   * G​e​t​ ​C​a​l​e​n​d​a​r
   */
  GET_CALENDAR_DISPLAY_NAME: string
  /**
   * G​e​t​ ​c​a​l​e​n​d​a​r​ ​m​e​t​a​d​a​t​a​ ​b​y​ ​I​D
   */
  GET_CALENDAR_DESCRIPTION: string
  /**
   * C​r​e​a​t​e​ ​C​a​l​e​n​d​a​r
   */
  CREATE_CALENDAR_DISPLAY_NAME: string
  /**
   * C​r​e​a​t​e​ ​a​ ​n​e​w​ ​s​e​c​o​n​d​a​r​y​ ​c​a​l​e​n​d​a​r
   */
  CREATE_CALENDAR_DESCRIPTION: string
  /**
   * U​p​d​a​t​e​ ​C​a​l​e​n​d​a​r
   */
  UPDATE_CALENDAR_DISPLAY_NAME: string
  /**
   * U​p​d​a​t​e​ ​c​a​l​e​n​d​a​r​ ​m​e​t​a​d​a​t​a
   */
  UPDATE_CALENDAR_DESCRIPTION: string
  /**
   * D​e​l​e​t​e​ ​C​a​l​e​n​d​a​r
   */
  DELETE_CALENDAR_DISPLAY_NAME: string
  /**
   * D​e​l​e​t​e​ ​a​ ​s​e​c​o​n​d​a​r​y​ ​c​a​l​e​n​d​a​r
   */
  DELETE_CALENDAR_DESCRIPTION: string
  /**
   * ⚠​️​ ​C​l​e​a​r​ ​C​a​l​e​n​d​a​r
   */
  CLEAR_CALENDAR_DISPLAY_NAME: string
  /**
   * D​A​N​G​E​R​O​U​S​:​ ​P​e​r​m​a​n​e​n​t​l​y​ ​d​e​l​e​t​e​ ​A​L​L​ ​e​v​e​n​t​s​ ​f​r​o​m​ ​t​h​e​ ​p​r​i​m​a​r​y​ ​c​a​l​e​n​d​a​r​.​ ​T​h​i​s​ ​o​p​e​r​a​t​i​o​n​ ​o​n​l​y​ ​w​o​r​k​s​ ​o​n​ ​t​h​e​ ​p​r​i​m​a​r​y​ ​c​a​l​e​n​d​a​r​ ​a​n​d​ ​c​a​n​n​o​t​ ​b​e​ ​u​n​d​o​n​e​.
   */
  CLEAR_CALENDAR_DESCRIPTION: string
  /**
   * G​e​t​ ​C​a​l​e​n​d​a​r​ ​L​i​s​t​ ​E​n​t​r​y
   */
  GET_CALENDAR_LIST_DISPLAY_NAME: string
  /**
   * G​e​t​ ​a​ ​s​i​n​g​l​e​ ​c​a​l​e​n​d​a​r​ ​f​r​o​m​ ​t​h​e​ ​u​s​e​r​'​s​ ​c​a​l​e​n​d​a​r​ ​l​i​s​t
   */
  GET_CALENDAR_LIST_DESCRIPTION: string
  /**
   * R​e​m​o​v​e​ ​C​a​l​e​n​d​a​r​ ​f​r​o​m​ ​L​i​s​t
   */
  DELETE_CALENDAR_LIST_DISPLAY_NAME: string
  /**
   * R​e​m​o​v​e​ ​a​ ​c​a​l​e​n​d​a​r​ ​f​r​o​m​ ​t​h​e​ ​u​s​e​r​'​s​ ​c​a​l​e​n​d​a​r​ ​l​i​s​t
   */
  DELETE_CALENDAR_LIST_DESCRIPTION: string
  /**
   * U​p​d​a​t​e​ ​C​a​l​e​n​d​a​r​ ​L​i​s​t​ ​E​n​t​r​y
   */
  UPDATE_CALENDAR_LIST_DISPLAY_NAME: string
  /**
   * U​p​d​a​t​e​ ​u​s​e​r​-​s​p​e​c​i​f​i​c​ ​c​a​l​e​n​d​a​r​ ​l​i​s​t​ ​p​r​o​p​e​r​t​i​e​s
   */
  UPDATE_CALENDAR_LIST_DESCRIPTION: string
  /**
   * A​d​d​ ​C​a​l​e​n​d​a​r​ ​t​o​ ​L​i​s​t
   */
  INSERT_CALENDAR_LIST_DISPLAY_NAME: string
  /**
   * A​d​d​ ​a​n​ ​e​x​i​s​t​i​n​g​ ​c​a​l​e​n​d​a​r​ ​t​o​ ​t​h​e​ ​u​s​e​r​'​s​ ​c​a​l​e​n​d​a​r​ ​l​i​s​t
   */
  INSERT_CALENDAR_LIST_DESCRIPTION: string
  /**
   * C​a​l​e​n​d​a​r​ ​T​i​t​l​e
   */
  CALENDAR_SUMMARY_DISPLAY_NAME: string
  /**
   * C​a​l​e​n​d​a​r​ ​n​a​m​e​/​t​i​t​l​e
   */
  CALENDAR_SUMMARY_HINT: string
  /**
   * C​a​l​e​n​d​a​r​ ​d​e​s​c​r​i​p​t​i​o​n
   */
  CALENDAR_DESCRIPTION_HINT: string
  /**
   * G​e​o​g​r​a​p​h​i​c​ ​l​o​c​a​t​i​o​n​ ​o​f​ ​t​h​e​ ​c​a​l​e​n​d​a​r
   */
  CALENDAR_LOCATION_HINT: string
  /**
   * D​e​f​a​u​l​t​ ​t​i​m​e​z​o​n​e​ ​i​n​ ​I​A​N​A​ ​f​o​r​m​a​t​.​ ​E​x​a​m​p​l​e​s​:​ ​A​s​i​a​/​S​h​a​n​g​h​a​i​,​ ​A​m​e​r​i​c​a​/​L​o​s​_​A​n​g​e​l​e​s​,​ ​E​u​r​o​p​e​/​L​o​n​d​o​n
   */
  CALENDAR_TIMEZONE_HINT: string
  /**
   * D​e​f​a​u​l​t​ ​R​e​m​i​n​d​e​r​s
   */
  DEFAULT_REMINDERS_DISPLAY_NAME: string
  /**
   * U​s​e​r​ ​d​e​f​a​u​l​t​ ​r​e​m​i​n​d​e​r​s​ ​(​m​e​t​h​o​d​:​ ​e​m​a​i​l​/​p​o​p​u​p​,​ ​m​i​n​u​t​e​s​:​ ​n​u​m​b​e​r​)
   */
  DEFAULT_REMINDERS_HINT: string
  /**
   * L​i​s​t​ ​E​v​e​n​t​ ​I​n​s​t​a​n​c​e​s
   */
  LIST_EVENT_INSTANCES_DISPLAY_NAME: string
  /**
   * L​i​s​t​ ​a​l​l​ ​i​n​s​t​a​n​c​e​s​ ​o​f​ ​a​ ​r​e​c​u​r​r​i​n​g​ ​e​v​e​n​t
   */
  LIST_EVENT_INSTANCES_DESCRIPTION: string
  /**
   * M​o​v​e​ ​E​v​e​n​t
   */
  MOVE_EVENT_DISPLAY_NAME: string
  /**
   * M​o​v​e​ ​a​n​ ​e​v​e​n​t​ ​t​o​ ​a​n​o​t​h​e​r​ ​c​a​l​e​n​d​a​r
   */
  MOVE_EVENT_DESCRIPTION: string
  /**
   * Q​u​i​c​k​ ​A​d​d​ ​E​v​e​n​t
   */
  QUICK_ADD_EVENT_DISPLAY_NAME: string
  /**
   * C​r​e​a​t​e​ ​a​n​ ​e​v​e​n​t​ ​f​r​o​m​ ​s​i​m​p​l​e​ ​n​a​t​u​r​a​l​ ​l​a​n​g​u​a​g​e​ ​t​e​x​t
   */
  QUICK_ADD_EVENT_DESCRIPTION: string
  /**
   * D​e​s​t​i​n​a​t​i​o​n​ ​C​a​l​e​n​d​a​r​ ​I​D
   */
  DESTINATION_CALENDAR_DISPLAY_NAME: string
  /**
   * T​a​r​g​e​t​ ​c​a​l​e​n​d​a​r​ ​f​o​r​ ​t​h​e​ ​e​v​e​n​t
   */
  DESTINATION_CALENDAR_HINT: string
  /**
   * E​v​e​n​t​ ​T​e​x​t
   */
  QUICK_ADD_TEXT_DISPLAY_NAME: string
  /**
   * N​a​t​u​r​a​l​ ​l​a​n​g​u​a​g​e​,​ ​e​.​g​.​ ​'​D​i​n​n​e​r​ ​w​i​t​h​ ​J​o​h​n​ ​t​o​m​o​r​r​o​w​ ​a​t​ ​7​p​m​'
   */
  QUICK_ADD_TEXT_HINT: string
  /**
   * M​e​e​t​i​n​g​ ​t​o​m​o​r​r​o​w​ ​a​t​ ​2​p​m
   */
  QUICK_ADD_TEXT_PLACEHOLDER: string
  /**
   * G​e​t​ ​S​e​t​t​i​n​g
   */
  SETTINGS_GET_DISPLAY_NAME: string
  /**
   * G​e​t​ ​a​ ​s​i​n​g​l​e​ ​u​s​e​r​ ​s​e​t​t​i​n​g
   */
  SETTINGS_GET_DESCRIPTION: string
  /**
   * L​i​s​t​ ​S​e​t​t​i​n​g​s
   */
  SETTINGS_LIST_DISPLAY_NAME: string
  /**
   * L​i​s​t​ ​a​l​l​ ​u​s​e​r​ ​s​e​t​t​i​n​g​s
   */
  SETTINGS_LIST_DESCRIPTION: string
  /**
   * S​e​t​t​i​n​g​ ​I​D
   */
  SETTING_ID_DISPLAY_NAME: string
  /**
   * e​.​g​.​ ​t​i​m​e​z​o​n​e​,​ ​l​o​c​a​l​e​,​ ​w​e​e​k​S​t​a​r​t
   */
  SETTING_ID_HINT: string
  /**
   * G​e​t​ ​C​o​l​o​r​s
   */
  COLORS_GET_DISPLAY_NAME: string
  /**
   * G​e​t​ ​c​a​l​e​n​d​a​r​ ​a​n​d​ ​e​v​e​n​t​ ​c​o​l​o​r​ ​d​e​f​i​n​i​t​i​o​n​s
   */
  COLORS_GET_DESCRIPTION: string
  /**
   * Q​u​e​r​y​ ​F​r​e​e​/​B​u​s​y
   */
  FREEBUSY_QUERY_DISPLAY_NAME: string
  /**
   * Q​u​e​r​y​ ​b​u​s​y​/​f​r​e​e​ ​s​t​a​t​u​s​ ​f​o​r​ ​c​a​l​e​n​d​a​r​s​ ​i​n​ ​a​ ​t​i​m​e​ ​r​a​n​g​e
   */
  FREEBUSY_QUERY_DESCRIPTION: string
  /**
   * C​a​l​e​n​d​a​r​ ​I​D​s
   */
  CALENDAR_IDS_DISPLAY_NAME: string
  /**
   * C​o​m​m​a​-​s​e​p​a​r​a​t​e​d​ ​c​a​l​e​n​d​a​r​ ​I​D​s​ ​t​o​ ​q​u​e​r​y
   */
  CALENDAR_IDS_HINT: string
  /**
   * S​t​a​r​t​ ​o​f​ ​t​i​m​e​ ​r​a​n​g​e​ ​(​r​e​q​u​i​r​e​d​)​.​ ​R​F​C​3​3​3​9​ ​w​i​t​h​ ​t​i​m​e​z​o​n​e​ ​o​f​f​s​e​t​.​ ​E​x​a​m​p​l​e​:​ ​2​0​2​5​-​0​3​-​1​8​T​0​0​:​0​0​:​0​0​Z​ ​o​r​ ​2​0​2​5​-​0​3​-​1​8​T​0​8​:​0​0​:​0​0​+​0​8​:​0​0
   */
  TIME_MIN_REQUIRED_HINT: string
  /**
   * E​n​d​ ​o​f​ ​t​i​m​e​ ​r​a​n​g​e​ ​(​r​e​q​u​i​r​e​d​)​,​ ​m​u​s​t​ ​b​e​ ​a​f​t​e​r​ ​s​t​a​r​t​.​ ​R​F​C​3​3​3​9​ ​w​i​t​h​ ​t​i​m​e​z​o​n​e​ ​o​f​f​s​e​t​.​ ​E​x​a​m​p​l​e​:​ ​2​0​2​5​-​0​3​-​1​9​T​0​0​:​0​0​:​0​0​Z​ ​o​r​ ​2​0​2​5​-​0​3​-​1​9​T​0​8​:​0​0​:​0​0​+​0​8​:​0​0
   */
  TIME_MAX_REQUIRED_HINT: string
  /**
   * S​e​l​e​c​t​e​d
   */
  SELECTED_DISPLAY_NAME: string
  /**
   * W​h​e​t​h​e​r​ ​t​o​ ​s​h​o​w​ ​t​h​i​s​ ​c​a​l​e​n​d​a​r​ ​i​n​ ​t​h​e​ ​U​I
   */
  SELECTED_HINT: string
  /**
   * C​o​l​o​r​ ​I​D
   */
  COLOR_ID_DISPLAY_NAME: string
  /**
   * P​r​e​d​e​f​i​n​e​d​ ​c​o​l​o​r​ ​I​D​ ​(​1​-​1​1​ ​f​o​r​ ​c​a​l​e​n​d​a​r​)
   */
  COLOR_ID_HINT: string
  /**
   * t​i​m​e​z​o​n​e
   */
  SETTING_ID_PLACEHOLDER: string
  /**
   * p​r​i​m​a​r​y​,​u​s​e​r​@​e​x​a​m​p​l​e​.​c​o​m
   */
  CALENDAR_IDS_PLACEHOLDER: string
  /**
   * A​l​l​-​d​a​y​ ​E​v​e​n​t
   */
  IS_ALL_DAY_EVENT_DISPLAY_NAME: string
  /**
   * I​f​ ​e​n​a​b​l​e​d​,​ ​u​s​e​ ​d​a​t​e​ ​o​n​l​y​ ​(​n​o​ ​t​i​m​e​)
   */
  IS_ALL_DAY_EVENT_HINT: string
  /**
   * I​n​c​l​u​d​e​ ​D​e​t​a​i​l​s
   */
  INCLUDE_DETAILS_DISPLAY_NAME: string
  /**
   * A​d​d​ ​d​e​s​c​r​i​p​t​i​o​n​ ​a​n​d​ ​l​o​c​a​t​i​o​n
   */
  INCLUDE_DETAILS_HINT: string
  /**
   * F​i​l​t​e​r​ ​b​y​ ​T​i​m​e​ ​R​a​n​g​e
   */
  USE_TIME_RANGE_DISPLAY_NAME: string
  /**
   * L​i​m​i​t​ ​r​e​s​u​l​t​s​ ​t​o​ ​a​ ​s​p​e​c​i​f​i​c​ ​t​i​m​e​ ​w​i​n​d​o​w
   */
  USE_TIME_RANGE_HINT: string
  /**
   * U​p​d​a​t​e​ ​T​i​m​e
   */
  UPDATE_TIME_DISPLAY_NAME: string
  /**
   * C​h​a​n​g​e​ ​e​v​e​n​t​ ​s​t​a​r​t​/​e​n​d​ ​t​i​m​e
   */
  UPDATE_TIME_HINT: string
  /**
   * S​t​a​r​t​ ​D​a​t​e
   */
  START_DATE_DISPLAY_NAME: string
  /**
   * S​t​a​r​t​ ​d​a​t​e​ ​f​o​r​ ​a​l​l​-​d​a​y​ ​e​v​e​n​t​s​,​ ​f​o​r​m​a​t​:​ ​y​y​y​y​-​m​m​-​d​d​.​ ​E​x​a​m​p​l​e​:​ ​2​0​2​5​-​0​3​-​1​8
   */
  START_DATE_HINT: string
  /**
   * 2​0​2​5​-​0​3​-​1​8
   */
  START_DATE_PLACEHOLDER: string
  /**
   * E​n​d​ ​D​a​t​e
   */
  END_DATE_DISPLAY_NAME: string
  /**
   * E​n​d​ ​d​a​t​e​ ​(​e​x​c​l​u​s​i​v​e​)​ ​f​o​r​ ​a​l​l​-​d​a​y​ ​e​v​e​n​t​s​,​ ​m​u​s​t​ ​b​e​ ​a​f​t​e​r​ ​s​t​a​r​t​ ​d​a​t​e​.​ ​F​o​r​ ​a​ ​s​i​n​g​l​e​ ​d​a​y​,​ ​s​e​t​ ​t​o​ ​t​h​e​ ​n​e​x​t​ ​d​a​y​.​ ​E​x​a​m​p​l​e​:​ ​o​n​e​-​d​a​y​ ​e​v​e​n​t​ ​o​n​ ​M​a​r​ ​1​8​ ​→​ ​e​n​d​_​d​a​t​e​ ​=​ ​2​0​2​5​-​0​3​-​1​9
   */
  END_DATE_HINT: string
  /**
   * 2​0​2​5​-​0​3​-​1​9
   */
  END_DATE_PLACEHOLDER: string
  /**
   * S​e​n​d​ ​U​p​d​a​t​e​s
   */
  SEND_UPDATES_DISPLAY_NAME: string
  /**
   * W​h​e​t​h​e​r​ ​t​o​ ​s​e​n​d​ ​n​o​t​i​f​i​c​a​t​i​o​n​s​ ​a​b​o​u​t​ ​t​h​e​ ​e​v​e​n​t​ ​c​h​a​n​g​e
   */
  SEND_UPDATES_HINT: string
  /**
   * N​o​n​e
   */
  SEND_UPDATES_NONE: string
  /**
   * A​l​l​ ​g​u​e​s​t​s
   */
  SEND_UPDATES_ALL: string
  /**
   * E​x​t​e​r​n​a​l​ ​g​u​e​s​t​s​ ​o​n​l​y
   */
  SEND_UPDATES_EXTERNAL_ONLY: string
  /**
   * V​i​s​i​b​i​l​i​t​y
   */
  VISIBILITY_DISPLAY_NAME: string
  /**
   * V​i​s​i​b​i​l​i​t​y​ ​o​f​ ​t​h​e​ ​e​v​e​n​t
   */
  VISIBILITY_HINT: string
  /**
   * D​e​f​a​u​l​t
   */
  VISIBILITY_DEFAULT: string
  /**
   * P​u​b​l​i​c
   */
  VISIBILITY_PUBLIC: string
  /**
   * P​r​i​v​a​t​e
   */
  VISIBILITY_PRIVATE: string
  /**
   * C​o​n​f​i​d​e​n​t​i​a​l
   */
  VISIBILITY_CONFIDENTIAL: string
  /**
   * S​h​o​w​ ​M​e​ ​A​s
   */
  TRANSPARENCY_DISPLAY_NAME: string
  /**
   * W​h​e​t​h​e​r​ ​t​h​e​ ​e​v​e​n​t​ ​b​l​o​c​k​s​ ​t​i​m​e​ ​o​n​ ​t​h​e​ ​c​a​l​e​n​d​a​r
   */
  TRANSPARENCY_HINT: string
  /**
   * B​u​s​y
   */
  TRANSPARENCY_OPAQUE: string
  /**
   * A​v​a​i​l​a​b​l​e
   */
  TRANSPARENCY_TRANSPARENT: string
  /**
   * S​t​a​t​u​s
   */
  EVENT_STATUS_DISPLAY_NAME: string
  /**
   * S​t​a​t​u​s​ ​o​f​ ​t​h​e​ ​e​v​e​n​t
   */
  EVENT_STATUS_HINT: string
  /**
   * C​o​n​f​i​r​m​e​d
   */
  EVENT_STATUS_CONFIRMED: string
  /**
   * T​e​n​t​a​t​i​v​e
   */
  EVENT_STATUS_TENTATIVE: string
  /**
   * E​v​e​n​t​ ​C​o​l​o​r
   */
  EVENT_COLOR_ID_DISPLAY_NAME: string
  /**
   * C​o​l​o​r​ ​I​D​ ​f​r​o​m​ ​c​o​l​o​r​s​ ​e​n​d​p​o​i​n​t​ ​(​1​-​1​1​)​.​ ​U​s​e​ ​'​G​e​t​ ​C​o​l​o​r​s​'​ ​t​o​ ​s​e​e​ ​o​p​t​i​o​n​s​.
   */
  EVENT_COLOR_ID_HINT: string
  /**
   * S​e​a​r​c​h​ ​Q​u​e​r​y
   */
  SEARCH_QUERY_DISPLAY_NAME: string
  /**
   * F​r​e​e​ ​t​e​x​t​ ​s​e​a​r​c​h​ ​i​n​ ​s​u​m​m​a​r​y​,​ ​d​e​s​c​r​i​p​t​i​o​n​,​ ​l​o​c​a​t​i​o​n​,​ ​a​t​t​e​n​d​e​e​s​,​ ​e​t​c​.
   */
  SEARCH_QUERY_HINT: string
  /**
   * t​e​a​m​ ​m​e​e​t​i​n​g
   */
  SEARCH_QUERY_PLACEHOLDER: string
  /**
   * O​r​d​e​r​ ​B​y
   */
  ORDER_BY_DISPLAY_NAME: string
  /**
   * R​e​s​u​l​t​ ​o​r​d​e​r​.​ ​'​s​t​a​r​t​T​i​m​e​'​ ​r​e​q​u​i​r​e​s​ ​s​i​n​g​l​e​E​v​e​n​t​s​=​t​r​u​e​.
   */
  ORDER_BY_HINT: string
  /**
   * S​t​a​r​t​ ​T​i​m​e
   */
  ORDER_BY_START_TIME: string
  /**
   * L​a​s​t​ ​M​o​d​i​f​i​e​d
   */
  ORDER_BY_UPDATED: string
  /**
   * E​x​p​a​n​d​ ​R​e​c​u​r​r​i​n​g
   */
  SINGLE_EVENTS_DISPLAY_NAME: string
  /**
   * E​x​p​a​n​d​ ​r​e​c​u​r​r​i​n​g​ ​e​v​e​n​t​s​ ​i​n​t​o​ ​i​n​d​i​v​i​d​u​a​l​ ​i​n​s​t​a​n​c​e​s​.​ ​R​e​q​u​i​r​e​d​ ​f​o​r​ ​o​r​d​e​r​B​y​=​s​t​a​r​t​T​i​m​e​.
   */
  SINGLE_EVENTS_HINT: string
  /**
   * S​h​o​w​ ​D​e​l​e​t​e​d
   */
  SHOW_DELETED_DISPLAY_NAME: string
  /**
   * I​n​c​l​u​d​e​ ​c​a​n​c​e​l​l​e​d​/​d​e​l​e​t​e​d​ ​e​v​e​n​t​s​ ​i​n​ ​r​e​s​u​l​t​s
   */
  SHOW_DELETED_HINT: string
  /**
   * R​e​c​u​r​r​e​n​c​e​ ​R​u​l​e
   */
  RECURRENCE_DISPLAY_NAME: string
  /**
   * R​R​U​L​E​ ​p​e​r​ ​R​F​C​5​5​4​5​,​ ​e​.​g​.​ ​R​R​U​L​E​:​F​R​E​Q​=​W​E​E​K​L​Y​;​B​Y​D​A​Y​=​M​O​,​W​E​,​F​R
   */
  RECURRENCE_HINT: string
  /**
   * R​R​U​L​E​:​F​R​E​Q​=​D​A​I​L​Y​;​C​O​U​N​T​=​5
   */
  RECURRENCE_PLACEHOLDER: string
  /**
   * A​t​t​e​n​d​e​e​s
   */
  ATTENDEES_DISPLAY_NAME: string
  /**
   * C​o​m​m​a​-​s​e​p​a​r​a​t​e​d​ ​e​m​a​i​l​ ​a​d​d​r​e​s​s​e​s​ ​o​f​ ​a​t​t​e​n​d​e​e​s
   */
  ATTENDEES_HINT: string
  /**
   * u​s​e​r​1​@​e​x​a​m​p​l​e​.​c​o​m​,​u​s​e​r​2​@​e​x​a​m​p​l​e​.​c​o​m
   */
  ATTENDEES_PLACEHOLDER: string
  /**
   * A​d​v​a​n​c​e​d​ ​O​p​t​i​o​n​s
   */
  USE_ADVANCED_OPTIONS_DISPLAY_NAME: string
  /**
   * S​h​o​w​ ​a​d​d​i​t​i​o​n​a​l​ ​e​v​e​n​t​ ​o​p​t​i​o​n​s​:​ ​v​i​s​i​b​i​l​i​t​y​,​ ​t​r​a​n​s​p​a​r​e​n​c​y​,​ ​s​t​a​t​u​s​,​ ​c​o​l​o​r​,​ ​r​e​c​u​r​r​e​n​c​e​ ​a​n​d​ ​a​t​t​e​n​d​e​e​s
   */
  USE_ADVANCED_OPTIONS_HINT: string
  /**
   * C​o​n​f​e​r​e​n​c​e​ ​D​a​t​a​ ​V​e​r​s​i​o​n
   */
  CONFERENCE_DATA_VERSION_DISPLAY_NAME: string
  /**
   * 0​ ​=​ ​n​o​ ​c​o​n​f​e​r​e​n​c​e​ ​d​a​t​a​,​ ​1​ ​=​ ​e​n​a​b​l​e​ ​c​o​n​f​e​r​e​n​c​e​ ​c​r​e​a​t​i​o​n​/​c​o​p​y
   */
  CONFERENCE_DATA_VERSION_HINT: string
  /**
   * S​e​c​o​n​d​a​r​y​ ​c​a​l​e​n​d​a​r​ ​I​D​ ​(​e​m​a​i​l​ ​a​d​d​r​e​s​s​)​.​ ​C​a​n​n​o​t​ ​u​s​e​ ​"​p​r​i​m​a​r​y​"​.​ ​R​u​n​ ​"​L​i​s​t​ ​C​a​l​e​n​d​a​r​s​"​ ​t​o​ ​f​i​n​d​ ​I​D​s​.
   */
  SECONDARY_CALENDAR_ID_HINT: string
  /**
   * a​b​c​d​e​f​1​2​3​4​@​g​r​o​u​p​.​c​a​l​e​n​d​a​r​.​g​o​o​g​l​e​.​c​o​m
   */
  SECONDARY_CALENDAR_ID_PLACEHOLDER: string
}

export type TranslationFunctions = {
  /**
   * Google Calendar
   */
  PLUGIN_DISPLAY_NAME: () => LocalizedString
  /**
   * Integrate Google Calendar into Atomemo workflows
   */
  PLUGIN_DESCRIPTION: () => LocalizedString
  /**
   * Google Calendar OAuth2
   */
  GOOGLE_CALENDAR_CREDENTIAL_DISPLAY_NAME: () => LocalizedString
  /**
   * OAuth2 for Google Calendar API. Enter Client ID and Client Secret from Google Cloud Console, then authorize via the OAuth flow to connect your calendar.
   */
  GOOGLE_CALENDAR_CREDENTIAL_DESCRIPTION: () => LocalizedString
  /**
   * Client ID
   */
  CLIENT_ID_DISPLAY_NAME: () => LocalizedString
  /**
   * OAuth 2.0 Client ID from Google Cloud Console
   */
  CLIENT_ID_HINT: () => LocalizedString
  /**
   * xxx.apps.googleusercontent.com
   */
  CLIENT_ID_PLACEHOLDER: () => LocalizedString
  /**
   * Client Secret
   */
  CLIENT_SECRET_DISPLAY_NAME: () => LocalizedString
  /**
   * OAuth 2.0 Client Secret from Google Cloud Console
   */
  CLIENT_SECRET_HINT: () => LocalizedString
  /**
   * Google Calendar Credential
   */
  CREDENTIAL_DISPLAY_NAME: () => LocalizedString
  /**
   * Calendar ID
   */
  CALENDAR_ID_DISPLAY_NAME: () => LocalizedString
  /**
   * Use "primary" for your main calendar, or a calendar email address. Run "List Calendars" to find IDs.
   */
  CALENDAR_ID_HINT: () => LocalizedString
  /**
   * primary or user@group.calendar.google.com
   */
  CALENDAR_ID_PLACEHOLDER: () => LocalizedString
  /**
   * Event ID
   */
  EVENT_ID_DISPLAY_NAME: () => LocalizedString
  /**
   * The unique identifier of the event
   */
  EVENT_ID_HINT: () => LocalizedString
  /**
   * Title
   */
  SUMMARY_DISPLAY_NAME: () => LocalizedString
  /**
   * Event title/summary
   */
  SUMMARY_HINT: () => LocalizedString
  /**
   * Meeting with team
   */
  SUMMARY_PLACEHOLDER: () => LocalizedString
  /**
   * Description
   */
  DESCRIPTION_DISPLAY_NAME: () => LocalizedString
  /**
   * Event description
   */
  DESCRIPTION_HINT: () => LocalizedString
  /**
   * Location
   */
  LOCATION_DISPLAY_NAME: () => LocalizedString
  /**
   * Event location (address or place name)
   */
  LOCATION_HINT: () => LocalizedString
  /**
   * Conference Room A
   */
  LOCATION_PLACEHOLDER: () => LocalizedString
  /**
   * Start Time
   */
  START_DATETIME_DISPLAY_NAME: () => LocalizedString
  /**
   * RFC3339 datetime with timezone offset. Examples: 2025-03-18T09:00:00+08:00 (UTC+8), 2025-03-18T01:00:00Z (UTC), 2025-03-18T09:00:00-05:00 (EST)
   */
  START_DATETIME_HINT: () => LocalizedString
  /**
   * End Time
   */
  END_DATETIME_DISPLAY_NAME: () => LocalizedString
  /**
   * RFC3339 datetime with timezone offset, must be after start time. Examples: 2025-03-18T10:00:00+08:00, 2025-03-18T02:00:00Z
   */
  END_DATETIME_HINT: () => LocalizedString
  /**
   * Timezone
   */
  TIMEZONE_DISPLAY_NAME: () => LocalizedString
  /**
   * IANA timezone name. Examples: Asia/Shanghai, America/Los_Angeles, Europe/London, Asia/Tokyo, UTC
   */
  TIMEZONE_HINT: () => LocalizedString
  /**
   * Asia/Shanghai
   */
  TIMEZONE_PLACEHOLDER: () => LocalizedString
  /**
   * Max Results
   */
  MAX_RESULTS_DISPLAY_NAME: () => LocalizedString
  /**
   * Maximum number of events to return (1-2500)
   */
  MAX_RESULTS_HINT: () => LocalizedString
  /**
   * Time Min
   */
  TIME_MIN_DISPLAY_NAME: () => LocalizedString
  /**
   * Lower bound (exclusive) for event end time. RFC3339 with timezone offset. Example: 2025-03-01T00:00:00Z
   */
  TIME_MIN_HINT: () => LocalizedString
  /**
   * Time Max
   */
  TIME_MAX_DISPLAY_NAME: () => LocalizedString
  /**
   * Upper bound (exclusive) for event start time, must be after Time Min. RFC3339 with timezone offset. Example: 2025-03-31T23:59:59Z
   */
  TIME_MAX_HINT: () => LocalizedString
  /**
   * List Events
   */
  LIST_EVENTS_DISPLAY_NAME: () => LocalizedString
  /**
   * List events from a Google Calendar
   */
  LIST_EVENTS_DESCRIPTION: () => LocalizedString
  /**
   * Create Event
   */
  CREATE_EVENT_DISPLAY_NAME: () => LocalizedString
  /**
   * Create a new event on Google Calendar
   */
  CREATE_EVENT_DESCRIPTION: () => LocalizedString
  /**
   * Get Event
   */
  GET_EVENT_DISPLAY_NAME: () => LocalizedString
  /**
   * Get a single event by ID
   */
  GET_EVENT_DESCRIPTION: () => LocalizedString
  /**
   * Update Event
   */
  UPDATE_EVENT_DISPLAY_NAME: () => LocalizedString
  /**
   * Update an existing event
   */
  UPDATE_EVENT_DESCRIPTION: () => LocalizedString
  /**
   * Delete Event
   */
  DELETE_EVENT_DISPLAY_NAME: () => LocalizedString
  /**
   * Delete an event from Google Calendar
   */
  DELETE_EVENT_DESCRIPTION: () => LocalizedString
  /**
   * List Calendars
   */
  LIST_CALENDARS_DISPLAY_NAME: () => LocalizedString
  /**
   * List calendars in the user's calendar list
   */
  LIST_CALENDARS_DESCRIPTION: () => LocalizedString
  /**
   * Get Calendar
   */
  GET_CALENDAR_DISPLAY_NAME: () => LocalizedString
  /**
   * Get calendar metadata by ID
   */
  GET_CALENDAR_DESCRIPTION: () => LocalizedString
  /**
   * Create Calendar
   */
  CREATE_CALENDAR_DISPLAY_NAME: () => LocalizedString
  /**
   * Create a new secondary calendar
   */
  CREATE_CALENDAR_DESCRIPTION: () => LocalizedString
  /**
   * Update Calendar
   */
  UPDATE_CALENDAR_DISPLAY_NAME: () => LocalizedString
  /**
   * Update calendar metadata
   */
  UPDATE_CALENDAR_DESCRIPTION: () => LocalizedString
  /**
   * Delete Calendar
   */
  DELETE_CALENDAR_DISPLAY_NAME: () => LocalizedString
  /**
   * Delete a secondary calendar
   */
  DELETE_CALENDAR_DESCRIPTION: () => LocalizedString
  /**
   * ⚠️ Clear Calendar
   */
  CLEAR_CALENDAR_DISPLAY_NAME: () => LocalizedString
  /**
   * DANGEROUS: Permanently delete ALL events from the primary calendar. This operation only works on the primary calendar and cannot be undone.
   */
  CLEAR_CALENDAR_DESCRIPTION: () => LocalizedString
  /**
   * Get Calendar List Entry
   */
  GET_CALENDAR_LIST_DISPLAY_NAME: () => LocalizedString
  /**
   * Get a single calendar from the user's calendar list
   */
  GET_CALENDAR_LIST_DESCRIPTION: () => LocalizedString
  /**
   * Remove Calendar from List
   */
  DELETE_CALENDAR_LIST_DISPLAY_NAME: () => LocalizedString
  /**
   * Remove a calendar from the user's calendar list
   */
  DELETE_CALENDAR_LIST_DESCRIPTION: () => LocalizedString
  /**
   * Update Calendar List Entry
   */
  UPDATE_CALENDAR_LIST_DISPLAY_NAME: () => LocalizedString
  /**
   * Update user-specific calendar list properties
   */
  UPDATE_CALENDAR_LIST_DESCRIPTION: () => LocalizedString
  /**
   * Add Calendar to List
   */
  INSERT_CALENDAR_LIST_DISPLAY_NAME: () => LocalizedString
  /**
   * Add an existing calendar to the user's calendar list
   */
  INSERT_CALENDAR_LIST_DESCRIPTION: () => LocalizedString
  /**
   * Calendar Title
   */
  CALENDAR_SUMMARY_DISPLAY_NAME: () => LocalizedString
  /**
   * Calendar name/title
   */
  CALENDAR_SUMMARY_HINT: () => LocalizedString
  /**
   * Calendar description
   */
  CALENDAR_DESCRIPTION_HINT: () => LocalizedString
  /**
   * Geographic location of the calendar
   */
  CALENDAR_LOCATION_HINT: () => LocalizedString
  /**
   * Default timezone in IANA format. Examples: Asia/Shanghai, America/Los_Angeles, Europe/London
   */
  CALENDAR_TIMEZONE_HINT: () => LocalizedString
  /**
   * Default Reminders
   */
  DEFAULT_REMINDERS_DISPLAY_NAME: () => LocalizedString
  /**
   * User default reminders (method: email/popup, minutes: number)
   */
  DEFAULT_REMINDERS_HINT: () => LocalizedString
  /**
   * List Event Instances
   */
  LIST_EVENT_INSTANCES_DISPLAY_NAME: () => LocalizedString
  /**
   * List all instances of a recurring event
   */
  LIST_EVENT_INSTANCES_DESCRIPTION: () => LocalizedString
  /**
   * Move Event
   */
  MOVE_EVENT_DISPLAY_NAME: () => LocalizedString
  /**
   * Move an event to another calendar
   */
  MOVE_EVENT_DESCRIPTION: () => LocalizedString
  /**
   * Quick Add Event
   */
  QUICK_ADD_EVENT_DISPLAY_NAME: () => LocalizedString
  /**
   * Create an event from simple natural language text
   */
  QUICK_ADD_EVENT_DESCRIPTION: () => LocalizedString
  /**
   * Destination Calendar ID
   */
  DESTINATION_CALENDAR_DISPLAY_NAME: () => LocalizedString
  /**
   * Target calendar for the event
   */
  DESTINATION_CALENDAR_HINT: () => LocalizedString
  /**
   * Event Text
   */
  QUICK_ADD_TEXT_DISPLAY_NAME: () => LocalizedString
  /**
   * Natural language, e.g. 'Dinner with John tomorrow at 7pm'
   */
  QUICK_ADD_TEXT_HINT: () => LocalizedString
  /**
   * Meeting tomorrow at 2pm
   */
  QUICK_ADD_TEXT_PLACEHOLDER: () => LocalizedString
  /**
   * Get Setting
   */
  SETTINGS_GET_DISPLAY_NAME: () => LocalizedString
  /**
   * Get a single user setting
   */
  SETTINGS_GET_DESCRIPTION: () => LocalizedString
  /**
   * List Settings
   */
  SETTINGS_LIST_DISPLAY_NAME: () => LocalizedString
  /**
   * List all user settings
   */
  SETTINGS_LIST_DESCRIPTION: () => LocalizedString
  /**
   * Setting ID
   */
  SETTING_ID_DISPLAY_NAME: () => LocalizedString
  /**
   * e.g. timezone, locale, weekStart
   */
  SETTING_ID_HINT: () => LocalizedString
  /**
   * Get Colors
   */
  COLORS_GET_DISPLAY_NAME: () => LocalizedString
  /**
   * Get calendar and event color definitions
   */
  COLORS_GET_DESCRIPTION: () => LocalizedString
  /**
   * Query Free/Busy
   */
  FREEBUSY_QUERY_DISPLAY_NAME: () => LocalizedString
  /**
   * Query busy/free status for calendars in a time range
   */
  FREEBUSY_QUERY_DESCRIPTION: () => LocalizedString
  /**
   * Calendar IDs
   */
  CALENDAR_IDS_DISPLAY_NAME: () => LocalizedString
  /**
   * Comma-separated calendar IDs to query
   */
  CALENDAR_IDS_HINT: () => LocalizedString
  /**
   * Start of time range (required). RFC3339 with timezone offset. Example: 2025-03-18T00:00:00Z or 2025-03-18T08:00:00+08:00
   */
  TIME_MIN_REQUIRED_HINT: () => LocalizedString
  /**
   * End of time range (required), must be after start. RFC3339 with timezone offset. Example: 2025-03-19T00:00:00Z or 2025-03-19T08:00:00+08:00
   */
  TIME_MAX_REQUIRED_HINT: () => LocalizedString
  /**
   * Selected
   */
  SELECTED_DISPLAY_NAME: () => LocalizedString
  /**
   * Whether to show this calendar in the UI
   */
  SELECTED_HINT: () => LocalizedString
  /**
   * Color ID
   */
  COLOR_ID_DISPLAY_NAME: () => LocalizedString
  /**
   * Predefined color ID (1-11 for calendar)
   */
  COLOR_ID_HINT: () => LocalizedString
  /**
   * timezone
   */
  SETTING_ID_PLACEHOLDER: () => LocalizedString
  /**
   * primary,user@example.com
   */
  CALENDAR_IDS_PLACEHOLDER: () => LocalizedString
  /**
   * All-day Event
   */
  IS_ALL_DAY_EVENT_DISPLAY_NAME: () => LocalizedString
  /**
   * If enabled, use date only (no time)
   */
  IS_ALL_DAY_EVENT_HINT: () => LocalizedString
  /**
   * Include Details
   */
  INCLUDE_DETAILS_DISPLAY_NAME: () => LocalizedString
  /**
   * Add description and location
   */
  INCLUDE_DETAILS_HINT: () => LocalizedString
  /**
   * Filter by Time Range
   */
  USE_TIME_RANGE_DISPLAY_NAME: () => LocalizedString
  /**
   * Limit results to a specific time window
   */
  USE_TIME_RANGE_HINT: () => LocalizedString
  /**
   * Update Time
   */
  UPDATE_TIME_DISPLAY_NAME: () => LocalizedString
  /**
   * Change event start/end time
   */
  UPDATE_TIME_HINT: () => LocalizedString
  /**
   * Start Date
   */
  START_DATE_DISPLAY_NAME: () => LocalizedString
  /**
   * Start date for all-day events, format: yyyy-mm-dd. Example: 2025-03-18
   */
  START_DATE_HINT: () => LocalizedString
  /**
   * 2025-03-18
   */
  START_DATE_PLACEHOLDER: () => LocalizedString
  /**
   * End Date
   */
  END_DATE_DISPLAY_NAME: () => LocalizedString
  /**
   * End date (exclusive) for all-day events, must be after start date. For a single day, set to the next day. Example: one-day event on Mar 18 → end_date = 2025-03-19
   */
  END_DATE_HINT: () => LocalizedString
  /**
   * 2025-03-19
   */
  END_DATE_PLACEHOLDER: () => LocalizedString
  /**
   * Send Updates
   */
  SEND_UPDATES_DISPLAY_NAME: () => LocalizedString
  /**
   * Whether to send notifications about the event change
   */
  SEND_UPDATES_HINT: () => LocalizedString
  /**
   * None
   */
  SEND_UPDATES_NONE: () => LocalizedString
  /**
   * All guests
   */
  SEND_UPDATES_ALL: () => LocalizedString
  /**
   * External guests only
   */
  SEND_UPDATES_EXTERNAL_ONLY: () => LocalizedString
  /**
   * Visibility
   */
  VISIBILITY_DISPLAY_NAME: () => LocalizedString
  /**
   * Visibility of the event
   */
  VISIBILITY_HINT: () => LocalizedString
  /**
   * Default
   */
  VISIBILITY_DEFAULT: () => LocalizedString
  /**
   * Public
   */
  VISIBILITY_PUBLIC: () => LocalizedString
  /**
   * Private
   */
  VISIBILITY_PRIVATE: () => LocalizedString
  /**
   * Confidential
   */
  VISIBILITY_CONFIDENTIAL: () => LocalizedString
  /**
   * Show Me As
   */
  TRANSPARENCY_DISPLAY_NAME: () => LocalizedString
  /**
   * Whether the event blocks time on the calendar
   */
  TRANSPARENCY_HINT: () => LocalizedString
  /**
   * Busy
   */
  TRANSPARENCY_OPAQUE: () => LocalizedString
  /**
   * Available
   */
  TRANSPARENCY_TRANSPARENT: () => LocalizedString
  /**
   * Status
   */
  EVENT_STATUS_DISPLAY_NAME: () => LocalizedString
  /**
   * Status of the event
   */
  EVENT_STATUS_HINT: () => LocalizedString
  /**
   * Confirmed
   */
  EVENT_STATUS_CONFIRMED: () => LocalizedString
  /**
   * Tentative
   */
  EVENT_STATUS_TENTATIVE: () => LocalizedString
  /**
   * Event Color
   */
  EVENT_COLOR_ID_DISPLAY_NAME: () => LocalizedString
  /**
   * Color ID from colors endpoint (1-11). Use 'Get Colors' to see options.
   */
  EVENT_COLOR_ID_HINT: () => LocalizedString
  /**
   * Search Query
   */
  SEARCH_QUERY_DISPLAY_NAME: () => LocalizedString
  /**
   * Free text search in summary, description, location, attendees, etc.
   */
  SEARCH_QUERY_HINT: () => LocalizedString
  /**
   * team meeting
   */
  SEARCH_QUERY_PLACEHOLDER: () => LocalizedString
  /**
   * Order By
   */
  ORDER_BY_DISPLAY_NAME: () => LocalizedString
  /**
   * Result order. 'startTime' requires singleEvents=true.
   */
  ORDER_BY_HINT: () => LocalizedString
  /**
   * Start Time
   */
  ORDER_BY_START_TIME: () => LocalizedString
  /**
   * Last Modified
   */
  ORDER_BY_UPDATED: () => LocalizedString
  /**
   * Expand Recurring
   */
  SINGLE_EVENTS_DISPLAY_NAME: () => LocalizedString
  /**
   * Expand recurring events into individual instances. Required for orderBy=startTime.
   */
  SINGLE_EVENTS_HINT: () => LocalizedString
  /**
   * Show Deleted
   */
  SHOW_DELETED_DISPLAY_NAME: () => LocalizedString
  /**
   * Include cancelled/deleted events in results
   */
  SHOW_DELETED_HINT: () => LocalizedString
  /**
   * Recurrence Rule
   */
  RECURRENCE_DISPLAY_NAME: () => LocalizedString
  /**
   * RRULE per RFC5545, e.g. RRULE:FREQ=WEEKLY;BYDAY=MO,WE,FR
   */
  RECURRENCE_HINT: () => LocalizedString
  /**
   * RRULE:FREQ=DAILY;COUNT=5
   */
  RECURRENCE_PLACEHOLDER: () => LocalizedString
  /**
   * Attendees
   */
  ATTENDEES_DISPLAY_NAME: () => LocalizedString
  /**
   * Comma-separated email addresses of attendees
   */
  ATTENDEES_HINT: () => LocalizedString
  /**
   * user1@example.com,user2@example.com
   */
  ATTENDEES_PLACEHOLDER: () => LocalizedString
  /**
   * Advanced Options
   */
  USE_ADVANCED_OPTIONS_DISPLAY_NAME: () => LocalizedString
  /**
   * Show additional event options: visibility, transparency, status, color, recurrence and attendees
   */
  USE_ADVANCED_OPTIONS_HINT: () => LocalizedString
  /**
   * Conference Data Version
   */
  CONFERENCE_DATA_VERSION_DISPLAY_NAME: () => LocalizedString
  /**
   * 0 = no conference data, 1 = enable conference creation/copy
   */
  CONFERENCE_DATA_VERSION_HINT: () => LocalizedString
  /**
   * Secondary calendar ID (email address). Cannot use "primary". Run "List Calendars" to find IDs.
   */
  SECONDARY_CALENDAR_ID_HINT: () => LocalizedString
  /**
   * abcdef1234@group.calendar.google.com
   */
  SECONDARY_CALENDAR_ID_PLACEHOLDER: () => LocalizedString
}

export type Formatters = {}
